In [22]:
import pandas as pd
import numpy as np
from selenium import webdriver
import time
from bs4 import BeautifulSoup
import requests
from selenium.webdriver.common.keys import Keys
import urllib

In [23]:
df=pd.read_csv('./data/죽기전에 가봐야할 101가지 여행지.csv')
df

            여행지
0           경복궁
1        삼청동 거리
2           인사동
3           조계사
4           청와대
..          ...
994         쇠소깍
995      백조일손지묘
996  휴애리 자연생활공원
997        안덕계곡
998    제주 감귤박물관

[999 rows x 1 columns]

In [24]:
df = df[567:600]

In [25]:
df = df.reset_index(drop=True)

In [26]:
df

                  여행지
0            광양 장도박물관
1   메타세콰이어 가로수길과 관방제림
2                담양온천
3                 죽녹원
4           대나무골 테마공원
5                 식영정
6                 소쇄원
7            한국 가사문학관
8           가마골과 용추계곡
9              명옥헌 원림
10          한국 대나무박물관
11                담양호
12                면앙정
13                송강정
14           섬진강 기차마을
15              압록유원지
16                천은사
17                노고단
18                화엄사
19          지리산 산수유마을
20                소록도
21            금탑사 비자림
22                나로도
23               유자공원
24      율포해수욕장과 해수녹차탕
25     소설 『태백산맥』 문학기행
26     증도 태평염전과 소금박물관
27        벌교 홍교, 대한다원
28               봇재다원
29        대원사와 티베트박물관
30                운주사
31          화순 고인돌 군락
32            조광조 유배지

In [28]:
options=webdriver.ChromeOptions()
options.add_argument('user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36')
options.add_experimental_option("excludeSwitches", ["enable-logging"])


driver=webdriver.Chrome()
url='https://www.tripadvisor.co.kr/'

reviews=[]
for i in range(len(df)):
    driver.get(url)
    search=df.여행지[i]
    driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(search)
    driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(Keys.ENTER)
    driver.switch_to.window(driver.window_handles[-1])
    time.sleep(2)
    
    # 약간 문제인 부분
    driver.find_element_by_css_selector('#BODY_BLOCK_JQUERY_REFLOW > div.page > div > div.ui_container.main_wrap > div > div > div > div > div.content_column.ui_column.is-9-desktop.is-12-tablet.is-12-mobile > div > div.ui_columns.sections_wrapper > div > div.prw_rup.prw_search_search_results.ajax-content > div > div.main_content.ui_column.is-12 > div > div:nth-child(2) > div > div > div:nth-child(1) > div > div > div > div.ui_column.is-9-desktop.is-8-mobile.is-9-tablet.content-block-column').click()
   
    driver.switch_to.window(driver.window_handles[-1])
    soup=BeautifulSoup(driver.page_source,'html.parser')
    mydata=soup.find_all('span','NejBf')
    for item in mydata:
        reviews.append(item.get_text().strip())
    driver.switch_to.window(driver.window_handles[-1])
    driver.close()
    driver.switch_to.window(driver.window_handles[0])
    driver.back()
    time.sleep(1)

C:\Users\alsgu\AppData\Local\Temp/ipykernel_17564/1243704218.py:13: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(search)
C:\Users\alsgu\AppData\Local\Temp/ipykernel_17564/1243704218.py:14: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(Keys.ENTER)
C:\Users\alsgu\AppData\Local\Temp/ipykernel_17564/1243704218.py:19: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  driver.find_element_by_css_selector('#BODY_BLOCK_JQUERY_REFLOW > div.page > div > div.ui_container.main_wrap > div > div > div > div > div.content_column.ui_column.is-9-desktop.is-12-tablet.is-12-mobile > div > div.ui_columns.sections_wrapper > div > div.prw_rup.prw_search_search_results.ajax-content > div > div.main_content.ui_column.is-12 > div > div:nth-child(2) > div > div > div:nth-child(1) > div > div > div > div.ui_column.is-9-desktop.is-8-mobile.is-9-tablet.content-block-column').click()

In [25]:
reviews

['국립자연휴양림',
 '청도의 자연휴양림 하면 운문산 자연휴양림이죠. 봄가을에는 야영하는데도 손색이 없고 숲이나 계곡도 아주 좋습니다. 강추입니다.',
 '경상북도 청도의 휴양림.',
 '자연휴양림마다 숙소를 선착순으로 특정날짜에 예약할수 있는데요.그런데 예약하기가 너무 힘들어요. 뭔가 좋은 해결책이 있으면 좋겠습니다.휴양림에서 풍욕,일광욕,피톤치드욕 하기 정말 좋아요. 숙소 예약이 조금더 쉬웠으면 합니다.',
 '청도운문산의 자연휴양림',
 '청도군에서 운영하는 자연휴양림으로 운문사근처에 위치해 있으며 한달전에 예약을 해야 방갈로를 이용할 수 있다.예약은 인터넷으로 가능하며, 주말에만 자리가 없을 뿐이지 평일은 자유로운 예약 가능(단 시즌이 않일때)',
 '자연으로 가득찬 청도 휴양림',
 '숲속을 가득 느낄 수 있는 청도의 휴양림입니다. 부산과 같은 대도시를 방문하는것도좋지만 진짜 힐링이 필요하다면 고요하고, 울창한 숲이있는 청도 운문사 휴양림 추천해봅니다!',
 '보령에 바다만 있는게 아닙니다.',
 '아이들과 같이 오면 리모델링을 끝낸 석탄박물관 꼭 구경하세요. 각종 석탄캐는 장비들과 탄광의 분위기.. 그리고 저렴한 입장료.  가까이에 성주산 휴양림이 있습니다.',
 '석탄 박물관',
 '041-934-1902매일 09:00 - 18:00월요일 휴무(추석연휴, 공휴일 다음날 휴관)성인기준 1500원, 청소년 800원 입장료있습니다.  보령의 옛 탄광이 있던 곳에 자리잡은 박물관입니다.석탄이 만들어지는 과정을 알려주기위해서 공룡이 살던 고생대이야기까지 나와요.. 탄광의 모형을 아주 크게 재작하여 볼수있는데 마치 개미굴같이 가지가 가지를 치고 땅속에서 광부의 고단했던 삶을 간접적으로 체험할수있었습니다.',
 '아이가 너무 좋아해요',
 '서해안에 탄광이 있었다는게 놀랍네요. 전시내용도 규모가 크진 않지만 재밌었고 실제 탄광구간을 볼수 있어서 좋았습니다. 체험형 엘리베이터를 아이가 너무너무 좋아했어요',
 '오래된 곳이나 산책하기가 좋다',
 '박물관 자체는 오래됬지만 주변의 산책로가 매우 좋다. 박물관을 보고 주변 산속을 산책하는 코스로 계획하면 좋고 인근의 개화예술공원과 함께 방문하면 좋음',
 '보령 석재 많고 석탄까지',
 '예전에 보령에서 석탄이 채굴을 했다고...석탄박물관이 있더라구요강원도에만 석틴광이 있는줄 알았는데좋은 경험이었어요',
 '입장료 있어요.',
 '조그만한 산골 박물관이에요. 오래된 느낌이 드네요. 입장료는 성인 1500원이고 어린이는 500원이에요. 각종 광산용 장비들이 전시되어 있답니다.',
 '석탄박물관',
 '석탄을 캐던 탄광촌과 갱도, 광부 작업자 등을 세부적으로 잘 묘사해 놓았더군요. 실제 갱도까지 내려가 볼 수 있는 것도 좋았고, 지하갱도에서 나오는 냉기로 냉방을 하고 있는 것도 신기했습니다.',
 '시원한 석탄박물관',
 '잊혀져가는 연료인 석탄에 대한 역사 기록이 남아있는 의미있는 장소에요. 지하에 갱도 체험도 할 수 있는데 냉기가 나오고 있어 시원하고 어린 아이들은 약간의 무서움을 가지고 체험하게 되는 공간이었어요.',
 '미니 연탄만들기 체험이 있어요.',
 '요즘 아이들에게 석탄이 생소한 연료인데 석탄에 대해서 알아볼 수 있고 미니 연탄만들기 체험이 있어... 귀여운 연탄을 만들어서 집에 가져갈 수 있어요..',
 '보령 전어 대하 축제 방문',
 '생각외로 관람할 것이 없다 입장료는 1500원.. 막장체험 엘리베이터만 기억에 남는다..미니연탄만들기 체험을 할수 없어 아쉬웠다',
 '낙조가 예쁜 해변이급니다',
 '여름에는 어떨지 모르겠지만 조용히 산책하기에 좋은 해변입니다. 낙조 보기도 좋구요. 서해 바다라는 것은 생걱하셔야 하구요',
 '가족여행',
 '날씨도 너무 좋았고 시간을 잘 맞춰서 바닷길 열리는 것도 봤어요! 할머니가 좋아하셔서 기분좋은 여행이었습니다! 다음에 또 가볼 예정입니다',
 '조용해서 좋았던 무창포',
 '바다도 좋았지만 숙소도 괜찮았고 단지 바로나가면 갯벌체험을 할 수 있다고 했지만 나오지 않는 조개.... ㅠㅠ 굴껍질과 돌맹이가 많아 아가들은 꼭 장화나 신발을 신고 들어가야 안전할 거 같습니다.',
 '바다가 아름다운',
 '바다가 아름다운 해수욕장입니다 특히 낙조를 볼때 매우 아름답습니다. 낮에는 바다를 느낄수 있고  밤에는 차가을 해변을  볼 수 있어서 좋았습니다. 주변에 음식도 맛납니다',
 '아이들과 갯벌체험, 낙조를 보기 위한 최고의 선택',
 '낙조가 굉장히 아름답습니다.물때를 잘 만나면 이른바 모세의 기적 체험도 할 수 있습니다.특히 아이들과 갯벌체험을 즐겁게 할 수 있습니다.인근의 대천해수욕장에 비해 조용하고 산만하지 않다는 것도 장점입니다.가족단위로 가는 분들께 추천합니다.',
 '낙조와 해변이 아름다운 무창포',
 '보령 비체팰리스 앞 해변입니다. 겨울이어서 해수욕도 못하고 바다갈라지는 날도 아니었지만 청량한 날씨와 일몰 뷰가 정말 최고였습니다',
 '방문기',
 '무창포는 대천해수욕장과는 다른 조용한 해변을 즐기기 위한 해수욕장입니다. 앞바다 섬이 조수 간만의 차가 맞으면 갯뻘을 걷는 재미가 있습니다.',
 '좋음',
 '풍광도 좋고 숨겨진 멋이있는 곳이라 더욱 좋음. 전반적으로 가격도 합리적이고 접근성도 좋아 괜찮았음.',
 '보령시의 유명한 무창포해수욕장',
 '보령시의 유명한 무창포해수욕장은 수영하기도 좋고 전어 축제나 대하 축제때 방문해도 좋다. 개인적으로는 비체팰리스에 숙박하며 즐기는 무창포를 선호',
 '한적하게 운치있는 곳',
 '대천처럼 크지는 않고 사람도 적었음 개장 전이라 더 조용했을 수도 있지만 차분히 산책하기에 좋았음 신비의 바닷길을 보러 갔지만 6, 7, 8월에는 열리지가 않아서 못 봄 꼭 보고 싶으시다면 날짜 확인하셔서 가셔야 합니다물놀이는 하지를 않아서 좋은지 잘 모르겠네요^^']

In [11]:
df[20:60]

                      여행지
20                   낙산공원
21                   명동성당
22                    청계천
23                    덕수궁
24                    정동길
25                  남대문시장
26                   서울광장
27           한국은행 화폐금융박물관
28                    숭례문
29                  농업박물관
30               남산골 한옥마을
31                     명동
32              남산과 N서울타워
33               삼성미술관 리움
34                국립중앙박물관
35                  전쟁기념관
36                  이슬람사원
37                  홍릉수목원
38             아차산북한산국립공원
39                 이화벽화마을
40                 한강시민공원
41                    서울숲
42                세종대왕기념관
43                서울 약령시장
44                    길상사
45                 최순우 옛집
46            북악산 서울 한양도성
47                    도봉산
48                     태릉
49                    독립문
50                 서대문형무소
51                  월드컵공원
52  절두산 순교성지와 양화진외국인선교사묘원
53      대한민국 국회의사당과 헌정기념관
54                  선유도공원
55                  여의도공원
56                  63스퀘어
57                국립서울현충원
58                    관악산
59                    헌인릉

In [9]:
len(reviews)

599

In [ ]:
options=webdriver.ChromeOptions()
options.add_argument('user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36')
options.add_experimental_option("excludeSwitches", ["enable-logging"])

basepath='C:/Users/이신행/OneDrive/바탕 화면/chromedriver_win32(1)/'
driver=webdriver.Chrome()
url='https://www.tripadvisor.co.kr/'

reviews=[]
for i in range(len(df)):
    driver.get(url)
    search=df.여행지[i]
    driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(search)
    driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(Keys.ENTER)
    driver.switch_to.window(driver.window_handles[-1])
    time.sleep(2)
    
    # 약간 문제인 부분
    driver.find_element_by_css_selector('#BODY_BLOCK_JQUERY_REFLOW > div.page > div > div.ui_container.main_wrap > div > div > div > div > div.content_column.ui_column.is-9-desktop.is-12-tablet.is-12-mobile > div > div.ui_columns.sections_wrapper > div > div.prw_rup.prw_search_search_results.ajax-content > div > div.main_content.ui_column.is-12 > div > div:nth-child(2) > div > div > div:nth-child(1) > div > div > div > div.ui_column.is-9-desktop.is-8-mobile.is-9-tablet.content-block-column').click()
   
    driver.switch_to.window(driver.window_handles[-1])
    soup=BeautifulSoup(driver.page_source,'html.parser')
    mydata=soup.find_all('span','NejBf')
    for item in mydata:
        reviews.append(item.get_text().strip())
    driver.switch_to.window(driver.window_handles[-1])
    driver.close()
    driver.switch_to.window(driver.window_handles[0])
    driver.back()
    time.sleep(1)

In [27]:
reviews

['대한민국의 역사',
 '대한민국의 역사가 잠들어 있는 곳. 서울을 방문했다면 꼭 방문해야 되는 곳. 경복궁은 우리의 역사다. 넓은 경복궁을 산책할 수 있는 것은 언제나 행복이다.',
 '국민이 공감하는 장소',
 '경복궁은 국민들이 자주 찾는곳으로 작성자는 주말에 자주 가족들과 방문하고 있음.특히 가족들과 방문시 옛고궁의 멋을 즐길수 있으며 쾌적한 공기와역사를 체험하고 힐링할수 있는곳임.',
 '산책하기 좋은 경복궁',
 '날씨 좋은 날 종종 산책하러 경복궁에 가는데 마음이 편온해지는 기분이라고 할까요? 특히 봄이나 가을에 산책가는 걸 추천해요!',
 'Good',
 'Goooooood 다 좋습니다 다음에 또 오고 싶네요 근처 관광지도많고 먹을거리도많네요 서울올때마다 자주이용중인데 또오고싶습니다',
 '가족단위로 방문하기 좋은곳',
 '요새 더더욱 코로나로 인해 사람 방문이 적음. 두자녀 동반시 성인 입장무료. 지금 시기에 나들이 하기 딱 좋은곳. 지하철 광화문역이나 종각역이용 편리.',
 '하늘이 내린 큰 복',
 "조선 개국 4년째인 1395년에 처음으로 세운 으뜸 궁궐이다.'하늘이 내린 큰 복' 이라는 뜻으로 경복궁이라 이름지었다.가장 아름답고 웅장한 이 경복궁은 임진왜란, 일제강점기 2번에 걸쳐 일본의 악랄하고 잔인한 파괴를 당한 악연을 갖고있다.향원정은 보수 공사로 인해 볼 수 없지만 아름다운 경회루만으로도 충분한 경복궁이다.",
 '굿',
 '한국 건축물의 아름다움을 느낄 수 있는 곳이고, 한복을 입었을 때 입장료는 무료.주변에 한복 대여점이 많으니 한번쯤 대여해서 입어보는것도 나쁘지 않을듯',
 '조선의 집',
 '조선의 성곽 안에는 박물관도 있고 경회루 등 볼것이 많다. 외국인들 및 연인들도 주변에서 한복 및 특수복장 빌려서 성을 둘러보며 데이트를 즐기기에 딱 좋다. 야간개장도 하니 잘 알아보고 올것 한국사람이라면 한번이상은 꼭와봤고 , 외국인들에게도 좋은 관광지라고 생각한다. 앞에 광화문 광장 청계천 뒤로 삼청동  이주변에 연계된 명소들도 많기 때문에 꼭 추천한다.',
 '대표 문화재',
 '대부분의 사람들이 여행을 간다면 그 나라의 유서 깊은 궁전을 찾게 된다.한국에서는 그 곳이 바로 경복궁이다.지금의 경복궁은 원래의 것보다 많이 축소되었지만 그래도 깨끗이 잘 정돈되어 있으며 위엄이 있다.',
 '경복궁',
 '몇번을 가도 감탄하게 되며 산책하기 최고인 경복궁 매번 갈때마다 정교함과 운치에 또한번 반하게 되는곳 주변에 볼거리도 많음',
 '기대 이상 만족',
 '저번달에 아주 오랜만에 다시 방문. 10년만에 재방문인데 그사이에 카페나 작은 상점 옷가게가 눈에 많이 띄었다. 서울내에 한옥건물 제발 보존 해주세요',
 '삼청동길',
 '삼청동길 한옥건물들을 볼수있는 거리중 한곳다만 예전에 비해 상권이 많이 없어졌어요..그래도 걸으면서 구경하기에는 좋아요.',
 '전통과 현대의 건축양식의 조합이 주는 이색적인 도시 풍경',
 '이 곳에서는 기와나 목재 등을 이용해 한국의 전통적인 느낌을 살린 현대식 건물이 많아서 이색적인 도시 풍경을 감상할 수 있다. 걷기만 해도 재미있다.',
 '옛 명성은 어디로...',
 "삼청동 팥죽 맛집 '서울에서 두번째로 맛있는 집'을 찾아 가면서 삼청동 메인거리를 걸으면서 곳곳에 임대 표시가 되어 있는 빈 가게들이 너무 많이 생긴 것을 보고 놀랐다. 이곳도 젠트리피케이션 때문에 자영업자들이 어려움을 겪고 있는 것 같은데 우리나라 대표적인 관광지인 궁 인근에 있어 우리나라 전통 공예품을 판매하는 상가들이 번성하면 좋을텐데... 아쉬움이 너무 컸다.",
 '옛날에 비해 많이 변한..',
 '예전엔 갈만한 식당과 카페를 줄줄이 알았는데 요즘은 정보가 없다. 그래도 갈때마다 옛 추억때문인지 정겹고 좋았다. 사람이 많이 없어서 여유롭게 가기 좋은 곳.',
 '퇴근 후 데이트코스로 좋은 길',
 '퇴근 후 데이트코스로 좋은 길입니다. 비교적 중심부에 위치해 있으며, 저녁에 데이트 목적으로 방문하는 분들이 많습니다. 정독도서관부터 시작해 식사 후 걷기에도 괜찮습니다.',
 '봄 가을 방문 강추',
 '삼청동길 방문한지 얼마 되지않았어요. 길은 좁고 다니기 불편하지만 한옥들이 몰려있고 한옥카페를 즐길수있어 좋았습니다. 더군다나 루프탑의 카페가 많아 좋았어요. 여유를 제대로 느끼실수있습니다. 그리고 수제비집 유명해요 꼭 방문해서 드셔보시길.. 짱맛',
 '삼청동길',
 '외국인이 많이 찾아오는 삼청동길, 주말에는 국내 여행객들까지 있어 걷기 힘들때도 있다. 인기있는 골목길 말고 조용하게 산책할 수 있는 코스도 있으니 잘 찾아보면 좋다.',
 '한국적인 분위기가 아름다운곳',
 '봄되면 꼭 가는 삼청동. 곳곳에 예쁜 상점들도 있고 맛있는 한식집이 많다. 사진찍기도 좋고 그냥 산책하는 것만으로도 기분 좋은 곳!',
 '데이트 장소로 추천',
 '데이트 장소로 추천받는 곳들 중 하나로 다양한 볼거리와 음식들이 있는 곳입니다 여기 떡볶이 집이 아주 유명하여 줄을 섭니다',
 '어제다녀온 인사동',
 '코로나때문인지 인사동거리에는 사람의 수는 어느정도 있긴했지만 무척이나 한산했다. 아마도 영업하는 상점들이 많이 문을 닫은것 때문이 아닌가 싶다. 커플이라면 차한잔 마시면서 30~40 분 정도 갈으면서 즐길수 있는 분위기',
 '전통과 현대미 조화를 이루는 곳',
 '오랜만에 방문한 인사동에서 전통도 체험하고 구경도 실컷 했음. 다소 아쉬웠다면 주변에 노점상들이 너무 난잡하게 산재해서 지저분하다는 느낌이 들었고 기념품 판매하는곳에서 많은 기념품들이 중국산이어서 너무 아쉬였음.',
 '인사동은 보물',
 '인사동하면 전통골목 아니겠습니까 ?전통차, 한정식 골목 등으로 나누어져 즐기기 좋은 장소지요외국인들도 많이 오고 지방에서 서울오면 꼭 보여주고 싶은곳이지요',
 '코로나로 한산한 거리입니다',
 '코로나 영향으로 주말인데도 한산합니다.주말에는 차량진입금지 입니다.낮에도 볼거리가있지만 밤에도 화려한곳입니다.다양한 제품과 먹거리 액티비티가 있습니다가족,연인,친구들과 방문해도 좋습니다',
 '좋아요',
 '프랜차이즈 화장품가게로 가득할거같았는데아직 골목골목은 살아있네요비싸서흠이지만예전인사동으로 부활하길 바래봅니다',
 '인사동',
 '안국역이랑 가까워서 구경도하고 한옥마을이랑도 가깝고 교통이 편리합니다걸어서 구경할데가 많은것같아요주말에는 많이 혼잡하네요',
 '볼 것 없다.',
 '먹고 배부르면 쌈지길이나 한바퀴 돌며 소화시킨다.그리고 주변에 뭐 먹잘것도 없는데다가 있어도 비싸기만 할 뿐이다.그냥 중국인들 상대로 장사하세요.',
 '인사동',
 '예전에 비해 관광객이나 현지인이 믾이 줄어든 느낌이 있지만 여전히 정겹고 재미있는 인사동 주차가 협소하니 대중교통 추천합니다',
 '언제나 외국사람이 많은 제일 한국같은 곳',
 '외국사람들이 여행오면 꼭 들르는 곳이라죠?그만큼 유명한 곳도 많고 한데 좀 상업화 된 거리라 막상 한국인은 자주 안가게되더라구요. 하지만 이 길만을 목적이 아니 종로전체를 걸으면서  돌아다니기엔 재밌는 곳이예요. 쓰윽 한번 들러보세요!',
 '한번쯤 경험해봐도 좋을 곳',
 '한국적인 느낌을 얻고자하는 외국인들에게 한번 쯤은 와볼만한 곳이나, 요새 너무 상업적인 가게가 많아졌고, 전통적인 특색은 사라지는 추세. 다만 전통적인 음식과 식당이 많으니 식사하러 와도 좋을 거리 .',
 '한국의 대표적인 조계종 사찰입니다.',
 '한국의 조계종을 대표하는 사찰입니다.사찰의 규모는 작으나 상징성이 있습니다.사대천왕도 동판으로 제작되어서 톡특합니다.사찰내에 아주오래된 고목이 있어서 한층더신비감을 느끼게 합니다.도심에 위치하고있어서 접근성이 좋습니다.',
 '서울 한복판의 대형 사찰',
 "과거 유명했던 사이비 종교 보천교의 본당인 '십일전'을 인수해 개조한 절입니다. 덕분에 규모 하나만큼은 국내 최대 목조건물 중 하나. 다만, 사시사철 연등이 걸려있어 건물 전체의 웅장함을 느끼기에는 늘 부족하다는 생각이 들어요.",
 '마음이 복잡할때는 방문 추천',
 '종교가 없어도 가끔 마음이 복잡할때는 절이나 교회에 방문할 것을 추천한다. 조계사는 다양한 행사도 많이하고 차분하게 마음을 추스릴 수 있는 곳이다. 좋은 마음으로 소원을 기원하기에 좋다. 한시간 미만으로 방문하면 좋겠다.',
 '항상 가을에..',
 '이맘때 항상 방문합니다.국하축제하고 절자체도 너무이뿌고 접근성도 좋아서올해는 국화분재가있어 아버지가 흥미로워하셨어요매번하지만 위치도바뀌고 전시도 조금씩 바껴서 너무 좋아요 국화빵도팔고 좀 이색적이지만 좋았어요^^',
 '서울의 대표 불교 사찰',
 '조계사는 대한불교 조계종의 총본산으로 봉은사, 길상사와 함께 서울의 대표 불교 사찰입니다. 그 중요성과는 달리 절의 규모는 작은 편이지만 조계종 측에서 장기적으로 조계사 성역화 사업을 진행하고 있어 점차 절의 규모는 커질 것으로 예상됩니다. 대웅전 내의 아미타여래상, 석가여래상, 약사여래상 앞에 앉아 잠시 명상을 해보시길 권합니다. 대웅전 뒷편의 현대적인 건물 지하엔 불교박물관이 있으니 꼭 방문하시기 바랍니다.',
 '위치가 좋음',
 '종로갔다가 들르기 좋은 곳. 불상이 생각보다 크고 위엄있어서 놀랐다. 다만 그 외에 시설이 많지 않은 작은 절이다. 한번쯤 가볼만한 곳',
 '서울에서 방문하기 좋은 절 중 하나, 조계사',
 '규모가 매우 큰 절 중 하나입니다. 종로구 중심가에 위치한 절로 부처님 오신 날 혹은 외국인 손님이 왔을 때 방문하기 좋습니다.',
 '도심에 있는 절',
 '인사동 바로 옆에 있는 조계종 대표 절입니다.. 도심에 한적하게 불교문화를 느낄 수 있는 곳이라, 가면 마음이 편안해 지고 고즈넉해서 좋습니다.',
 '조계사',
 '종로 한가운데에 위치에서 접근성이 가장 좋은 곳이 아닌가 생각된다. 특히 부처님 오신날쯤에는 연등과 꽃이 예쁘게 꾸며져 있어 너무 좋다.',
 '반드시 들러야 하는 곳은 아니짐나 그래도 들르면 좋을 것 같습니다.',
 '반드시 들러야 하는 곳은 아니짐나 그래도 들르면 좋을 것 같습니다. 볼 거리 많은 종로에서 조계사에 들르면 참 좋을 것 같단 생각이 듭니다.',
 '청와대 관람투어',
 '6개월 전에 예약하고 주말에가족들과 함께 다녀왔습니다.경복궁은 여러번 갔는데 항상 멀리서 보던 청와대를 들어가보니 상징적인 곳이라경비가 삼엄하긴 하지만 고즈넉하고 좋았습니다.투어중에는 화장실이 없으니청와대관람차에서 내려 보안검색하기전 화장실을들러주는게 좋을 것 같습니다.기념품으로 성인에게는 머그컵아이들에게는 버스카드를 넣을수 있는 목걸이지갑을주었습니다. 산책하는 겸 저는 너무 만족했으나햇빛을 피할곳이 따로 없으니 모자나 생수 이온음료 정도는 챙겨 가세요!',
 '청와대',
 '내부관람을 위해서는 사전예약이 필요합니다.예약을 하지 않았을 경우 외부전경을 보면서 기념촬영하기 좋습니다.',
 '청와대',
 '대한민국 대통령의 집무실과 관저가 있죠!!청와대 앞길이 최근에 개방되서 좀 더 가까워진 느낌이에요!!!',
 '청와대는 예약제',
 '내부로는 예약하지 못해서 들어가지 못했지만 외곽을 따라 돌담길을 걷는건 너무 멋져요. 특히 가을에 낙엽이 질때 더 멋스러워욘',
 '청와대',
 '청와대 관람은 예약이 필요하나 경복궁 담을 따라 청와대 앞을 걸어봐도 좋습니다. 아름다운 길입니다.',
 '청와대공원 개방으로 청와대 앞 공원 둘러보기 추천~',
 '청와대 견학은 예약제로 운영하지만, 올해부터 청와대공원 인근 검문없이 자유롭게 산책할 수 있습니다.편안하게 청와대 공원 산책하고, 청와대 바라보며 삼청동까지 천천히 걸었습니다.',
 '가볼만한 가치가 있네여',
 '예약하고 가셔야 해요경비 엄청 삼엄하고 사진도 찍을수 있는 곳정해쟈 있는데 그럼에도 불구하고 유익함단 볕 피할데가 없어서 모자 필수친절하고 아이들 교육에도 좋아요',
 '서울의 중심',
 '물론 통치의 핵심장소이기도 하나 뒤에 병풍처럼 두른 산들과 앞 광화문 광장.양쪽 북촌과 서촌 사이에 청와대가 있다.위치적으로도 서울의 요지이자 중심에 청와대가 있다.차가 지나가야하는 루트라 검문을 하고 지나갔는데  의경들이 친절했고 비록 지나치기만 했지만  요새같은 시국에 만감이 교차했다.',
 '청와대 관람',
 "저는 청와대가 너무 궁금하여~ 미리 예약을 해서 입장 하였습니다. 물론 2~3개월전에 예약제로 운영이 되는곳입니다. '관람료는 없어요.. 무료입니다. 대신 개인일경우 10명이하로 , 단체일경우 11~200명이하로 신청이 가능합니다. 관람은 매주 화요일~금요일 토요일은 둘째, 넷내주에 가능합니다. 관람 시간은 오전 10시, 11시 오후 2시 3시로 하루에 4번을 운영중입니다.  총관람은 한시반이 걸립니다. 관람 코스는 만남의 장소-> 홍보관-> 녹지원 -> 구 본관터-> 소정원 -> 본관 -> 영빈관 -> 칠궁-> 무궁화동산 -> 청와대 사랑채입니다. 대중교통을 이용하시는 분들은 지하철 3호선 경복궁역 5번 출구를 이용하여 주셔야 합니다.",
 '한번은 가봐야 할 곳~',
 '대통령이 계신곳이라 경비가 삼엄하네요, 경복궁 뒤쪽에 있어 아이들 교육면에서도 고궁갈때 걸어가보면 좋아요 청와대 투어도 있다하니 내부도 가보고 싶네요']

In [12]:
res=requests.get('https://www.tripadvisor.co.kr')
res

In [21]:
driver=webdriver.Chrome()
url='https://www.tripadvisor.co.kr'
driver.get(url)

reviews=[]

for i in range(len(df)):
    driver.get(url)
    search=df.여행지[i]
    driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(search)
    driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(Keys.ENTER)
    driver.switch_to.window(driver.window_handles[-1])
    time.sleep(2)
    
    # 약간 문제인 부분
    try:
        driver.find_element_by_css_selector('#BODY_BLOCK_JQUERY_REFLOW > div.page > div > div.ui_container.main_wrap > div > div > div > div > div.content_column.ui_column.is-9-desktop.is-12-tablet.is-12-mobile > div > div.ui_columns.sections_wrapper > div > div.prw_rup.prw_search_search_results.ajax-content > div > div.main_content.ui_column.is-12 > div > div:nth-child(2) > div > div > div:nth-child(1) > div > div > div > div.ui_column.is-9-desktop.is-8-mobile.is-9-tablet.content-block-column').click()

        driver.switch_to.window(driver.window_handles[-1])
        soup=BeautifulSoup(driver.page_source,'html.parser')
        mydata=soup.find_all('span','NejBf')
        for item in mydata:
            reviews.append(item.get_text().strip())
        driver.switch_to.window(driver.window_handles[-1])
        driver.close()
        driver.switch_to.window(driver.window_handles[0])
        driver.back()
        time.sleep(1)
    except:
        driver.find_element_by_css_selector('#BODY_BLOCK_JQUERY_REFLOW > div.page > div > div.ui_container.main_wrap > div > div > div > div > div.content_column.ui_column.is-9-desktop.is-12-tablet.is-12-mobile > div > div.ui_columns.sections_wrapper > div > div.prw_rup.prw_search_search_results.ajax-content > div > div.main_content.ui_column.is-12 > div > div:nth-child(2) > div > div > div:nth-child(1) > div > div > div > div.ui_column.is-9-desktop.is-8-mobile.is-9-tablet.content-block-column > div').click()

        driver.switch_to.window(driver.window_handles[-1])
        soup=BeautifulSoup(driver.page_source,'html.parser')
        mydata=soup.find_all('span','NejBf')
        for item in mydata:
            reviews.append(item.get_text().strip())
        driver.switch_to.window(driver.window_handles[-1])
        driver.close()
        driver.switch_to.window(driver.window_handles[0])
        driver.back()
        time.sleep(1)

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#BODY_BLOCK_JQUERY_REFLOW > div.page > div > div.ui_container.main_wrap > div > div > div > div > div.content_column.ui_column.is-9-desktop.is-12-tablet.is-12-mobile > div > div.ui_columns.sections_wrapper > div > div.prw_rup.prw_search_search_results.ajax-content > div > div.main_content.ui_column.is-12 > div > div:nth-child(2) > div > div > div:nth-child(1) > div > div > div > div.ui_column.is-9-desktop.is-8-mobile.is-9-tablet.content-block-column > div"}
  (Session info: chrome=101.0.4951.54)

In [23]:
len(reviews)

1554

In [24]:
df[df['여행지']=='중남미문화원']

       여행지
90  중남미문화원

In [27]:
driver=webdriver.Chrome()
url='https://www.tripadvisor.co.kr'
driver.get(url)

for i in range(91,len(df)):
    driver.get(url)
    search=df.여행지[i]
    driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(search)
    driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(Keys.ENTER)
    driver.switch_to.window(driver.window_handles[-1])
    time.sleep(2)
    
    # 약간 문제인 부분
    try:
        driver.find_element_by_css_selector('#BODY_BLOCK_JQUERY_REFLOW > div.page > div > div.ui_container.main_wrap > div > div > div > div > div.content_column.ui_column.is-9-desktop.is-12-tablet.is-12-mobile > div > div.ui_columns.sections_wrapper > div > div.prw_rup.prw_search_search_results.ajax-content > div > div.main_content.ui_column.is-12 > div > div:nth-child(2) > div > div > div:nth-child(1) > div > div > div > div.ui_column.is-9-desktop.is-8-mobile.is-9-tablet.content-block-column').click()

        driver.switch_to.window(driver.window_handles[-1])
        soup=BeautifulSoup(driver.page_source,'html.parser')
        mydata=soup.find_all('span','NejBf')
        for item in mydata:
            reviews.append(item.get_text().strip())
        driver.switch_to.window(driver.window_handles[-1])
        driver.close()
        driver.switch_to.window(driver.window_handles[0])
        driver.back()
        time.sleep(1)
    except:
        driver.find_element_by_css_selector('#BODY_BLOCK_JQUERY_REFLOW > div.page > div > div.ui_container.main_wrap > div > div > div > div > div.content_column.ui_column.is-9-desktop.is-12-tablet.is-12-mobile > div > div.ui_columns.sections_wrapper > div > div.prw_rup.prw_search_search_results.ajax-content > div > div.main_content.ui_column.is-12 > div > div:nth-child(2) > div > div > div:nth-child(1) > div > div > div > div.ui_column.is-9-desktop.is-8-mobile.is-9-tablet.content-block-column > div').click()

        driver.switch_to.window(driver.window_handles[-1])
        soup=BeautifulSoup(driver.page_source,'html.parser')
        mydata=soup.find_all('span','NejBf')
        for item in mydata:
            reviews.append(item.get_text().strip())
        driver.switch_to.window(driver.window_handles[-1])
        driver.close()
        driver.switch_to.window(driver.window_handles[0])
        driver.back()
        time.sleep(1)

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#BODY_BLOCK_JQUERY_REFLOW > div.page > div > div.ui_container.main_wrap > div > div > div > div > div.content_column.ui_column.is-9-desktop.is-12-tablet.is-12-mobile > div > div.ui_columns.sections_wrapper > div > div.prw_rup.prw_search_search_results.ajax-content > div > div.main_content.ui_column.is-12 > div > div:nth-child(2) > div > div > div:nth-child(1) > div > div > div > div.ui_column.is-9-desktop.is-8-mobile.is-9-tablet.content-block-column > div"}
  (Session info: chrome=101.0.4951.54)

In [28]:
df[df['여행지']=='수종사']

    여행지
99  수종사

In [30]:
df[95:105]

             여행지
95       국립과천과학관
96    정약용 생가와 묘소
97         몽골문화촌
98     축령산 자연휴양림
99           수종사
100     남양주종합촬영소
101          동구릉
102  경기도립 물향기수목원
103   옥구도 도시자연공원
104          오이도

In [ ]:
https://www.tripadvisor.co.kr/Tourism-g294196-South_Korea-Vacations.html

In [38]:
options=webdriver.ChromeOptions()
options.add_argument('user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36')
options.add_experimental_option("excludeSwitches", ["enable-logging"])

basepath='C:/Users/이신행/OneDrive/바탕 화면/chromedriver_win32(1)/'
driver=webdriver.Chrome()
url='https://www.tripadvisor.co.kr/Tourism-g294196-South_Korea-Vacations.html'

reviews=[]
for i in range(len(df)):
    driver.get(url)
    search=df.여행지[i]
    driver.find_element_by_css_selector('#lithium-root > header > div > nav > div > div.fUFMI > div > div.weiIG.Z0.Wh.bZZEX > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(search)
    driver.find_element_by_css_selector('#lithium-root > header > div > nav > div > div.fUFMI > div > div.weiIG.Z0.Wh.bZZEX > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(Keys.ENTER)
    driver.switch_to.window(driver.window_handles[-1])
    time.sleep(2)
    
    # 약간 문제인 부분
    driver.find_element_by_css_selector('#BODY_BLOCK_JQUERY_REFLOW > div.page > div > div.ui_container.main_wrap > div > div > div > div > div.content_column.ui_column.is-9-desktop.is-12-tablet.is-12-mobile > div > div.ui_columns.sections_wrapper > div > div.prw_rup.prw_search_search_results.ajax-content > div > div.main_content.ui_column.is-12 > div > div:nth-child(2) > div > div > div:nth-child(1) > div > div > div > div.ui_column.is-9-desktop.is-8-mobile.is-9-tablet.content-block-column > div').click()
   
    driver.switch_to.window(driver.window_handles[-1])
    soup=BeautifulSoup(driver.page_source,'html.parser')
    mydata=soup.find_all('span','NejBf')
    for item in mydata:
        reviews.append(item.get_text().strip())
    driver.switch_to.window(driver.window_handles[-1])
    driver.close()
    driver.switch_to.window(driver.window_handles[0])
    driver.back()
    time.sleep(1)

KeyboardInterrupt:

In [39]:

options=webdriver.ChromeOptions()
options.add_argument('user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36')
options.add_experimental_option("excludeSwitches", ["enable-logging"])

basepath='C:/Users/이신행/OneDrive/바탕 화면/chromedriver_win32(1)/'
driver=webdriver.Chrome()
url='https://www.tripadvisor.co.kr/Tourism-g294196-South_Korea-Vacations.html'

reviews2=[]
for i in range(len(df)):
    driver.get(url)
    search=df.여행지[i]
    driver.find_element_by_css_selector('#lithium-root > header > div > nav > div > div.fUFMI > div > div.weiIG.Z0.Wh.bZZEX > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(search)
    driver.find_element_by_css_selector('#lithium-root > header > div > nav > div > div.fUFMI > div > div.weiIG.Z0.Wh.bZZEX > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(Keys.ENTER)
    driver.switch_to.window(driver.window_handles[-1])
    time.sleep(2)
    
    # 약간 문제인 부분
    driver.find_element_by_css_selector('#BODY_BLOCK_JQUERY_REFLOW > div.page > div > div.ui_container.main_wrap > div > div > div > div > div.content_column.ui_column.is-9-desktop.is-12-tablet.is-12-mobile > div > div.ui_columns.sections_wrapper > div > div.prw_rup.prw_search_search_results.ajax-content > div > div.main_content.ui_column.is-12 > div > div:nth-child(2) > div > div > div:nth-child(1) > div > div > div > div.ui_column.is-9-desktop.is-8-mobile.is-9-tablet.content-block-column > div').click()
   
    driver.switch_to.window(driver.window_handles[-1])
    soup=BeautifulSoup(driver.page_source,'html.parser')
    mydata=soup.find_all('span','NejBf')
    for item in mydata:
        reviews2.append(search + '-->' + item.get_text().strip())
    driver.switch_to.window(driver.window_handles[-1])
    driver.close()
    driver.switch_to.window(driver.window_handles[0])
    driver.back()
    time.sleep(1)

WebDriverException: Message: unknown error: cannot determine loading status
from unknown error: cannot determine loading status
from target frame detached
  (Session info: chrome=101.0.4951.54)

In [40]:
reviews2[-5:]

['국립서울현충원-->동작구 현충원은 단순히 잘 갖춰진 국립묘지일 뿐만 아니라 가족들이 주말에 산책하기 좋게 나무, 연못 등이 있다. 봄에는 벚꽃도 많이 펴서 보기 좋지만 사람들이 매우 많아 이 시기를 피해 가는 것이 좋다. 개인적으로는 가을에 가는 것을 좋아함',
 '국립서울현충원-->꽃필 때 방문하면 더 좋아요',
 '국립서울현충원-->호국영령들께서 잠들어계신 곳이라 가면 숙연해 집니다.벚꽃필 때 방문하면 아름답습니다. 능수벚나무가 많아요',
 '국립서울현충원-->방문할만한곳.',
 '국립서울현충원-->꽃놀이하러 벚꽃구경하러 사람들이 많이 찾는 곳하지만 이곳의 본연의 의미를 아는 것이 중요할 것 같다.서울 사는 분들이라면 가보세요']

In [75]:
# 진짜 크롤링 사용 코드
options=webdriver.ChromeOptions()
options.add_argument('user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36')
options.add_experimental_option("excludeSwitches", ["enable-logging"])

basepath='C:/Users/이신행/OneDrive/바탕 화면/chromedriver_win32(1)/'
driver=webdriver.Chrome()
url='https://www.tripadvisor.co.kr/Tourism-g294196-South_Korea-Vacations.html'

for i in range(475, len(df)):
    driver.get(url)
    search=df.여행지[i]
    driver.find_element_by_css_selector('#lithium-root > header > div > nav > div > div.fUFMI > div > div.weiIG.Z0.Wh.bZZEX > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(search)
    driver.find_element_by_css_selector('#lithium-root > header > div > nav > div > div.fUFMI > div > div.weiIG.Z0.Wh.bZZEX > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(Keys.ENTER)
    driver.switch_to.window(driver.window_handles[-1])
    time.sleep(2)
    try: 
        # 약간 문제인 부분
        driver.find_element_by_css_selector('#BODY_BLOCK_JQUERY_REFLOW > div.page > div > div.ui_container.main_wrap > div > div > div > div > div.content_column.ui_column.is-9-desktop.is-12-tablet.is-12-mobile > div > div.ui_columns.sections_wrapper > div > div.prw_rup.prw_search_search_results.ajax-content > div > div.main_content.ui_column.is-12 > div > div:nth-child(2) > div > div > div:nth-child(1) > div > div > div > div.ui_column.is-9-desktop.is-8-mobile.is-9-tablet.content-block-column > div').click()

        driver.switch_to.window(driver.window_handles[-1])
        soup=BeautifulSoup(driver.page_source,'html.parser')
        mydata=soup.find_all('span','NejBf')
        for item in mydata:
            reviews2.append(search + '-->' + item.get_text().strip())
        driver.switch_to.window(driver.window_handles[-1])
        driver.close()
        driver.switch_to.window(driver.window_handles[0])
        driver.back()
        time.sleep(1)
    except:
        pass

In [77]:
reviews2[-5:]

['제주 감귤박물관-->감귤의 제배 과정 효능 방법등에 대해 나와 있고 종류또한  다양합니다. 아이들과 방문한다면 좋은 공부가 될수도 있습니다.',
 '제주 감귤박물관-->감귤박물관',
 '제주 감귤박물관-->생각보다 아주 크게 있음. 감귤을 수확하는 모든 과정을 볼 수 있으며 체험도 할 수 있어 재밌음.',
 '제주 감귤박물관-->신나는 감귤 축제',
 '제주 감귤박물관-->감귤 축제 기간에 방문하니 감귤 수확 체험이 평소 6000원이던 것이 3000원으로 할인해주고 직원들이 수확하는 방법도 자세히 알려주시고 목장갑, 가위도 다 빌려주시기 때문에 아이들과 체험하기 좋았다.박물관도 생각보다 크고, 오래되긴 했지만 깨끗하게 관리되고 있으며, 그린하우스 내에 세계 여러나라의 작고 큰 귤나무가 다양하게 있어 좋았다.밑에 리뷰에 있는 것처럼 애월이 아니라(애월은 제주시에 있음) 서귀포 효돈에 위치하고 있다. 주차장도 꽤 큰 편이다. 감귤 과즐이 맛있어서 한 번 사먹어 보기를 권한다.']

In [76]:
df[df['여행지']=='학동 몽돌해수욕장']

           여행지
830  학동 몽돌해수욕장

In [78]:
len(reviews2)

12358

In [79]:
titles=[]
contents=[]
for i in range(0,len(reviews2),2):
    titles.append(reviews2[i])
for j in range(1,len(reviews2),2):
    contents.append(reviews2[j])

In [80]:
titles

['경복궁-->대한민국의 역사',
 '경복궁-->국민이 공감하는 장소',
 '경복궁-->산책하기 좋은 경복궁',
 '경복궁-->Good',
 '경복궁-->가족단위로 방문하기 좋은곳',
 '경복궁-->하늘이 내린 큰 복',
 '경복궁-->굿',
 '경복궁-->조선의 집',
 '경복궁-->대표 문화재',
 '경복궁-->경복궁',
 '삼청동 거리-->기대 이상 만족',
 '삼청동 거리-->삼청동길',
 '삼청동 거리-->전통과 현대의 건축양식의 조합이 주는 이색적인 도시 풍경',
 '삼청동 거리-->옛 명성은 어디로...',
 '삼청동 거리-->옛날에 비해 많이 변한..',
 '삼청동 거리-->퇴근 후 데이트코스로 좋은 길',
 '삼청동 거리-->봄 가을 방문 강추',
 '삼청동 거리-->삼청동길',
 '삼청동 거리-->한국적인 분위기가 아름다운곳',
 '삼청동 거리-->데이트 장소로 추천',
 '인사동-->어제다녀온 인사동',
 '인사동-->전통과 현대미 조화를 이루는 곳',
 '인사동-->인사동은 보물',
 '인사동-->코로나로 한산한 거리입니다',
 '인사동-->좋아요',
 '인사동-->인사동',
 '인사동-->볼 것 없다.',
 '인사동-->인사동',
 '인사동-->언제나 외국사람이 많은 제일 한국같은 곳',
 '인사동-->한번쯤 경험해봐도 좋을 곳',
 '조계사-->한국의 대표적인 조계종 사찰입니다.',
 '조계사-->서울 한복판의 대형 사찰',
 '조계사-->마음이 복잡할때는 방문 추천',
 '조계사-->항상 가을에..',
 '조계사-->서울의 대표 불교 사찰',
 '조계사-->위치가 좋음',
 '조계사-->서울에서 방문하기 좋은 절 중 하나, 조계사',
 '조계사-->도심에 있는 절',
 '조계사-->조계사',
 '조계사-->반드시 들러야 하는 곳은 아니짐나 그래도 들르면 좋을 것 같습니다.',
 '청와대-->청와대 관람투어',
 '청와대-->청와대',
 '청와대-->청와대',
 '청와대-->청와대는 예약제',
 '청와대-->청와대',
 '청와대-->청와대공원 개방으로 청와대 앞 공원 둘러보기 추천~',
 '청와대-->가볼만한 가치가 있네여',
 '청와대-->서울의 중심',
 '청와대-->청와대 관람',
 '청와대-->한번은 가봐야 할 곳~',
 '보신각-->보신각 지나가면서~~~',
 '보신각-->새해를 맞이하여 울리는 종소리',
 '보신각-->좋은곳',
 '보신각-->보신각 타종의 주인공',
 '보신각-->방문기',
 '보신각-->정오의 이벤트',
 '보신각-->좋아요',
 '보신각-->보신각',
 '보신각-->벨 파빌리온',
 '보신각-->종로 1가 역사 유적지',
 '이화장-->희망의 등불 역할을 톡톡히 하고 있는 2020 희망의 빛초롱 축제',
 '이화장-->명동 쇼핑거리 ~~',
 '이화장-->대한민국 최고의 쇼핑 거리',
 '이화장-->Eggdrop sandwich in myeongdong!!',
 '이화장-->2000년 중반부터 점차 한국인이 잘 안보이게된..',
 '이화장-->중국인만 손님',
 '이화장-->명동',
 '이화장-->외국인 여행객들에게 마지막날 코스로 추천',
 '이화장-->관광객 천국',
 '이화장-->명동 새로생긴 아몬드전문점이 인상적',
 '국립민속박물관-->국내인들도 한번 가볼만 하다.',
 '국립민속박물관-->부모님과 방문하면 좋아요',
 '국립민속박물관-->아이들과 꼭 가봐야하는 곳',
 '국립민속박물관-->경복궁이 덥다면 여기는 시원하다',
 '국립민속박물관-->국립 민속 박물관',
 '국립민속박물관-->국립 민속 박물관',
 '국립민속박물관-->베리 굿',
 '국립민속박물관-->무료로 구경하기 좋은거 같아요.',
 '국립민속박물관-->기념품점 추천',
 '국립민속박물관-->딱히 볼 건 없었어요',
 '사직단-->조용한 쉼터',
 '사직단-->가족들과 오기 좋은곳!',
 '사직단-->도심속에 숲',
 '사직단-->도심속에 평안함',
 '사직단-->궁권들과는 다른 독특한 분위기를 느낄 수 있는 곳',
 '사직단-->오랜 역사를 지닌 평화로운 공원',
 '사직단-->긴장을 풀거나 약간의 역사 수업을받는 공원',
 '사직단-->잠긴 제단',
 '경교장-->김구선생님이 돌아가신 역사의 현장',
 '경교장-->강북삼성병원 가는 길에',
 '경교장-->역사의 아픔이 있는장소',
 '경교장-->방문기',
 '경교장-->독립 후 상해의 임시정부가 자리잡은 곳',
 '탑골공원-->독립운동의 성지와 같은 곳!',
 '탑골공원-->한번은 가볼만함.',
 '탑골공원-->1919년 3·1운동의 발상지로 더욱 유서깊은 탑골공원',
 '탑골공원-->항상 지나가긴 하면서 제대로 못본곳',
 '탑골공원-->탑골공원',
 '탑골공원-->원각사지10층석탑!',
 '탑골공원-->탑골공원',
 '탑골공원-->원각사지 10층 석탑이  숨어있는 보물장소',
 '탑골공원-->종로를 가다가 한번쯤',
 '탑골공원-->종로에서 종묘로 향하는 도중에 있습니다.',
 '대학로-->있는 대학의 품위',
 '대학로-->새로 바뀐 푸드코트',
 '대학로-->조용히 산책하며 구경하기 좋은 곳',
 '대학로-->이화여자대학교',
 '대학로-->중국인 관광객 구경하기 좋은 곳',
 '대학로-->궁금해서 가봤어요',
 '대학로-->대한민국 명문대 클라스',
 '대학로-->세계 최고의 여성대학',
 '대학로-->조경이 아름다운 학교',
 '대학로-->관광객이 많이 구경가는 대학교',
 '인왕산 선바위와 국사당-->Viewpoints of Seoul',
 '인왕산 선바위와 국사당-->초보 하이커에게도 적당해요',
 '인왕산 선바위와 국사당-->방문기',
 '인왕산 선바위와 국사당-->서울의 경치',
 '인왕산 선바위와 국사당-->인왕산',
 '인왕산 선바위와 국사당-->서울을 한눈에',
 '인왕산 선바위와 국사당-->혼자 걷기 좋은 한양도성',
 '인왕산 선바위와 국사당-->서울 한복판에 이런 자연이!',
 '인왕산 선바위와 국사당-->서울 중심의 멋진산',
 '인왕산 선바위와 국사당-->너무 좋음',
 '종묘-->서울 한복판의 조선시대',
 '종묘-->눈 덮인 종묘에 가시길!',
 '종묘-->종묘대제관람',
 '종묘-->추천하고 싶은 명소',
 '종묘-->매년 가을마다 갑니다',
 '종묘-->훌륭한 곳이지만 여름은 피할 것',
 '종묘-->석양에 아름다운 조선의 국혼',
 '종묘-->한국의 영혼, 종묘',
 '종묘-->아름다운 종묘',
 '종묘-->꼭 가보셔야',
 '서울역사박물관-->추후 공지가 있을 때까지 일시 휴업',
 '서울역사박물관-->아이들도 오면 좋지만 어른들이 와도 충분히 역사공부하여 즐길 수 있는 곳. 청각장애인도 함께 즐길 수 있는 영화제도 종종 개최한다.',
 '서울역사박물관-->기대만큼은 아니지만  들러보아야할곳중 하나. 아직도 많은 자료전시가 필요한것으로 보입니다. 무료관람지-유료였다면 생각하봐야할듯.',
 '서울역사박물관-->서울에서 평생 살아도 사실 한번도 못가볼 가능성이 많은 박물관입니다. 그러나 한번 쯤 내가 사는 이 곳은 어떻게 만들어졌는가를 아는 것도 인생에서 중요하다 싶네요.',
 '서울역사박물관-->어서와 한국은 처음이지  핀란드 편에 나온 거를 보고 보러 갔어요. 일제강점기 견학부분이 TV에 나왔는데 제가 생각했던것보다는 부실했어요. 오히려 식민지 상황에서 모더니티를 더 조명했다는 느낌이 들었네요. 여기 식당도 있는데 비빔밥(4500원)이 맛있었어요.',
 '서울역사박물관-->말 그대로 서울의 역사를 소개하는 박물관으로서 옆에 있는 대한민국 역사 박물관 과는 엄연히 다른 박물관이다. 옛 조선이 개국하고 부터 현재 서울의 발전 과정 및 역사를 전시하고 있으며 내가 몰랐던 한양의 유래와 옛 도성 거리(지금의 세종로)를 설명해 놓았으며 모형으로 꾸며 놓기도 하였다. 뿐만 아니라 QR 코드를 통해 자세한 음성 해설을 들으수가 있으며 한국어,영어,중국어,일어 4개 국어로 지원된다. 내 생각으로는 국립 중앙 박물관 만큼 중요하다고 여겨지는 곳이다. 왜냐면 우리는 현재 서울의 모습만 잘 알고 있지 옛 조선시대의 한양의 도성 거리 모습을 잘 알지 못하기 때문이다, 또한 장터, 농부, 주민들의 생활이나 관리들이 일하는 기관등 여러 부분에 대해 소개 하고있다. 정말 잘 전시해 놓았으며, 현재 특별 전시로 한강의 유래와 발전에 대해 전시하고 있으며 내년 1월 까지 전시하니 꼭 가보길 바란다. 바란건대 이곳이 널리 알려져서 전쟁 기념관 이나 국립 중앙 박물관 처럼 많은 이들이 발걸음 하는 곳이 되길 바란다.',
 '서울역사박물관-->어디든 가기 좋은 광화문 근처 위치다양한 전시로 볼거리 가득근처 경희궁도 좋음근처에 있다면 잠깐쉬어 가도 좋을듯서울의 다양한 모습 볼수있음',
 '서울역사박물관-->별로 기대하지 않고 방문했는데, 미니어처로 만들어진 서울시 그리고 서울시에 많은 기억들을 담고 있는거 같아서 가성비가 좋았던 곳으로 기억합니다.',
 '서울역사박물관-->우연한 기회에 역사 박물관을 가게 되었는데, 생각보다 알찬 전시물에 놀랐습니다.직접 버튼을 눌러서 작동 시켜볼 수 있는 것들도 많고 영상물도 많아서 지루하지 않게 한양부터 시작된 서울의 역사를 공부할 수 있었네요.아이들이 있으신 분들은 꼭 한 번 가보시길 추천합니다.',
 '서울역사박물관-->광화문에 위치해서 접근성도 좋고 서울의 역사를  다양한 전시물을 통해 알기쉽게 이해할수있어서 좋았어요. 직접 체험할수 있는 공간도 있고 초등학생들이 꼭 가볼만한 공간이예요.',
 '서울역사박물관-->재미있게 만들어진 박물관이에요. 서울의 역사가 궁금한 분들은 한 번 돌아보면 큰 도움이 됩니다.박물관사이트에서 전시 해설을 신청해도 괜찮아요.',
 '창경궁-->짱',
 '창경궁-->코로나 이후 첫 야경투어 창경궁',
 '창경궁-->왕실 가족의 생활 공간으로 풍부한 왕실 가족사가 전해오는 창경궁 이야기',
 '창경궁-->도심 힐링하는곳',
 '창경궁-->도심 속의 조용한 산책 장소!',
 '창경궁-->산책하기좋은곳',
 '창경궁-->All',
 '창경궁-->가을 단풍을 도심에서',
 '창경궁-->작년보단 안이뿌지만',
 '창경궁-->조용하게 조선의 향기를 느낄 수 있는 곳.',
 '창덕궁-->꼭추천하는곳',
 '창덕궁-->작은 문들이 인상적인 궁',
 '창덕궁-->한국',
 '창덕궁-->역사가 살아있는 곳',
 '창덕궁-->아름다운 궁',
 '창덕궁-->추억의 장소...',
 '창덕궁-->한국에서 가장 아름다운 궁궐',
 '창덕궁-->데이트 장소로도 좋아요',
 '창덕궁-->역사체험',
 '창덕궁-->멋진 최고의 조선 궁',
 '북촌한옥마을-->여유로운 마음으로 거닐기좋아요. ^^',
 '북촌한옥마을-->아름다운 한옥을 볼수있는 장소',
 '북촌한옥마을-->북촌 한옥마울',
 '북촌한옥마을-->겨울이지만 사진 잘 받는 곳',
 '북촌한옥마을-->데이트 장소로 좋음',
 '북촌한옥마을-->북촌한옥마을',
 '북촌한옥마을-->한옥들이 몰려있는 한옥마을',
 '북촌한옥마을-->북촌 한옥마을',
 '북촌한옥마을-->여긴 꼭 가야할 곳',
 '북촌한옥마을-->많은 분들이 좋다고 했지만 너무 조용해서 조금 아쉬움.',
 '동대문시장-->쇼핑의 천국',
 '동대문시장-->가장 즐겨가는 쇼핑몰~',
 '동대문시장-->한국에 오면 꼭 방문할 곳',
 '동대문시장-->한국 패션을 이끌어가는 쇼핑의 메카',
 '동대문시장-->이제는 한국인에게도 바가지 씌우는',
 '동대문시장-->패션타운',
 '동대문시장-->쓰잘데기없이 과소비하게된다 ㅋㅋㅋㅋ',
 '동대문시장-->물건을 구입하기 위해 들렸어요!!',
 '동대문시장-->업무상으로 관광으로 다 좋아요',
 '동대문시장-->심심할때 가는 시장',
 '운현궁-->친구데리고 가기',
 '운현궁-->흥선대원군의 집',
 '운현궁-->지금은 공사중',
 '운현궁-->경복궁이나 창덕궁 같은 고아한 궁은 아니지만',
 '운현궁-->안국역에서 가까운 운현궁, 주말에는 다도체험이 가능',
 '운현궁-->운현궁!! 강추해요',
 '운현궁-->공연도 있어요~~',
 '운현궁-->무료입장하는 운현궁의 봄',
 '운현궁-->산책하기 좋은 곳.',
 '운현궁-->복접한 도심의 휴식처이자 역사공간',
 '낙산공원-->언제가도 좋은 곳',
 '낙산공원-->공연보고',
 '낙산공원-->천천히 가는 서울',
 '낙산공원-->낙산공원',
 '낙산공원-->가볍게 서울 야경을 즐길 수 있는 언덕길',
 '낙산공원-->낙산공원',
 '낙산공원-->야경이 멋진 공원',
 '낙산공원-->낙산공원',
 '낙산공원-->추천합니다',
 '낙산공원-->서울야경 명소 BEST 3 중 하나',
 '명동성당-->이토록 아름다운 공간이 우리 곁에!',
 '명동성당-->명동이 유명해지고..',
 '명동성당-->대한민국 천주교의 1번지',
 '명동성당-->이 장소 자체가 좋다기 보다는...',
 '명동성당-->아직도 구유가 있어요',
 '명동성당-->wedding',
 '명동성당-->우리나라의 TOP 1 성당',
 '명동성당-->아름다운 성당, 성지',
 '명동성당-->크리스마스 이브에 갔던곳',
 '명동성당-->성당 상품들 구경하러',
 '청계천-->청계천 최고',
 '청계천-->홀로 혹은 같이 산책하기 좋은 곳',
 '청계천-->산책하기 좋아요~',
 '청계천-->서울에서 힐링하는곳',
 '청계천-->도심의 대표적인 하천입니다.',
 '청계천-->생각없이 걷기좋은곳',
 '청계천-->서울의 중심부로 흐르는 천',
 '청계천-->이명박이가 이건 잘했지.',
 '청계천-->청계천',
 '청계천-->도심속의   쉼표',
 '덕수궁-->추후 공지가 있을 때까지 일시 휴업',
 '덕수궁-->궁에 가면 의미나 역사는 잊은채 사진 찍기에만 바빴습니다.도보해설이라는 좋은 프로그램이 있다는 정보를 알고 신청해 보았더니 매우 만족합니다.정성스럽게 질문에 답도 해주시고 2시간동안 전혀 지루함없이 해설해주신 김경숙B 해설사님 너무 감사드립니다. 역사를 잊은 민족에게 미래는 없습니다.이름으로만 혹은 왕이 계셨던 곳이라는 막연한 설명에서 장소의 의미를 찾고 역사를 공부해 가도록 길을 열어주셔서 너무 고맙습니다.아무쪼록 이 프로그램들이 쭉 지속되어 역사를 많은 사람들이 알아가는 계기가 되길 바랍니다.',
 '덕수궁-->도듬이라는 도깨비투어를통해  해설자분이  각각의  건물에대해 설명을 들으며 걷다보니  운치도있고 모르던것들도 알수있었습니다따로 방문하여 듣는것도좋지만 자세히 설명해주는분이 계시니 너무좋았어요특히 야경이 너무좋네요',
 '덕수궁-->덕수궁은 조선시대의 궁과 일본식 근대 건물이 함께 존재하는 공간이다. 역사적인 지식을 갖고 방문을 하면 더욱 느끼는 것이 많은 장소이다. 화려하면서도 밤에는 조명으로 매우 아름답기도 하다.',
 '덕수궁-->조용히 둘러보는 고궁. 덕수궁 입구에서 가끔 볼만한 공연도 진행하시더라구요.경복궁보다는 덜 붐비는 편입니다. 조용히 둘러보기 좋았어요',
 "덕수궁-->숭례문에서 경복궁까지 이어지는 구간에서, 한 번은 들러보면 좋은 장소가 덕수궁입니다. 덕수궁은 아기자기한 공원 같은 느낌이 강하고, 이벤트가 많이 벌어지는 곳입니다. 그러나 알고 보면 대한제국의 슬픈 역사가 남겨진 곳이기도 합니다.지금은 '기억된 미래'라고 하는 덕수궁 야외 프로젝트가 진행중이고, '대한제국 황제의 식탁' 특별전이 열리고 있습니다. 성인 기준 500원에 모든걸 즐길 수 있죠. 다만 행사는 그때그때 바뀌니까, 이벤트 일정은 미리 체크하고 가는 것이 좋습니다.덕수궁앞이 시위로 인해서 매우 시끄럽고, 분위기가 살벌하지만... 관광객들에게 시비를 걸지는 않습니다. 시끄러운 정문을 지나면, 색다른 매력의 궁궐을 만나보실 수 있습니다.",
 '덕수궁-->지하철역과 아주 가깝고 관람도 한 시간 이내에 둘러보기 좋은 곳이에요. 외국인보다는 주로 한국인 관광객들이 있습니다.조용하게 산책하듯이 둘러보기 좋습니다.덕수궁 석조전은 인터넷으로 미리 신청을 해야 입장할 수 있어요.',
 '덕수궁-->외국인 친구들이 방문한다면 데리고 갈 곳! 서울의 중심부에 있어 이곳저곳 구경하기도 좋고, 내부의 모습도 흥미롭다. 특히 미술관도 있어서 구경할 거리가 많다.',
 '덕수궁-->역 바로 앞에 있어서 찾아가기 가장 좋은 궁이라고 생각해요~ 미술관도 있어서 관람하다가 더우면 에어컨도 쐴 수 있고~ 서울시내 궁 중에 가자 ㅇ좋아하는 궁이에요',
 '덕수궁-->경복궁보다 개인적으로 더 선호하는 곳이다. 상대적으로 사람이 적고 조용하게 걸으면서 산책도 할 수 있어서 더 좋았던 것 같다.',
 '덕수궁-->아직 날씨가 쌀쌀해서 좀 아쉬웠으나 산책하며 좋았습니다. 나중에 꽃 피면 다시 갈겁니다. 입장료도 저렴하고 인근 직장인들은 종합권 구매해서 이용 가능하다라고요. 좋은 것 같습니다.',
 '남대문시장-->여러가지 볼거리가 많고 명동역과 서울역이 가까워서 이거저거 많이 할수가 있고 시장 구경하는 재미가 크고 대중교통 이용이 편리함',
 '남대문시장-->정말 없는게 없는 남대문 시장이지만먹는 것부터 남다른 남대문 시장이예요천원 호떡부터 삼천원 칼국수 등등 음식값도 저렴한데 맛까지 있어서 좋았어요',
 '남대문시장-->일요일은 쉬는날이지만 먹거리시장도 열고 문연가게들도 있어 충분히 즐길수 있었어요호떡도 사먹고 갈치조림먹고 쇼핑하고 잘놀다왔어요~~~~',
 '남대문시장-->호떡 장인이 있는 곳입니다천원짜리 호떡으로 유명한 장인님이 계시며 전국 어디를 가도 그돈주고 못먹습니다^^남대문 호떡이라고 검색해보세요ㅎㅎ',
 '남대문시장-->가족이 같이 놀러갔어요 길거리에 맛있는것도 많고 가성비좋은 물건도 많습니다 관광객도 많아요길이 복잡해서 이가게 저가게 다니면서 가격 비교하며 사긴 어렵습니다다시 찾아가기 어렵거든요맘에 들면 가격흥정해서 사세요',
 '남대문시장-->남대문시장도 볼게많지만, 시장 다 구경하고힐튼호텔방향쪽으로 걸어 올라가면서 사진찍기 좋은곳 많이있어요. 남산공원도 갈수있어요.',
 '남대문시장-->하루 종일 볼거리, 먹거리 가 가득한 곳입니다.특히 남대문에서 도보로 방문해 한국의 맛, 서울의 묘미을 느낄 수 있는 곳이 정말 맍지요.낯이면 낯..밤이면 밤.. 하루 종일 다양하 경험을 해 볼 수 있습니다.교통과 위치도 정말 추천할 만한데...1호선과 4호선 지하철이 환승하는 곳 가깝고.. 2호선과 3호선도 도보로 이용이 가능한 위치여서 누구나 편안히 즐거움을 경험 할 수 있습니다.음식도 저렴하고 다양한 음식과 세계여러 곳의 맛도 한자리에서 경험할 수 있어서 맛집여행에도 좋을 듯 합니다.',
 '남대문시장-->역사와 전통이 있는 시장으로써 여러가지 물건을 판다 ex) 의류, 수입물품, 의약품(약국), 안경, 식자재, 주방기기(접시) 등규모가 큰 편이며 굳이 물건을 구입하지 않고 구경만 해도 즐거운 경험이 될 수 있는 시장이다.',
 '남대문시장-->가시면 유명한 가맛골 만두부터 칼국수, 갈치골목, 야채호떡 등 맛난게 참으로 많아요~그리고 한국전통 선물도 인사동보다 저렴하게 사실 수 있고, 꽃이며 옷이며 이불이며 없는게 없습니다 ㅋㅋㅋ남대문 제대로 구경하려면 최소 반나절은 있어야함 ㅋㅋ',
 '남대문시장-->시장 투어를 하신다면 저는 남대문응 추천 할께요. 먹거리도 많고 이것저것 구경하는 재미가 있어요. 수입산가 구경하는 재미도 아주 솔솔합니다.',
 '서울광장-->서울 시청역 1호선,2호선에서 나오면 바로 위치하고 있는 광장여름에는 잔디, 겨울에는 때에따라 아이스링크장으로 변신하여 운영됩니다.도심속에 있는 잔디 뭔가 좋았어요.',
 '서울광장-->서울시청 앞에 있는 큰 광장이다. 평소에는 푸른 잔디가 펼쳐저 있지만, 시위나 행사, 집회의 용도로 활용되기도 한다. 겨울에는 아이스링크가 만들어진다. 큰 축구경기가 있으면 여기서 대규모 응원전을 볼 수 있다.',
 '서울광장-->겨울이다보니 푸릇푸릇한 잔디는 없고간이 아이스링크가 설치되어 있었습니다.사람들이 즐겁게 스케이트를 타고 있는데 재밌어 보이더라구요.아이와 함께 와서 스케이트 타면 좋을것 같은 곳이었습니다..(미세먼지만 없다면...ㅠㅠ)',
 '서울광장-->주말이나 꼭 특별한 날이 아니라도 최근에는 점심시간 혹은 퇴근 후 광장에서 공연도 많이 진행하고 다양한 이벤트들이 열려서 잠시 쉬어가며 즐기기에 좋다.',
 '서울광장-->시청 앞에 있는 잔디광장이죠~~ 여러 이벤트를 하는 곳이죠!! 지나가면서 구경하기 좋아요!!!',
 '서울광장-->겨울에는 스케이트장을 운영해 놀기 좋다. 빌딩숲 사이에 광장이 있어 뻥뚫린 느낌이 들었다.',
 '서울광장-->서울광장이 크고 좋지만 집회하는 사람들과 노숙하는 사람들이 많아서 눈살을 찌푸리게 됩니다. 필수로 가볼만한 곳은 아니지만 겨울에 스케이트 타러 가볼만 합니다',
 '서울광장-->주말에 바람 쐬러 가기 좋은 곳이다앞에 파란 잔디도 좋고 뛰어 놀아도 좋고눈이 맑아지는 것 같은 곳이다다양한 행사도 해서 심심하지 않다',
 '서울광장-->항상 뉴스로만 보던 서울광장~집회가 있는 날이아니라 그런지 시민들이 자리하고잇는 모습이 보기 좋았습니다. 뉴스에서 보던 모습때문에 광장하면 부정적인 이미지였는데 막상 가서 보니까  문화축제를 하는곳~  매일매일 공연을 하는곳이었습니다. 최근까지 클래식 공연이 있었고 9월에는 감성충전 페스티말이라는 행사가 진행중이었습니다. 공연을 보려했던건 아니지만 무대장치며 이미 돗자리 펴고 준비중이신 분들을 보니~ 제가 생각했던 이미지와는 많이 다른곳이었습니다.',
 '서울광장-->서울 광장은 서울시청 앞에 있는 시민을 위한 광장으로 서울의 랜드마크이지요. 도심 한가운데에서 넓은 잔디마당이 있어 때로는 지는 해를 보며 힐링하기도 합니다. 다만 그늘은 없습니다.',
 '한국은행 화폐금융박물관-->대한민국 화폐의 역사를 한 눈에 볼 수 있는 테마 박물관입니다. 전시 뿐만 아니라 1만원 권으로 1억 원이 얼마나 무거운지 체험해볼 수 있는 전시관도 있습니다.',
 '한국은행 화폐금융박물관-->규모가 박물관만큼 크지는 않지만 화폐를 세세히 보면서 설명도 읽고 다돌아보려니 시간이 꽤 많이 걸렸어요. 세계 각국의 화폐들이 전시되어 있고 체험하는 코너들도 있었어요.체험 코너에서 500원을 넣고 화폐에 자기 얼굴 찍어서 나오는 기계가 있는데 기념으로 하기 좋은 거 같아요~',
 '한국은행 화폐금융박물관-->오랜만에 박물관 왔습니다주차는  호텔에  파킹하고  대중교통 이용했습니다도심이라 자차보다는 대중교통이 편리할때가 많습니다입장은 남녀노소 무료이며음식물 반입은  안되네요우리나라 화폐및 동전드을시대별로 볼수있으며동선도 그리  넓지 않아짧은 시간 아이들과 재미나게 관람할수있는곳중 하나입니다불편한건 실내에  앉아있을수있는 공간이거의 없다고 보시면 되네요아예 없는건 아닙니다',
 '한국은행 화폐금융박물관-->과거의 한국은행 전시장은 평일에 어려운 절차를 거쳐야 참관할 수 있었지만, 2000년대에 들어오며 과거 조선은행으로 개관한 본점 건물을 전체적으로 박물관으로 하고 사무를 옆 건물들로 이전함과 동시에 상시 개방적인 형태로 운영하게 되었다. 건물 자체도 당대 일본 근대건축의 대가였던 다쓰노 긴고(辰野金吾)의 작품으로 이미 역사적인 곳이며, 내부 홀 전체를 전시장으로 사용하고 있어 넓은 공간에서 세계의 다양한 화폐들을 볼 수 있다. 전시는 2층까지 이어지며, 한편 수시로 테마전을 개최하고 있으므로 이에 맞추어 방문할 가치가 있을 것이다. 단 건축물은 1980년대 후반 원형복원공사 때 외부는 과거와 동일하게 맞추었지만 내부는 현대적인 형태로 재구성한 점이 있다는 것을 염두에 두면 좋을 것이다.',
 '한국은행 화폐금융박물관-->한국은행 본점 건물에 위치한 화페금융박물관. 초등학생 자녀가 있는 분들이라면 나들이 삼아 다녀오기에 좋은 곳이다.',
 '한국은행 화폐금융박물관-->화폐박물관이 있는 무료입장이 매력적인 곳.맞은 편의 신세계와 그 옆의 구제일은행 건물 등등근대건축양식의 세 건물을 셋트로 구경하기에 아주적합한 위치임화폐박물관이라는 전시물의 호감도는 그다지 만족스러운수준은 아님 단지, 조선은행 건물 내부를 볼 수 있다는 것으로상당히 추천할 수 있음',
 '한국은행 화폐금융박물관-->화폐 역사를 한 눈에 볼 수 있습니다. 애들과 함께 하면 좋네요.. 관람료도 무료라 부담없어요.',
 '한국은행 화폐금융박물관-->한국은행에 있다는 것으로도의미있어요 한국은행 방문했을때나 근처에 쇼핑할때 들려보세요 한국은행에 갈수있는 방법',
 '한국은행 화폐금융박물관-->전세계의 화폐를 다양하게 볼 수 있어요.또한 식물이나 동물, 인물 등 다양한 분류로 화폐를 나눠놓았구요.상평통보 만드는 법 등을 체험해 볼 수 있답니다.어린이 패키지 구입하면 한국 지폐에 사진을 인쇄할 수 있어요.',
 '한국은행 화폐금융박물관-->을지로입구역에서 도보로 몇분거리에 화폐금융박물관이 있습니다.중후한 건물로 예전 한국은행 건물이었는데, 역사적으로 중요한 건물인 것을 알게 됐습니다.한국의 옛날 지폐나 북한의 지폐 등도 전시되어 있어서, 많이 알려지지 않은 좋은 관광지라고 생각합니다.',
 '숭례문-->숭례문 을 지나다닐 수 있게 오픈 해 놓은 줄 몰랐다숭례문 입구 천장에 용구림을처음 보았다 웅장하고 한복의 문양처럼  그렇게나 고울 수 가 없다 최고',
 '숭례문-->남대문으로도 불리우는 국보 1호 숭례문 입니다.남대문 시장이나 상공회의소 건물 버스 정류장에서 내려서 걸어갈 수 있습니다.바로 앞 까지 안 걸어 가더라도 웅장한 건물을 느낄 수 있습니다.서울 시내 명소 중 하나라 꼭 한 번 가볼만 합니다!',
 '숭례문-->1392년 이성계가 조선왕조를 세우고 한양으로 천도하면서 1395년부터 성곽을 축조하게 되었다. 남쪽의 정문인 숭례문도 동시에 시공되어 1398년 준공되었으며, 1907년 성곽이 해체된 후로도 남아 서울의 대표적인 역사적인 상징물로 남았다. 물론 전쟁으로 인한 파손의 역사는 있었지만 특히 2008년의 방화로 인한 전소는 큰 충격이 되어 현재의 것은 2013년 복원된 것이다. 1907년 일본에 의한 성곽 해체 이후 문이 폐쇄되었지만 2006년 개방되었으며, 재건 후 2013년에도 문 앞이 개방되면서 직접 접근할 수 있는 대표적인 상징물이 되었다. 서울역, 명동, 시청을 이은 삼각의 중앙에 위치하는 대표적인 교통표지이며, 많은 사람들은 그냥 지나칠지도 모르겠지만 6세기 이상을 시민과 함께 한 대표적인 유적답게 개방 이후 직접적인 접근체험이 가능하게 된 만큼 둘러볼 가치가 큰 곳이다.',
 '숭례문-->늘 그 자리에 있어 그냥 지나치기 쉽지만 여유 있는 날 가만히 살펴보면 그 웅장함에 새삼 놀라게 된다. 지금의 숭례문은 복원된 숭례문이지만 여전히 보러 갈 만한 명소다.',
 '숭례문-->숭례문이 국보인 이유에 대한 학습을 한다면 이 건축물은 꽤 의미 있게 다가옵니다. 서울을 여행하는 사람들이라면 다른 전통 문의 역할도 함께 학습하는 게 좋습니다. 서울에는 한양 내성을 위한 여러 개의 문이 있고 각각의 역할도 있습니다. 그 역할과 역사적 의미를 함께 찾아 보세요.',
 '숭례문-->사실 전소 전에는 크게 신경쓰지 않았다.복원 후에 찾았으나 아쉬운 점도 많았다.가까이에서 직접 바라보며 느낄 수 있는 점은 좋았으나그래도 아직 많은 관리가 필요해보인다.외국인 친구가 오면 글쎄....... 남대문시장 가지 않는 이상 안데려갈 듯 하다.',
 '숭례문-->서울 시청쪽에서 바라보면 남대문 야경이 멋지다. 몇년전 불이타서 복원해서 가까이서보면 허접하다',
 '숭례문-->숭례문은 서울의 중심부에 위치해 있습니다. 시청과 광화문을 가는 길목에 있으니 천천히 산책하며 가는 것이 좋습니다. 근처 남대문 시장에서 쇼핑을 즐겨도 좋아요',
 '숭례문-->주위가 넓으면서 너무 횡하지 않아서 좋네요. 새로 지어진 건물이지만 복원이 잘된 것 같아요.',
 '숭례문-->대한민국을 방문한다면 꼭 한번 가볼만한 장소입니다. 그리고 한복 착용하였을때 입장이 무료이기 때문에 참고하세요.',
 '농업박물관-->한국의 농업과 농경 역사를 쉽게 이해할 수 있도록 만들어 놓아 아이들이 많이 찾지만 외국인들에게도 한번 쯤 들러볼만 함광화문이나 덕수궁, 정동길 쪽으로 와서 5호선 서대문역을 이용할 때 한번 쯤 들러보면 좋음',
 '농업박물관-->아이와 함께 둘러보기 좋은 곳이다. 구성도 알차고 미리 예약하면 여러가지 체험에도 참여할 수 있다. 가끔 무료 강의도 하는데 아주 유익하다.',
 '농업박물관-->농협본점옆에 있으며관람료는 무료입니다사전예약제는 아니며당일 입장 관람 가능합니다도심이라 주차는 여유롭지 않은것 같으며서울은 대중교통이 최고인것 같네요박물관은 민속촌의 축소판이라고보시면 될꺼같습니다예전 선조들의 지혜로운 생활과경제방식을 배울수 있습니다',
 '농업박물관-->생활의 , 산업의 기본이 되는 농업에 관한 박물관입니다.기본이 되는 산업분야이며, 최근들어 다시 각종 기술력이 더해져서 다시 재조명되고있는 농업.흥미로운 전시품들이 많아요. 농업체험활동등 다양한 대상들을 위한 프로그램도 운영되고 있습니다.',
 '농업박물관-->박물관이 인상적이었다. 지루하다고 생각하는 것, 살아있는 것 같은 집이지만 활기 넘치고 감사 표시, 필드, 등, 실제로 매우 흥미로운 박물관이 었습니다. 몇 가지 작물 의 성장 도 박물관 밖에서 작은 그림. 수많은 입체 모형 입니다. 제 생각에 아이들이 박물관을 즐길 수 있다.박물관에 있는 한국인 농부의 생활을 아주 보여 주는 것이 앞서 현대. 저는 거의 모든 주요 박물관에 서울, 최고의 것들 중에 하나인 경우, 특히 둘 이상의 누사두와 에 관심이 있다면 왕령. 한국어와 영어의 전시.1st 및 2nd 약 한시간 정도 가면 표지판을 읽을 바닥으로 마감되어 있습니다. 또한 지하에 있는 디스플레이, 현재 한국 농업 에 있는 제품 및 농민 단체, 생략할 수 있는 시간 이지만 바닥 층.',
 '남산골 한옥마을-->사실 이곳 찾아온건 아니고, 남산공원에서 내려오다가 통한 곳이 바로 이곳. 전통혼례도 올리고, 한옥 구경에 사진도 펑펑 ! 잘 나온다. 하늘도 파란색에 기와와의 연결 ! 끝!커피도 한 잔 할 수 있다 (민씨댁앞 전통공예품 판매장내)',
 '남산골 한옥마을-->충무로역 근처에 이런곳이 있는줄 몰랐다사람이 많지 않고, 붐비지 않아 조용하게 산책 하며멋스러운 한옥들을 구경하고 감상할수 있어요한옥 5개동과 한옥마을안에 계곡을 만들어 물이 자연스럽게 흐르고, 정자, 연못 등 전통양식의 정원구경할수 있다여러가지 체험 할수 있는곳들도 있는데, 괴물노리개 만들기 체험을 했는데 너무 좋았어요체험공간에서 보는 연못 풍경이 멋져요주차공간 협소, 입구들어오는 초입에 왼쪽 유료 주차장이용추천',
 '남산골 한옥마을-->날씨도 좋고 선책하기에 너무 좋은 날입니다.  한시간정도 산책하며 많은 사진을 찍었어요.  공기도 좋네요.. 대부분 외부에 있어 비올떄 조심하시고요. 저는 끝나고 명동으로 이동에서 코카클럽에서 무료 한복을 입고 무료 사진 촬영을 하며 맛있는 한국 음식을 먹었습니다.',
 '남산골 한옥마을-->한옥의 다양한 모습을 볼 수 있고 멋진 정원도 둘러볼 수 있고 타임캡슐도 매우 인상적이어서 좋았음. 꽃이 많이 피는 봄에 가면 더 좋음.',
 '남산골 한옥마을-->뭔가 귀여운 느낌마저 드는 재밌고 볼거리 많고 산책하기도 좋아요. 쇼핑도 가능 ㅋㅋ 다음엔 여자끼리 말고 남자랑 갈 수 있길 ㅋㅋㅋ',
 "남산골 한옥마을-->충무로에서 필름을 맡기고 날씨가 좋아 꽤나 걸었다.가을바람을 맞으며 생각없이 걸었다.독특한 이정표'남산골 한옥마을' 여기 이런 곳이 있었나? 궁금증을 이기지 못하고 또 다시 걸었다.충무로 한복판에 이런곳이 있다는게 재밌었고 꽤 다양한 프로그램을 진행중임이 흥미로웠다.다음에는 원하는 프로그램이나 행사에 맞춰 재방문 하려한다.",
 '남산골 한옥마을-->규모는 작지만 평지라 아이들 데리고 가기 좋은 곳이예요. 다양한 체험들이 있어서 재미있어요. 당일 예약도 되지만 이틀 전 미리 예약하는 것이 좋습니다',
 '남산골 한옥마을-->중국인이 많다. 충무로에 이런곳이 있는지 몰랐다. 정문앞에 한복대여점이 있어 한옥마을에서 한옥입으면 진짜 이쁘고 멋있었다. 비둘기가 많아서 아쉬웠다. 그리고 진짜 깨끗해서 산책하기 좋은 남산골한옥마을이다.',
 '남산골 한옥마을-->저는 북촌한옥마을 같은 곳을 생각했는데 이곳은 좀 인위적으로 꾸며놓았달까.실제 사람들이 살면서 지내는 걸 생각했는데 갔더니 쉬는 날도 있어서 놀랐어요.그래서 한옥 내부는 못보고 근처만 한바퀴 돌다 갔네요.북촌과 남산골 중 고르라면 저는 북촌이 더 나은거 같아요',
 '남산골 한옥마을-->충무로역에서 가까운 남산골 한옥 마을. 사실 지나가다가 우연히 발견해서 들어갔는데, 너무 아름다웠습니다. 오랫동안 잘 유지되었으면 하는 마음입니다! ㅎㅎ 겨울이어도 아름다웠는데 봄이나 가을에 가면 더욱 아름다울 거 같아요. ㅎㅎ',
 "명동-->코로나19 여파는 매년 늦가을 청계천에서 열리는 아름다운 빛초롱축제도 피해갈 수 없었다. 이에 (재)서울관광재단은 서울시의 후원으로 서울시 관광특구 4곳에 경제적 어려움에 처한 소상인과 코로나19 극복을 염원하는 시민들을 위한 ‘서울시 관광특구와 함께하는 2020 희망의 빛초롱’ 행사를 진행하고 있다. 장소별 행사 주제 및 기간이 다른 바 사전 검색이 필요하다(잠실 과 동대문 패션타운 관광특구는 각기 11/6일 11/13일 이미 종료). 크리스마스를 주제로 11/22일(일) 종료를 앞둔 명동 관광특구의 ‘희망빛축제’를 주말(11/21)을 맞아 살펴 보았다. 명동예술극장 앞에 타이틀 등(燈)과 주제 등(燈)을 설치하고 다른 2 곳(을지로입구역 하나은행 앞과 명동역 6번출구 앞)에 또 다른 조형물을 설치했다. 주말이라 그런지 적지 않은 시민들과 외국인들이 명동의 야경과 함께 ‘희망빛축제' 조형물을 다양한 방법으로 즐기고 있었다.참고로 서울관광재단에서 운영하는 희망의 빛초롱 축제는, 11월 22일부로 종료되었다. 다만 명동특구 자체적으로 크리스마스 트리, 멜리 캐릭터 등은 2021년 1월 15일까지 운영된다.",
 '명동-->명동 거리는 늘 사람이 많았는데 코로나 때문인지 ...  사람도 없고 여유롭게 잘 쇼핑하다 가요 ~피제이 호텔도 너무 가까워서 아주 교통편도 좋았답니다아 ✨',
 '명동-->대한민국에서 만날 수 있는 모든 형태의 쇼핑을 할 수 있는 곳. 내국인부터 외국인까지 모두가 쇼핑을 즐길 수 있는 곳으로 모두가 모이는 문화의 장소.',
 '명동-->Very nice place!! Korea’s famous sandwich franchise!!!명동에서도 맛볼수 있는 한국의 유명한 샌드위치 프랜차이즈 !! 포슬포슬한 에그 스크램블과 브리오쉬빵 ! 너무 맛있습니다 합리적인가격으로 명동에서도 이용가능하다니~~ 꼭 가보세요 ~',
 '명동-->관광객들이 명동에 더 많다. 여기에 화장품 샵들이 점차 관광객을 대상으로 영업하더니... 이제는 거의 모든 샵이 외국인대상으로 영업하는 것 같다. 중국어 일본어가 더 많이 들리는 한국의 명소 관광지다 보니.. 가격이 너무 비싸서 외국분들에게 추천하고싶지는 않다. 좀만 더 가서 남대문시장을 경험하는 것도 하나의 방법',
 '명동-->중국인 상대로만 장사하세요~한국인데 한국어는 하나도 안들리는 곳~명동은 성당빼고 갈 일이 없음 ㅋ길거리 음식도 별것 아닌게 5천원씩이나 받네',
 '명동-->중국관광객이 많이 다니며 한국 같지 않은 느낌이 큽니다 쇼핑 할게 매우 많고 맛있는 식당들도 많습니다 다만 주차가 불편하고 비싸니 대중교통이용하시길',
 '명동-->여러맛집, 군것질거리와 많은 쇼핑거리가 있는 핫플레이스입니다그만큼 유동인구가 많아 복잡합니다오사카, 대만 등 세계 어느나라를 가도 이런느낌의 쇼핑거리는 비슷하지만 또 이런쇼핑거리가 여행의 묘미이기도 합니다여행마지막날 저녁에 구경하며 쇼핑도하고 여행선물도 고르는 마지막날 코스로 추천합니다',
 '명동-->외국인 관광객이 많아지면서 평소엔 잘 가게되진 않지만 그래도 맛집이 많아서 종종 가게 되는 곳이예요저녁되면 오픈하는 노점상도 많아서 구경하고 먹을게 많아서 잼있어요',
 '명동-->명동거리는 언제나 북적이며 일본인과 중국인이 많다. 한국인인 나는 자주 가진 않지만 한번씩 가곤 하는데 이번엔 길을가다 허니버터 아몬드 매장이 크게생긴걸 봤다 무료 시식도 가능하고 한번쯤 가볼만하다. 하지만 사람이 너무 ㅁ낳고 길거리 음식이 너무 비싸다',
 '남산과 N서울타워-->충무로역에서 순환버스 02 or 04번 이용하고 남산타워 도착 하면 됩니다. 국립극장 앞에서 타면 사람 많아서 못탈수도 있어요. 전망대 입장권 비싸긴한데 올라가서 구경할만한거같아요.  미리 구매 안했다면 현장에서도 구매 가능해요. 남산타워 t1광장에서 트립닷컴 현장 발매가 가장 저렴 합니다. qr 코드 스캔하고 바로 사용가능해요. 현장에서 25%할인해주고 있어요. 가서 이용하시면 좋을거같아요. 회전식 레스토랑이나 한쿡이라는 식당은 예약제라서 이용이 어려워요.1~3층에 식당이용하면 됩니다.',
 '남산과 N서울타워-->좋은 위치!! 서울에서 가장 높은 지점이다. 서울 시내 전체를 볼 수 있습니다. 시원하고 깨끗한 장면과 함께 연인들이 남긴 자물쇠가 많다',
 '남산과 N서울타워-->서든무반동핵 『로드.com』 월핵 오토에임 정지없는핵 언로드 서든팅핵 서든탈주핵 조종핵 강퇴핵서든무반동핵 『로드.com』 월핵 오토에임 정지없는핵 언로드 서든팅핵 서든탈주핵 조종핵 강퇴핵서든무반동핵 『로드.com』 월핵 오토에임 정지없는핵 언로드 서든팅핵 서든탈주핵 조종핵 강퇴핵서든무반동핵 『로드.com』 월핵 오토에임 정지없는핵 언로드 서든팅핵 서든탈주핵 조종핵 강퇴핵',
 '남산과 N서울타워-->뭐든 좋다. 그냥 가서 아이스크림만 먹고 와도 좋고 스타벅스에서 커피만 마셔도 좋다. 식당 많고 구경만 하고 걸어서 내려와도 바로 명동이라 편리하다',
 '남산과 N서울타워-->코시국 전에는 서울오면 꼭 가던곳입니다ㅎㅎ코로나가 좀 안정되면 다시가고프네요ㅜㅜ올겨울 지나고는 남산타워에서 벚꽃을 볼수있기를 바랍니다ㅜㅜ',
 '남산과 N서울타워-->12월은 1일부터 15일까지는 걸어서 올라가는걸 염두하시고 가세요언덕같은 산이라 남자에게는 별거 아니지만 여자분은 좀 힘드실수 있습니다',
 '남산과 N서울타워-->서울의 야경을 한 눈에 볼 수 있는 곳. 하지만 미세먼지가 심한 날에는 절대 방문하시지 마시기 바랍니다. 서울을 하나도 볼 수 없을지도 모릅니다. 좋은 날에 방문하세요.',
 '남산과 N서울타워-->오르막길이 여러갈래인데, 국립극장쪽으로 올라가면 완만하고 명동역1번쪽으로 나가면 좀 치고 올라가는 재미가 있습니다. 맑은 날 정상에 오르면 서울시내가 정말 아름답게 펼쳐져 보입니다.',
 '남산과 N서울타워-->사울역에서 가까워서 역에 도착하자마자 바로 찾아간곳입니다타워끝까지놀라갔는데 입장료가 좀 비싸지만 서울을 한눈에 볼수있어서 좋았습니다',
 '남산과 N서울타워-->어릴적엔 남산타워로 불리우던곳.그시절에 63빌딩도 생기기 이전이어서 명실공히 서울에서 가장 높은 전망대를 가지고 있었던곳.지금은 롯데타워도 생기고 해서 최고의 높이를 가지고 있지는 않지만.그래도 서울에 대표적인 명소로 손꼽히는 곳이죠.전망대에 야간 조명칼러에 따라 날씨를 알려주기도 하고요.',
 '삼성미술관 리움-->박물관과 전시에 관심이 있다면 반드시 찾아가야 할 곳입니다. 개별 유물과 미술품의 질이 훌륭하며 전시조명을 완벽하게 통제하는 점에선 감탄이 나옵니다. 마리오 보타,장 누벨, 렘 콜하스가 참여한 미술관 건축도 매우 인상적이니 눈여겨 보시기 바랍니다.',
 "삼성미술관 리움-->삼성에서 하는 미술관이다보니 전체적으로 건물도 내부도 좋아요,.'언덕에 있지만 찾아가기 어렵진 않아요.가끔 좋은 전시를 할때 찾아가면 좋더라구요, 보통 큰 조형물전시를 많이 해서 사진찍기도 좋아요.,",
 '삼성미술관 리움-->한국, 그 중 서울을 대표하는 미술관 중 하나이다. 삼성에서 소유하고 있는 미술관으로 한국 전통 미술부터 신세대의 미술까지 다양한 전시가 있다.',
 '삼성미술관 리움-->가끔 좋은 기획전을 하면 들르기 좋은 곳이다. 주위에 한강진 맛집, 카페도 가고 이태원을 거쳐 해방촌까지 쭉 걷는 코스가 좋다.',
 '삼성미술관 리움-->외국인 친구랑 갔는데 재밌게 구경하고 왔네요~모던한 작품들도 많고 한국적인 작품들도 많이 있어서 데이트 코스로도 좋을것같아요! 굿굿',
 '삼성미술관 리움-->국립중앙박물관과 다르게 5000~10000원의 입장료가 있지만 대신 훨씬 조용히, 진짜 아름다운 문화재를 모아 감상할 수 있습니다. 사진촬영이 안 되는 게 아쉽지만 눈으로 봐도 충분히 아쉽지 않을 박물관.',
 '삼성미술관 리움-->같이 여행했던 동행분이 여기가 풍수지리에 좋다는 말을 하셔서, 그 관점에서 방문해 봤습니다.  좋은 기운을 많이 받을 수 있어서 좋았습니다.',

In [81]:
contents

['경복궁-->대한민국의 역사가 잠들어 있는 곳. 서울을 방문했다면 꼭 방문해야 되는 곳. 경복궁은 우리의 역사다. 넓은 경복궁을 산책할 수 있는 것은 언제나 행복이다.',
 '경복궁-->경복궁은 국민들이 자주 찾는곳으로 작성자는 주말에 자주 가족들과 방문하고 있음.특히 가족들과 방문시 옛고궁의 멋을 즐길수 있으며 쾌적한 공기와역사를 체험하고 힐링할수 있는곳임.',
 '경복궁-->날씨 좋은 날 종종 산책하러 경복궁에 가는데 마음이 편온해지는 기분이라고 할까요? 특히 봄이나 가을에 산책가는 걸 추천해요!',
 '경복궁-->Goooooood 다 좋습니다 다음에 또 오고 싶네요 근처 관광지도많고 먹을거리도많네요 서울올때마다 자주이용중인데 또오고싶습니다',
 '경복궁-->요새 더더욱 코로나로 인해 사람 방문이 적음. 두자녀 동반시 성인 입장무료. 지금 시기에 나들이 하기 딱 좋은곳. 지하철 광화문역이나 종각역이용 편리.',
 "경복궁-->조선 개국 4년째인 1395년에 처음으로 세운 으뜸 궁궐이다.'하늘이 내린 큰 복' 이라는 뜻으로 경복궁이라 이름지었다.가장 아름답고 웅장한 이 경복궁은 임진왜란, 일제강점기 2번에 걸쳐 일본의 악랄하고 잔인한 파괴를 당한 악연을 갖고있다.향원정은 보수 공사로 인해 볼 수 없지만 아름다운 경회루만으로도 충분한 경복궁이다.",
 '경복궁-->한국 건축물의 아름다움을 느낄 수 있는 곳이고, 한복을 입었을 때 입장료는 무료.주변에 한복 대여점이 많으니 한번쯤 대여해서 입어보는것도 나쁘지 않을듯',
 '경복궁-->조선의 성곽 안에는 박물관도 있고 경회루 등 볼것이 많다. 외국인들 및 연인들도 주변에서 한복 및 특수복장 빌려서 성을 둘러보며 데이트를 즐기기에 딱 좋다. 야간개장도 하니 잘 알아보고 올것 한국사람이라면 한번이상은 꼭와봤고 , 외국인들에게도 좋은 관광지라고 생각한다. 앞에 광화문 광장 청계천 뒤로 삼청동  이주변에 연계된 명소들도 많기 때문에 꼭 추천한다.',
 '경복궁-->대부분의 사람들이 여행을 간다면 그 나라의 유서 깊은 궁전을 찾게 된다.한국에서는 그 곳이 바로 경복궁이다.지금의 경복궁은 원래의 것보다 많이 축소되었지만 그래도 깨끗이 잘 정돈되어 있으며 위엄이 있다.',
 '경복궁-->몇번을 가도 감탄하게 되며 산책하기 최고인 경복궁 매번 갈때마다 정교함과 운치에 또한번 반하게 되는곳 주변에 볼거리도 많음',
 '삼청동 거리-->저번달에 아주 오랜만에 다시 방문. 10년만에 재방문인데 그사이에 카페나 작은 상점 옷가게가 눈에 많이 띄었다. 서울내에 한옥건물 제발 보존 해주세요',
 '삼청동 거리-->삼청동길 한옥건물들을 볼수있는 거리중 한곳다만 예전에 비해 상권이 많이 없어졌어요..그래도 걸으면서 구경하기에는 좋아요.',
 '삼청동 거리-->이 곳에서는 기와나 목재 등을 이용해 한국의 전통적인 느낌을 살린 현대식 건물이 많아서 이색적인 도시 풍경을 감상할 수 있다. 걷기만 해도 재미있다.',
 "삼청동 거리-->삼청동 팥죽 맛집 '서울에서 두번째로 맛있는 집'을 찾아 가면서 삼청동 메인거리를 걸으면서 곳곳에 임대 표시가 되어 있는 빈 가게들이 너무 많이 생긴 것을 보고 놀랐다. 이곳도 젠트리피케이션 때문에 자영업자들이 어려움을 겪고 있는 것 같은데 우리나라 대표적인 관광지인 궁 인근에 있어 우리나라 전통 공예품을 판매하는 상가들이 번성하면 좋을텐데... 아쉬움이 너무 컸다.",
 '삼청동 거리-->예전엔 갈만한 식당과 카페를 줄줄이 알았는데 요즘은 정보가 없다. 그래도 갈때마다 옛 추억때문인지 정겹고 좋았다. 사람이 많이 없어서 여유롭게 가기 좋은 곳.',
 '삼청동 거리-->퇴근 후 데이트코스로 좋은 길입니다. 비교적 중심부에 위치해 있으며, 저녁에 데이트 목적으로 방문하는 분들이 많습니다. 정독도서관부터 시작해 식사 후 걷기에도 괜찮습니다.',
 '삼청동 거리-->삼청동길 방문한지 얼마 되지않았어요. 길은 좁고 다니기 불편하지만 한옥들이 몰려있고 한옥카페를 즐길수있어 좋았습니다. 더군다나 루프탑의 카페가 많아 좋았어요. 여유를 제대로 느끼실수있습니다. 그리고 수제비집 유명해요 꼭 방문해서 드셔보시길.. 짱맛',
 '삼청동 거리-->외국인이 많이 찾아오는 삼청동길, 주말에는 국내 여행객들까지 있어 걷기 힘들때도 있다. 인기있는 골목길 말고 조용하게 산책할 수 있는 코스도 있으니 잘 찾아보면 좋다.',
 '삼청동 거리-->봄되면 꼭 가는 삼청동. 곳곳에 예쁜 상점들도 있고 맛있는 한식집이 많다. 사진찍기도 좋고 그냥 산책하는 것만으로도 기분 좋은 곳!',
 '삼청동 거리-->데이트 장소로 추천받는 곳들 중 하나로 다양한 볼거리와 음식들이 있는 곳입니다 여기 떡볶이 집이 아주 유명하여 줄을 섭니다',
 '인사동-->코로나때문인지 인사동거리에는 사람의 수는 어느정도 있긴했지만 무척이나 한산했다. 아마도 영업하는 상점들이 많이 문을 닫은것 때문이 아닌가 싶다. 커플이라면 차한잔 마시면서 30~40 분 정도 갈으면서 즐길수 있는 분위기',
 '인사동-->오랜만에 방문한 인사동에서 전통도 체험하고 구경도 실컷 했음. 다소 아쉬웠다면 주변에 노점상들이 너무 난잡하게 산재해서 지저분하다는 느낌이 들었고 기념품 판매하는곳에서 많은 기념품들이 중국산이어서 너무 아쉬였음.',
 '인사동-->인사동하면 전통골목 아니겠습니까 ?전통차, 한정식 골목 등으로 나누어져 즐기기 좋은 장소지요외국인들도 많이 오고 지방에서 서울오면 꼭 보여주고 싶은곳이지요',
 '인사동-->코로나 영향으로 주말인데도 한산합니다.주말에는 차량진입금지 입니다.낮에도 볼거리가있지만 밤에도 화려한곳입니다.다양한 제품과 먹거리 액티비티가 있습니다가족,연인,친구들과 방문해도 좋습니다',
 '인사동-->프랜차이즈 화장품가게로 가득할거같았는데아직 골목골목은 살아있네요비싸서흠이지만예전인사동으로 부활하길 바래봅니다',
 '인사동-->안국역이랑 가까워서 구경도하고 한옥마을이랑도 가깝고 교통이 편리합니다걸어서 구경할데가 많은것같아요주말에는 많이 혼잡하네요',
 '인사동-->먹고 배부르면 쌈지길이나 한바퀴 돌며 소화시킨다.그리고 주변에 뭐 먹잘것도 없는데다가 있어도 비싸기만 할 뿐이다.그냥 중국인들 상대로 장사하세요.',
 '인사동-->예전에 비해 관광객이나 현지인이 믾이 줄어든 느낌이 있지만 여전히 정겹고 재미있는 인사동 주차가 협소하니 대중교통 추천합니다',
 '인사동-->외국사람들이 여행오면 꼭 들르는 곳이라죠?그만큼 유명한 곳도 많고 한데 좀 상업화 된 거리라 막상 한국인은 자주 안가게되더라구요. 하지만 이 길만을 목적이 아니 종로전체를 걸으면서  돌아다니기엔 재밌는 곳이예요. 쓰윽 한번 들러보세요!',
 '인사동-->한국적인 느낌을 얻고자하는 외국인들에게 한번 쯤은 와볼만한 곳이나, 요새 너무 상업적인 가게가 많아졌고, 전통적인 특색은 사라지는 추세. 다만 전통적인 음식과 식당이 많으니 식사하러 와도 좋을 거리 .',
 '조계사-->한국의 조계종을 대표하는 사찰입니다.사찰의 규모는 작으나 상징성이 있습니다.사대천왕도 동판으로 제작되어서 톡특합니다.사찰내에 아주오래된 고목이 있어서 한층더신비감을 느끼게 합니다.도심에 위치하고있어서 접근성이 좋습니다.',
 "조계사-->과거 유명했던 사이비 종교 보천교의 본당인 '십일전'을 인수해 개조한 절입니다. 덕분에 규모 하나만큼은 국내 최대 목조건물 중 하나. 다만, 사시사철 연등이 걸려있어 건물 전체의 웅장함을 느끼기에는 늘 부족하다는 생각이 들어요.",
 '조계사-->종교가 없어도 가끔 마음이 복잡할때는 절이나 교회에 방문할 것을 추천한다. 조계사는 다양한 행사도 많이하고 차분하게 마음을 추스릴 수 있는 곳이다. 좋은 마음으로 소원을 기원하기에 좋다. 한시간 미만으로 방문하면 좋겠다.',
 '조계사-->이맘때 항상 방문합니다.국하축제하고 절자체도 너무이뿌고 접근성도 좋아서올해는 국화분재가있어 아버지가 흥미로워하셨어요매번하지만 위치도바뀌고 전시도 조금씩 바껴서 너무 좋아요 국화빵도팔고 좀 이색적이지만 좋았어요^^',
 '조계사-->조계사는 대한불교 조계종의 총본산으로 봉은사, 길상사와 함께 서울의 대표 불교 사찰입니다. 그 중요성과는 달리 절의 규모는 작은 편이지만 조계종 측에서 장기적으로 조계사 성역화 사업을 진행하고 있어 점차 절의 규모는 커질 것으로 예상됩니다. 대웅전 내의 아미타여래상, 석가여래상, 약사여래상 앞에 앉아 잠시 명상을 해보시길 권합니다. 대웅전 뒷편의 현대적인 건물 지하엔 불교박물관이 있으니 꼭 방문하시기 바랍니다.',
 '조계사-->종로갔다가 들르기 좋은 곳. 불상이 생각보다 크고 위엄있어서 놀랐다. 다만 그 외에 시설이 많지 않은 작은 절이다. 한번쯤 가볼만한 곳',
 '조계사-->규모가 매우 큰 절 중 하나입니다. 종로구 중심가에 위치한 절로 부처님 오신 날 혹은 외국인 손님이 왔을 때 방문하기 좋습니다.',
 '조계사-->인사동 바로 옆에 있는 조계종 대표 절입니다.. 도심에 한적하게 불교문화를 느낄 수 있는 곳이라, 가면 마음이 편안해 지고 고즈넉해서 좋습니다.',
 '조계사-->종로 한가운데에 위치에서 접근성이 가장 좋은 곳이 아닌가 생각된다. 특히 부처님 오신날쯤에는 연등과 꽃이 예쁘게 꾸며져 있어 너무 좋다.',
 '조계사-->반드시 들러야 하는 곳은 아니짐나 그래도 들르면 좋을 것 같습니다. 볼 거리 많은 종로에서 조계사에 들르면 참 좋을 것 같단 생각이 듭니다.',
 '청와대-->6개월 전에 예약하고 주말에가족들과 함께 다녀왔습니다.경복궁은 여러번 갔는데 항상 멀리서 보던 청와대를 들어가보니 상징적인 곳이라경비가 삼엄하긴 하지만 고즈넉하고 좋았습니다.투어중에는 화장실이 없으니청와대관람차에서 내려 보안검색하기전 화장실을들러주는게 좋을 것 같습니다.기념품으로 성인에게는 머그컵아이들에게는 버스카드를 넣을수 있는 목걸이지갑을주었습니다. 산책하는 겸 저는 너무 만족했으나햇빛을 피할곳이 따로 없으니 모자나 생수 이온음료 정도는 챙겨 가세요!',
 '청와대-->내부관람을 위해서는 사전예약이 필요합니다.예약을 하지 않았을 경우 외부전경을 보면서 기념촬영하기 좋습니다.',
 '청와대-->대한민국 대통령의 집무실과 관저가 있죠!!청와대 앞길이 최근에 개방되서 좀 더 가까워진 느낌이에요!!!',
 '청와대-->내부로는 예약하지 못해서 들어가지 못했지만 외곽을 따라 돌담길을 걷는건 너무 멋져요. 특히 가을에 낙엽이 질때 더 멋스러워욘',
 '청와대-->청와대 관람은 예약이 필요하나 경복궁 담을 따라 청와대 앞을 걸어봐도 좋습니다. 아름다운 길입니다.',
 '청와대-->청와대 견학은 예약제로 운영하지만, 올해부터 청와대공원 인근 검문없이 자유롭게 산책할 수 있습니다.편안하게 청와대 공원 산책하고, 청와대 바라보며 삼청동까지 천천히 걸었습니다.',
 '청와대-->예약하고 가셔야 해요경비 엄청 삼엄하고 사진도 찍을수 있는 곳정해쟈 있는데 그럼에도 불구하고 유익함단 볕 피할데가 없어서 모자 필수친절하고 아이들 교육에도 좋아요',
 '청와대-->물론 통치의 핵심장소이기도 하나 뒤에 병풍처럼 두른 산들과 앞 광화문 광장.양쪽 북촌과 서촌 사이에 청와대가 있다.위치적으로도 서울의 요지이자 중심에 청와대가 있다.차가 지나가야하는 루트라 검문을 하고 지나갔는데  의경들이 친절했고 비록 지나치기만 했지만  요새같은 시국에 만감이 교차했다.',
 "청와대-->저는 청와대가 너무 궁금하여~ 미리 예약을 해서 입장 하였습니다. 물론 2~3개월전에 예약제로 운영이 되는곳입니다. '관람료는 없어요.. 무료입니다. 대신 개인일경우 10명이하로 , 단체일경우 11~200명이하로 신청이 가능합니다. 관람은 매주 화요일~금요일 토요일은 둘째, 넷내주에 가능합니다. 관람 시간은 오전 10시, 11시 오후 2시 3시로 하루에 4번을 운영중입니다.  총관람은 한시반이 걸립니다. 관람 코스는 만남의 장소-> 홍보관-> 녹지원 -> 구 본관터-> 소정원 -> 본관 -> 영빈관 -> 칠궁-> 무궁화동산 -> 청와대 사랑채입니다. 대중교통을 이용하시는 분들은 지하철 3호선 경복궁역 5번 출구를 이용하여 주셔야 합니다.",
 '청와대-->대통령이 계신곳이라 경비가 삼엄하네요, 경복궁 뒤쪽에 있어 아이들 교육면에서도 고궁갈때 걸어가보면 좋아요 청와대 투어도 있다하니 내부도 가보고 싶네요',
 '보신각-->보신각 지나가면서 한번식 사진도 직고 너무 좋아 하는대 요즈음은 한번식 지나가다 보면 대모만 하고있어서 참 그렇다~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~문화재 만큼 이나 성수러워야하는대 ㅠㅠㅠ',
 '보신각-->티비를 보면 항상 커플들이 모여서 키스하는 장소로 기억이 많이 남네요. 평소에가면 가까이 접근은 하지못하나, 공원으로서 인상깊습니다.',
 '보신각-->매년 말일에 이곳을 방문하면 tv에 나올지도 모른다. 평소에는 별일 없이 조용한곳.도심 한 가운데 이런 종이 있다는것이 조금 신기',
 '보신각-->종각역 지나갈때, 아무생각없이 지나곤 했는데여기가 바로 보신각 이더라고요.ㅋㅋㅋ보신각 타종, 항상 그맘때면 정말 사람이 엄청나게 몰려서그거 한번 듣겠다고 말이죠.집에서 티비를 보는대도, 사람들이 무지하게 많아 보이던데직접 온 사람은 오죽하겠습니까.멀리서 볼수 밖에 없어서 아쉽긴 하지만, 그래도 문화의 유산안내표지만 보고 갈 때름이네요~',
 '보신각-->연말연시에 서울에서 타종 행사를 하는 곳으로 유명한 이곳은 서울시민 모두가 다 아는 랜드마크로 종로2가 도심 한복판 누각에 종이 있어 새삼 우리 민족의 자긍심을 일깨우는 곳입니다.',
 '보신각-->점심 12시 전에 가면한복을 입고 종을 칠 수 있는이벤트가 있습니다.11시 30분 정도에 가서 사진찍고12시에 종을 치는데 정말 좋았어요.내국인은 인터넷에서 미리 신청을 해야하지만외국은은 즉석에서 가능합니다.',
 '보신각-->도심속의  한옥무더운 여름에 방문하면 낭패봅니다그늘에 쉴만한곳도 없습니다동선은 짧아서 짧은시간 관람 가능하며보신각종 앞에까지는 못가게 작은 울타리 쳐져있습니다도심이라 자차보다는 대중교통 이용하시면되고요굳이 자차를 이용하신다면주변 공영주차장 확인후 출발관람은 남녀노소 무료입니다',
 '보신각-->매년 새해가 되면 제야의 종을 타종하는 곳이다. 평상시에는 그냥 종이 위치한 장소이지만, 시민들이 쉬어가거나 도심 내에 한국적인 건물이 지어져 있어서, 인상적인 느낌을 주기도 한다.',
 '보신각-->청계천으로가는 길에이 건물을지나 갔다. 간판은 벨 파빌리온으로 그것을 소개했습니다. 불행히도, 파빌리온 입구는 줄을 벗어나기 때문에 입장 할 수 없었습니다.',
 '보신각-->이것은 거대한 종소리가 들려있는 파빌리온입니다.이곳은 역사적인 장소이기 때문에, 새해 맞이에 여기에서 종을 울리는 것은 나라에서 가장 기대되는 행사입니다. 매우 붐비는. 가입을 원하지 않으면이 지역을 피하십시오.종로 1가 교차로에 위치하여 쉽게 접근 할 수 있습니다.내부로의 접근은 허용되지 않습니다. 거의 혼잡하지 않았습니다. 벨이 울리는 것과 같은 이벤트가있을 때 방문하는 것이 좋습니다.',
 "이화장-->코로나19 여파는 매년 늦가을 청계천에서 열리는 아름다운 빛초롱축제도 피해갈 수 없었다. 이에 (재)서울관광재단은 서울시의 후원으로 서울시 관광특구 4곳에 경제적 어려움에 처한 소상인과 코로나19 극복을 염원하는 시민들을 위한 ‘서울시 관광특구와 함께하는 2020 희망의 빛초롱’ 행사를 진행하고 있다. 장소별 행사 주제 및 기간이 다른 바 사전 검색이 필요하다(잠실 과 동대문 패션타운 관광특구는 각기 11/6일 11/13일 이미 종료). 크리스마스를 주제로 11/22일(일) 종료를 앞둔 명동 관광특구의 ‘희망빛축제’를 주말(11/21)을 맞아 살펴 보았다. 명동예술극장 앞에 타이틀 등(燈)과 주제 등(燈)을 설치하고 다른 2 곳(을지로입구역 하나은행 앞과 명동역 6번출구 앞)에 또 다른 조형물을 설치했다. 주말이라 그런지 적지 않은 시민들과 외국인들이 명동의 야경과 함께 ‘희망빛축제' 조형물을 다양한 방법으로 즐기고 있었다.참고로 서울관광재단에서 운영하는 희망의 빛초롱 축제는, 11월 22일부로 종료되었다. 다만 명동특구 자체적으로 크리스마스 트리, 멜리 캐릭터 등은 2021년 1월 15일까지 운영된다.",
 '이화장-->명동 거리는 늘 사람이 많았는데 코로나 때문인지 ...  사람도 없고 여유롭게 잘 쇼핑하다 가요 ~피제이 호텔도 너무 가까워서 아주 교통편도 좋았답니다아 ✨',
 '이화장-->대한민국에서 만날 수 있는 모든 형태의 쇼핑을 할 수 있는 곳. 내국인부터 외국인까지 모두가 쇼핑을 즐길 수 있는 곳으로 모두가 모이는 문화의 장소.',
 '이화장-->Very nice place!! Korea’s famous sandwich franchise!!!명동에서도 맛볼수 있는 한국의 유명한 샌드위치 프랜차이즈 !! 포슬포슬한 에그 스크램블과 브리오쉬빵 ! 너무 맛있습니다 합리적인가격으로 명동에서도 이용가능하다니~~ 꼭 가보세요 ~',
 '이화장-->관광객들이 명동에 더 많다. 여기에 화장품 샵들이 점차 관광객을 대상으로 영업하더니... 이제는 거의 모든 샵이 외국인대상으로 영업하는 것 같다. 중국어 일본어가 더 많이 들리는 한국의 명소 관광지다 보니.. 가격이 너무 비싸서 외국분들에게 추천하고싶지는 않다. 좀만 더 가서 남대문시장을 경험하는 것도 하나의 방법',
 '이화장-->중국인 상대로만 장사하세요~한국인데 한국어는 하나도 안들리는 곳~명동은 성당빼고 갈 일이 없음 ㅋ길거리 음식도 별것 아닌게 5천원씩이나 받네',
 '이화장-->중국관광객이 많이 다니며 한국 같지 않은 느낌이 큽니다 쇼핑 할게 매우 많고 맛있는 식당들도 많습니다 다만 주차가 불편하고 비싸니 대중교통이용하시길',
 '이화장-->여러맛집, 군것질거리와 많은 쇼핑거리가 있는 핫플레이스입니다그만큼 유동인구가 많아 복잡합니다오사카, 대만 등 세계 어느나라를 가도 이런느낌의 쇼핑거리는 비슷하지만 또 이런쇼핑거리가 여행의 묘미이기도 합니다여행마지막날 저녁에 구경하며 쇼핑도하고 여행선물도 고르는 마지막날 코스로 추천합니다',
 '이화장-->외국인 관광객이 많아지면서 평소엔 잘 가게되진 않지만 그래도 맛집이 많아서 종종 가게 되는 곳이예요저녁되면 오픈하는 노점상도 많아서 구경하고 먹을게 많아서 잼있어요',
 '이화장-->명동거리는 언제나 북적이며 일본인과 중국인이 많다. 한국인인 나는 자주 가진 않지만 한번씩 가곤 하는데 이번엔 길을가다 허니버터 아몬드 매장이 크게생긴걸 봤다 무료 시식도 가능하고 한번쯤 가볼만하다. 하지만 사람이 너무 ㅁ낳고 길거리 음식이 너무 비싸다',
 '국립민속박물관-->국내인들도 그냥 가볼만 하다.경복궁 한바퀴 돌고 사진찍고 나오면 있는 곳인데 그러면서 한번 들르면 된다.나에겐 딱히 의미가 있진 않다.',
 '국립민속박물관-->나이드신 부모님과 방문하면  옛 생각에 입가에 미소가 절로어머 이것봐, 옛날엔 이랬지 하시며 말씀이 많아지시구요 손자 손녀들과 함께 보러오신 분들도 보기 좋아보이더라구요. 예전 시대를 배경으로 타임머신 타고간듯 즐거운 시간 가능합니다',
 '국립민속박물관-->아이들과 방학때나 주말에 꼭 한번은 가 보는 곳입니다 .도심속에 있어서 편리한 대중교통으로 아이들에게 교육적인 곳을 데리고 갈 수 있는것이 좋아요',
 '국립민속박물관-->외국인 데리고 경복궁을 방문하는데 날씨나 환경으로 인해서 경복궁을 관람할 수 없는 환경이라고 한다면 여기만큼 좋은곳은 없다. 무료로 입장이 가능한 곳이며 각 나라의 언어별로 설명을 들을 수 있고, 굳이 설명이 아니더라도 눈으로 둘러보기 충분한 가치를 가지고 있다 전체적으로 둘러보는데 걸리는 시간은 짧으면 20분 길게 잡으면 1시간 정도 걸린다',
 '국립민속박물관-->경복궁 안에 위치한 국립 민속 박물관, 어린이들 역사 공부도 할겸 겸사겸사 가본 곳이다. 건물이 웅장해서 사진 찍는 사람들이 많았다.',
 '국립민속박물관-->이곳은 국립 고궁 박물관 과 마찬가지로 경복궁 내에 자리해 있으며 외부에서도 출입이 가능하다 또한 입장료는 없다. 이곳은 고궁 박물관에 비한다면 사실 별로 볼것은 없다고 느껴지는 곳이며 전시 물품 조차도 적은 편이다. 하지만 그만큼 시간이 많이 소요되지는 않으니 경복궁에 왔다면 같이 방문해보길 바란다.금요일에는 9시까지 연장 영업 한다.',
 '국립민속박물관-->대부분의 박물관은 좋다 민속 박물관은 생긴지 얼마 안되너 시설도 깨끗하고 다양한 전시회도 해서 좋다 아이와 자주와도 좋을듯 하다',
 '국립민속박물관-->특별히 확끌리는 장면은 없지만, 오밀조밀하게 한국에 정서 문화를 잘 녹여낸거같아요. 외국인 친구들을 데리고 구경하기 좋은 곳입니다.',
 '국립민속박물관-->경복궁을 간 김에 들린 민속 박물관인데, 내부 전시물도 좋았지만, 예상외의 아기자기하고 다양한 물건을 파는 기념품점도 좋았다.',
 '국립민속박물관-->현대미술관에 들렀다가 바로 앞에 있기도 하고 입장료도 따로 없어서 들렀는데, 그닥 볼 만한 건  없었네요. 바닥이 모래였던 것도 그렇게 좋진 않았구요. 시대가 변한만큼 전통의 모습을 유지하면서도 조금 더 깔끔하고 현대적으로 꾸미는 것도 좋을 것 같아요. 궁이 아니라 박물관이니까요.',
 '사직단-->관광객들이 많은 경북궁쪽에서 독립문으로 조금만 걸어오면 조선시대 땅과 곡식을 위한 제살를 위한 사직단이 있습니다 지금은 주변에 높은 빌당과 상가가 들어와 덩그러니남아있지만 그래도 들어가면 푸른 나무들이 있어서 시끄러운 도시에서 조용히 쉴수있는 공원이 되네요',
 '사직단-->근처에 회사다닐때 시간이 남아 둘러본 곳입니다.아직 유명하지 않아서 사람도 별로 없고분위기도 독특하고 예뻤습니다.아이들과 함께 가족단위로 와도 좋을 곳이라고 생각합니다.',
 '사직단-->도심속의 작은 숲.. 사람이 적어 더욱 좋다. 커피한잔과 도시락에 차한잔.. 딱 좋은곳이다.',
 '사직단-->조선시대 옛모습으로 복원예정인 사직공원도심속에 여유로운 산책을 하기를 원하시면 추천합니다.사직공원에 가면 종로도서관 및 어린이도서관이 있으니 겸사겸사 추천드립니다.제가 어릴때는 뛰어놀 수 있는 공간이 넓었는데 지금은 조선시대 사직단을 복원한다고 펜스쳐놓고 그래서 좀 아쉬원데 도심속에 여유를 느끼시려면 사직공원 추천합니다.',
 '사직단-->도심에 이런 곳이 있나하고 놀랄민한 곳임.  경복궁역에서도 가까운 편인데 경북궁, 덕수궁 등과는 다른 조용한 분위기가 독특함. 시간되면 북악스카이웨이쪽으로 가는 것도 좋을듯',
 '사직단-->사대 공원은 서대문 교도소 박물관과 경복궁 사이의 중간 지점에 위치하고있어 두 명소 사이를 걸어 다녔습니다. 공원은 방문 할 우리 목록에 없었다. 오히려 우리가 길의 보도에서 볼 수 있었던 외벽과 건물은 우리를 끌었다.공원은 흥미 진진한 역사였으며, 고려 왕조 (918-1392) 이후 가을과 봄에 신에게 준 의식과 희생이이 곳에서 행해졌 다. 관습의 목적은 농작물이 풍성하기를 바라는 것이었다. 돌 수정은 1395 년에 태조 왕이 제정 한 것이고, 더 이상 존재하지 않고 단지 플랫폼 만 남아있다. 관습은 1911 년에 끝났지 만 1988 년 국경절에 다시 시작되었습니다.공원의 큰 부분은 범위를 벗어나지 만 닫힌 울타리를 들으며 사진을 찍을 수있었습니다. 우리는 공원에서 우리의 평화로운 시간을 즐겼습니다.이 주일 오후에 방문객이 거의 없습니다.',
 '사직단-->이것은 신들의 제단을 둘러싼 공원입니다.제단 지역은 담장으로 격리됩니다. 방문자는 주변 공원을 걸 으면서 울타리를 들여다 볼 수 있습니다.할 일이 많지 않습니다. 단지 몇 명의 방문자가 오래된 나무로 공원에서 휴식을 취합니다. 다른 사람들은 역사서에서 강의를 듣습니다.',
 '사직단-->이유는 공원에 갔는데 방문하려면 sajikdan. 이는 고대 변경 곡립 토양과 비슷한 변경에 베이징. 불행히도, 이 공개됩니다. 그 곳에서 기념사진을 찍는 슬로프에 제단, 하지만 좋았을 수 있고 주위에 걸었다. 공원 자체는 충분히 좋은, 특별한 건 없었지만. 이 숙녀 놀이 크로켓, 꽤 특이한.',
 '경교장-->김구 선생님이 광복 후 기거하시다가 돌아가신 곳입니다. 그당시 사용하던 가구 등 내부를 잘 복원해 놓았습니다. 역사의 현장이므로 방문할 필요가 있습니다',
 '경교장-->정동야행에 코스이기도 하지만 정동에서 길을 건너야 하고 강북삼성병원 갔을 때 이런 곳에 문화재가 하면서 방문해 볼 만한 곳이다',
 '경교장-->강북 삼성병원에 자리잡은 옛 임시정부 김구선생님의 마지막장소.역사적으로 중요한곳임에도 지켜지지 못하고 간신히 경교장 건물 하나만 남은것이 너무나도 안타깝고 이것을 지켜내신분들이 참 대단하다 김구선생님 마지막 총맞으실때 입으셨던 피묻은 옷은 정말 너무 슬프다',
 '경교장-->백범 김 구 선생님이 계시던 곳인데, 지금은 강북삼성병원 내에 있어 병원 부속 건물로 오해 받을 수 있지만 독립건물입니다. 서울특별시 유형문화재 129호로 지정되어 있어 잊혀져가는 근현대사 유물로 안타까운 느낌이 드는 곳입니다.',
 '경교장-->삼성병원 내부에 경교장이 있습니다. 상해의 임시정부가 광복 후 사무실로 썼던 건물인데 병원 건물로 쓰던 것을 최대한 옛날 모습으로 복원한 곳입니다. 내부에는 당시의 모습을 재현하고 대한민국 독립과 임시정부, 그리고 김구 선생님에 대한 자료들이 전시되어 있습니다.근대의 건물을 구경한다는 차원에서 지나는 길에 들려볼만 합니다.',
 "탑골공원-->우리나라 최초의 도심 내 공원으로 1465년 세워졌다 연산군 때 폐사된 후 중종 때 건물이 모두 철거되어 빈터만 남은 곳을 19세기 말에 공원으로 설계한 것이다. 모든 것이 철거되고도 탑과 비만이 남아 있던 이곳은 특히 1919년 3월 1일의 독립선언으로 현대사에서 특히 중요한 장소가 되었다. 이 시대부터 '파고다 공원'으로 불려 왔지만 1992년 옛 지명에 따라 '탑골 공원'으로 개칭하였다. 석탑과 원각사비 외에도 3·1운동 부조, 의암 손병희 동상, 독립 선언문 등이 있다. 근래 들어 노인들의 휴식처로 많이 사용되어 왔지만 문화재들의 중요성으로 재발견되고 있는 곳이기도 하다.",
 '탑골공원-->인사동을 찾아가다 우연찮게 가게된 탑골공원.텔레비전에서 보던 것처럼 어르신들이 많이 보였음. 하지만 노숙하는 분들도 많아 아이를 데려가기 꺼려짐.',
 '탑골공원-->탑공원, 탑동공원, 파고다공원이라고도 하며,1991년 10월 25일 사적 제354호로 지정되었다. 고려시대에는 흥복사가, 조선시대 전기(1464)에는 원각사가 그 자리에 있었는데, 연산군이 원각사를 폐사하고 중종 때 건물이 모두 철거되면서 빈터만 남아 있다가, 1897년(광무 1) 영국인 고문 J.M.브라운이 설계하여 공원으로 꾸며졌다. 독립선언서가 낭독되었던 팔각정을 중심으로,원각사지 10층석탑(국보 2), 원각사비(보물 3), 앙부일구(해시계) 받침돌 등의 문화재와, 1980년에 제작, 건립한 3·1운동기념탑, 3·1운동벽화, 의암 손병희 동상(1966년 건립), 한용운 기념비(1967년 건립) 등이 있다.1992년 이곳의 옛 지명을 따라 파고다공원에서 탑골공원으로 개칭하였다.',
 '탑골공원-->먼가 십원에 그려진 곳이라 생각해서 쉽게 볼수 있지 않을까 오래됐다고 무시하는 느낌이 들어 한번 가보았다. 마치 탑은 산소마스크를 씌운듯 힘들게 보존된거같다. 그래도 한번은 오고 봐서 다행인거같다.',
 '탑골공원-->역사책에 나오는 역사적인 장소이죠!!!  공원안에 국보 원각사지 10층 석탑이 있어요~~ 한번 들려보길 바래요!!',
 '탑골공원-->탑골공원의 이미지는 어르신들만 많이 있는 곳이라고 생각하고 여태까지 안 갔었는데 원각사지10층석탑을 보기 위해 지나가다가 들렀다. 탑이 유리 안에 있어서 좀 답답하기는 하였지만, 이 곳에서 독립선언서를 낭독하였다는 것과 민족대표33인이 모두 한 목소리를 내었던 곳이라고 생각하니 마음이 짠해지기도 하였다.',
 '탑골공원-->종로에 위치한 탑골공원. 그런데 평일 낮에는 어르신들이 많이 몰리는 곳이다보니 젊은 층이 여행으로 가기에는 그다지 추천하고픈 곳은 아니다.',
 '탑골공원-->흔히들 어르신들이 많이 오시는 장소로만 알고 있었는데, 우연히 들어가 본 후, 원각사집 10층 석탑도 보고 오래된 나무도 보고난 뒤 인식이 바뀌었음.그냥 밖에서만 지나치지 말고 잠시라도 들러서 안쪽에 숨어있는 역사적 가치가 있는 것들을 즐기고 오길 추천함',
 '탑골공원-->주변을 뱅 돌아가본적은 많았지만 막상 들어가본적은 없었는데, 종로에 갈 때 한번쯤 가서 파고다를 가볼 필요가 있었다고 생각했다. 늦은 밤에 가는 것은 역시 위험.',
 '탑골공원-->종각역에서 종묘로 향하는 도중에 있습니다.할아버지와 할머니들이 많이 모여있어요.솔직히 일본인의 입장에서 보면 살기 힘든 장소지만,서울에 사는 노인분들의 생활을 엿볼 수가 있으니어차피 지나가는 곳이라면 발길을 멈추고 한번 보고 가는 것은 어떨까요?',
 '대학로-->우연히 만난(어디로 가는길을 묻기도 전에 궁금하신게 있으세요 ? 하며 다가서는) 어느 학생에게서도 풍기는 있는 분위기. 학교교정과 모든것에 있어보이는 품위 ! 정말 이대 이대 왜그런지.. 그리고 "나 이대나온 여자야"  어느 영화대사처럼 좋은 느낌같고 갑니다. 교정 여기저기에 토론하는 학생들의 열정도 !',
 '대학로-->간만에 가니까 이대 ecc안 푸드코트가 새로운 식당이름으로 바뀌었더라고요....근데 가격이 엄청 비싸졌어요..ㅜㅜ 이국식당에서 제일 싼 경향식 돈가스가 8900원인가 했어요. 셀프인데도 말이죠. 그렇다고 맛이나 구성이 변한 거 아니예요  오히려 반찬코너에 김치 있었는데 사라졌어요...ㅠㅠ 학교 안인데 너무한 거 같아요. ㅜㅜ',
 '대학로-->한국에서 아름답기로는 손꼽히는 대학교입니다. 다만, 관광객들이 몰려 학생들이 피해를 보고 있다고 하니 되도록이면 조용히 산책하고 오는 게 좋습니다. 옆의 연세대학교 역시 이화여대만큼이나 아름답습니다. 같이 가보는 걸 추천.',
 '대학로-->서울시 대학교들이 조경이 다 잘되어 있긴 하지만 이화여자대학교도 산책하기에 참 좋은 곳이라는 생각이 든다. 접근성도 좋아서 찾아가기 쉽다.',
 '대학로-->이곳이 학교인지 중국인 관광객이 다니는 명소인지 구분이 어려운 곳입니다. 그들이 없다면 한번쯤 이화여대 재학생들에게 피해를 주지 않는 선에서 방문해 볼 만한 곳입니다.',
 '대학로-->정말 궁금해서 구경하러 가봤는데 예상보다 예쁜 캠퍼스에 놀랐고 산책하고 쉬기에 너무 좋겠다는 생각이 들었습니다. 실제로 그런 사람들도 많아 보였어요.',
 '대학로-->건물 중에 ECC 진짜 멋집니다 역시 명문대라 그런지 학생들 다 포스가 납니다또한 열람실이 있는 출입구는 학생들의 학업 분위기를 위해 외부인 출입금지더군요 ㄷ ㄷ 역시 클라쓰..근처에 맛집도 많아요!일 차원 자주 가는데 엘수에뇨 맛있습니자 ㅋㅋ',
 '대학로-->한국 뿐만 아니라 전세계 중 가장 큰 여성 종합대학 입니다. 캠퍼스도 아름다워서 한번쯤은 가볼 만 한 곳입니다. 중국인 관광객이 많은게 다소 흠입니다.',
 '대학로-->ECC 건물은  건축적으로 매우 아름답고 홍해가 갈라지는 기적을 건축적으로 표현해 놓았다. 조경이 아름다워 산책하기도 사진을 찍기에도 좋다.',
 '대학로-->대학교에서 외국인 방문객을 볼 수 있었네요. 여대여서 갈일이 없었지만,  새 건물과 오래건물이 마치 서울처럼 이리저리 섞여 있네요.',
 '인왕산 선바위와 국사당-->서울의 조망권1. 무무대 이 전망대의 이름은 무무대이며 인왕산 자락길에 있다. 인왕산 길에 올라가기 전 종로도서관을 들를 수 있다. 도서관은 도보 여행길에 유용한 베이스 역할을 할 수 있다. 문화와 레저가 함께하는 여가 생활은 내가 좋아하는 조합이다. 무무대 가는 길은 어렵지 않다. 인왕산 자락길이 잘 닦여있다. 그냥 인왕산 정상가는 길에도 좋은 전망권이 있다. 인왕산은 나름 보물 같은 장소라고 생각한다. 인왕산 자락길은 부암동하고도 연결이 될 수 있다. 청운문학도서관과 윤동주 문학관은 한번 가보고 싶은 곳이다.2. 전동 전망대 정동 전망대는 서울시청 무교동별관 13층에 있다. 커피샵이 같이 있고 덕수궁 내부가 보이는 유명한 곳이다. 서울시청, 서울도서관, 덕수궁, 정동 등 산책하고 여가 시간을 보내기에 좋다.3. 대한민국역사박물관 전망대 경복궁 방향이 보이는 전망대이다. 역시 멋지다4. 낙산공원 동대문에 위치한 한양도성 박물관을 지나 낙산 공원으로 한양 도성길이 이어져 있으며 역시 멋진 조망을 볼 수 있는 지점들이 있다.5. 세운상가 전망대 종묘를 지나 시원한 조망을 갖고 있으며 뒤편으로 남산도 보인다.',
 '인왕산 선바위와 국사당-->산을 거의 가보지 않아 하이킹엔 잼병인데 인왕산은 초심자들도 쉽게 정상까지 오를 수 있게 코스가 쉽습니다.정상 2/3 지점까지는 거의 계단이라 쉽게 올라갔고 나머지도 그리 어렵지 않았어요.사직공원쪽에서 시작해 부암동쪽으로 내려와 맛있게 점심과 디저트를 하면 딱 좋아요.',
 '인왕산 선바위와 국사당-->서울 인왕산은 서울을 대표하는 주산으로 광화문에서 서쪽으로 보면 제법 웅장한 모습으로 서울을 지켜주고 있습니다. 바로 옆으로 북악산과 뒷쪽의 북한산과 더불어 서울 시민의 사랑을 받고 있는 아름다운 산입니다.',
 '인왕산 선바위와 국사당-->오늘 정말 바람이 많이 불고 추웠는데 간만에 미세먼지가 없어 인왕산에서 서울 경치를 보러 올라갔어요. 선바위는 여전히 멋있고 더 올라가니 경치를 잘 볼 수는 있었는데 바람이 너무 쎄게 불어서 죽는줄 알았어요. ㅜㅜ 바람이 강한 날은 안 올라가는 게 나을듯 합니다.',
 '인왕산 선바위와 국사당-->인왕산. 돌로 되어 있는 걷는 부분이 많아서 험난해 보였지만. 일반 등산 장비를 갖추지 않았어도 수월한 등산 이었고 재미있는 등산 이었다. 입출구가 여러곳 있고 그래도 평일 등산 이었지만 한적했다 ~! 전망대가 중간 중간에 많아서 좋았다',
 '인왕산 선바위와 국사당-->오르면 경복궁 등 서울 도심이 한눈에 보인다. 계단이 많아 힘이드는 산이다. 군사 구역으로 사진 촬영을 할 수 없는 구간이 있다.',
 '인왕산 선바위와 국사당-->경교장에서 창의문으로 내려오는 구간은 거리도 짧아서 가볍고 편하게 다녀올 수 있습니다. 청와대 뒷산이라 경찰들이 곳곳에 있어 혼자서 다녀오기에도 안전하고 좋습니다. 서울 풍경이 한 눈에 보이고 부암동으로 하산하면 맛집도 많은 건 덤입니다.',
 '인왕산 선바위와 국사당-->서울 성곽길을 따라 걷다보면 어느새 인왕산 자락에 올라있다.서울 한 가운데였는데 어느 새 싶은 산속에 들어온 느낌이다.',
 '인왕산 선바위와 국사당-->청와대를 끼고 옛 성곽이 둘러져있는 산입니다예전에는 출입이 자유롭지 않았던 시절도 있지만 지금은 동네주민 서울시민 모두가 편하게 걸을수 있고 맑은 공기를 느낄수있고 서울의 아름다운 모습을 볼수있는곳입니다 잔잔한 걷는길부터 성곽을 끼고 정상에 오를수도 있고 다양한 루트의 길이 관리가 잘 되어있습니다',
 '인왕산 선바위와 국사당-->개인적으로 서울에서 북한산이랑 인왕산 너무 좋다.바위산이라서 느낌도 독특하고 서울 중심에 이런 곳이 있는게 너무좋고보존을 잘해야된다 생각함',
 '종묘-->고자넉하고 좋았어요. 종묘 주변에는 현대화된 모던 한옥들,근대시대 건물들등..다양한 상가들을 보는 재미도 있었구요. 다만 현재 공사중이라 아쉬운 점도 있었습니다.',
 '종묘-->눈 덮인 겨울에 방문한 적이 있는데 여름과 같은 다른 계절보다 더 아름답고 그때만의 분위기가 참 좋았다. 비록 발은 시려워서 동동거렸지만.',
 '종묘-->5월 5일에 종묘대제를 보러 갔다왔어요. 2시부터 시작인데 정전에 들어가기 위해 한시간 이상 줄을 서야 했어요. 간신히 들어가서 잘 봤는데 안타까웠던 점은 전광판에도 영어설명이 없어서 외국인들이 잠깐 들어왔다가 그냥 가버리는 모습을 발견한 점이에요.',
 '종묘-->서울에 방문하고 문화를 보고 싶은 관광객이나 사람들에게 추천하고 싶습니다 종종 여러 행사도 진행하고 있어서 유익합니다',
 '종묘-->단풍이 드는 계절은 여기와 너무 어울리죠.한국 전통 건축을 보기 위해서는 필수 코스에요.하지만 이 곳에 가서는 정숙하시기 바랍니다.조선 왕들의 영령들이 잠드신 곳이니까요.',
 '종묘-->넓고 한국의 역사적인 중요지이므로 반드시 가보아야할 곳이지만 그늘이 부족하므로 여름에는 돌아다니기가 힘겨움. 최소한 양산은 들고 가야할 듯. 사극에서 보이는 장소를 직접 보며 돌들의 의미까지 알아가는 재미가 있음.',
 "종묘-->집 근처에 있으면서도 '에이 뭐 볼 거 있겠어' 하고 안 가다가 시간이 남는 날 우연히 갔다. 더 일찍 방문하지 않은 것을 후회했다. 세상에 입장료 천원에 이렇게 볼 것이 많은 문화유산이 없다.우리궁궐지킴이에서 진행하는 시간관람제에 따라 꼭 봐야한다. 둘러보다 궁금증이 생길 법한 것을 모두 자세하게 알려준다.",
 '종묘-->서울에 온 관광객이라면 반드시 창덕궁을 봐야 하지만, 서울에 온 여행자라면 반드시 종묘를 봐야 한다.종묘 정전은 전 세계 어느 랜드마크와 비교해도 부족함이 없는, 한민족 최고의 건축이라 확신한다.개인적으로 종묘를 보기 가장 좋은 날과 장소는 가을날 해 질 무렵 종묘 정전의 동쪽 문이었다. 석양을 마주하며 오른편의 종묘를 바라봤을 때 느꼈던 그 전율은 결코 잊을 수 없다.',
 '종묘-->종묘는 신주를 모시고 제사를 봉행하는 곳으로 고즈넉하고 아름다웠다. 데이트코스로 연인들도 많았다.',
 '종묘-->서울 살면서 최근에 종묘를 가본 것을 후회합니다. 종묘로 가는 길이 다소 험하고 나이드신 어르신들이 많이 모여계신 동네이기는 하지만, 한 번쯤 가볼만 합니다. 종묘가 생각보다 넓고 크고 공원 같더군요!',
 '서울역사박물관-->볼거리가 많은 곳',
 '서울역사박물관-->가볼곳중 하나',
 '서울역사박물관-->한번쯤 가볼만한',
 '서울역사박물관-->핀란드 친구들의 자취를 따라서',
 '서울역사박물관-->서울 역사 박물관',
 '서울역사박물관-->도심 휴양지',
 '서울역사박물관-->서울에 정보가 가득한 그곳',
 '서울역사박물관-->아이 있는 분들에게 강추',
 '서울역사박물관-->작지만알찬박물관',
 '서울역사박물관-->잘 구성된 박물관',
 '창경궁-->추후 공지가 있을 때까지 일시 휴업',
 '창경궁-->보는 것도 많고 힐링 됐어요 날씨 좋은 날에 꼭 한 번 가보세요 요즘 힘든 일도 많았는데 마음이 안정되구 넘 좋았네요 하하하하하',
 '창경궁-->주차는 인근 서울대병원에 하고, 미리 예약한 야간투어를 시작했습니다. 2년전 덕수궁, 경복궁은 야경투어를 통해 재미있고, 의미있게 관람한 경험이 있어 창경궁 궁투어를 예정하고 있었으나 코로나19로인해 2년만에야 하게 되었습니다.해설사님의 설명으로 각각의 전각과 역사의 배경이 된 곳들을 보게되었습니다.창경궁의 야경은 덕수궁과 경복궁에 비해 화려하지는 않습니다. 하지만 그 아름다움은 결코 되지지 않습니다.창경궁관람은 꼭 해설사를 동반한 가이드 투어를 추천합니다.',
 '창경궁-->코로나19로 자의든 타의든 야외 생활이 제한되는 상황에서 역사 공부와 함께 산책을 할 수 있는 멋진 곳. 게다가 아름다운 가을의 꽃, 꽃무릇도 만날 수 있는 도심속의 휴식처.창경궁은 서울의 5대 궁궐 중 3번째로 지어진 조선시대 궁궐로 창덕궁과 함께 동궐이라 불렀다. 조선이 개국한 이래 안정기에 접어들면서 왕실 가족도 늘어났다. 성종 때 세 분의 대비(세조 비 정희왕후, 예종 비 안순왕후, 덕종 비 소혜왕후)를 함께 모시고자 창덕궁 곁에 마련한 궁궐이 창경궁이다. 다른 궁궐과 달리 왕실 생활 공간의 확장을 목적으로 태종이 상왕으로 있으면서 지내던 수강궁을 중건하고 정전인 명정전, 정무를 보는 문정전 등을 지어 작은 규모이지만 궁궐의 격식을 갖추었다. 창경궁은 왕실 가족의 생활 공간으로 출발하였기에 내전이 외전에 비해 더 넓은 특징이 있다. 따라서 창경궁에는 왕들의 효심과 사랑, 왕과 세자의 갈등, 왕비와 후궁간의 암투 등 왕실 가족 사이에 일어난 이야기가 풍부하게 전해온다. 창경궁은 다른 궁궐과 마찬가지로 임진왜란 때 전소되어 광해군 8년(1616)에 복원되었다. 창경궁 최악의 치욕은 일제강점기 전각들을 헐어내고 그 자리에 동물원과 식물원을 만들어 1909년 일반에 개방한 것이다. 순조를 위로한다는 명목이었지만 일제의 속내는 우리 궁궐의 권위를 격하시키려는 데 있었다. 광복 이후에도 창경궁은 창경원으로 동물원이자 행락지 신세를 벗어나지 못하다가 1980년대 창경궁으로 복원하면서 그 치욕에서 벗어날 수 있었다. 평소에도 다른 궁궐보다 관람객이 적어 여유로운 창경궁이 코로나19로 더욱 더 한가로웠다. 문정문 보수 공사로 일부 공간을 관람할 수 없는 아쉬움이 조금 있었지만, 가을의 화려한 꽃, 꽃무릇을 자생화단에서 만난 것은 생각하지 못한 행운이었다.',
 '창경궁-->궁궐이라는것이 옛날 우리조상들의 삶, 왕과 가족들의 생활을유추해볼수 있는곳이 아닌가 생각한다.그것을 통해서 우리삶을 재조명해보기도 한다.',

In [82]:
data=pd.DataFrame({'리뷰제목':titles,'내용':contents})
data

,리뷰제목,내용
0,경복궁-->대한민국의 역사,경복궁-->대한민국의 역사가 잠들어 있는 곳. 서울을 방문했다면 꼭 방문해야 되는 ...
1,경복궁-->국민이 공감하는 장소,경복궁-->경복궁은 국민들이 자주 찾는곳으로 작성자는 주말에 자주 가족들과 방문하고...
2,경복궁-->산책하기 좋은 경복궁,경복궁-->날씨 좋은 날 종종 산책하러 경복궁에 가는데 마음이 편온해지는 기분이라고...
3,경복궁-->Good,경복궁-->Goooooood 다 좋습니다 다음에 또 오고 싶네요 근처 관광지도많고 ...
4,경복궁-->가족단위로 방문하기 좋은곳,경복궁-->요새 더더욱 코로나로 인해 사람 방문이 적음. 두자녀 동반시 성인 입장무...
...,...,...
6174,제주 감귤박물관-->생각보다 사람이 없네요.,제주 감귤박물관-->제주 감규의 역사에 대해 알수 있습니다.세게 감귤 전시과 및 열...
6175,"제주 감귤박물관-->한국 감귤의 역사, 세계 감귤 전시관,열대 식물 온실, 족욕체험...",제주 감귤박물관-->잘 만들어 놓았는데 관광객들이 오가기엔 조금 애매한가봅니다.서귀...
6176,제주 감귤박물관-->제주도의 역사에대해 나와있습니다.,제주 감귤박물관-->감귤의 제배 과정 효능 방법등에 대해 나와 있고 종류또한 다양...
6177,제주 감귤박물관-->감귤박물관,제주 감귤박물관-->생각보다 아주 크게 있음. 감귤을 수확하는 모든 과정을 볼 수 ...
6178,제주 감귤박물관-->신나는 감귤 축제,제주 감귤박물관-->감귤 축제 기간에 방문하니 감귤 수확 체험이 평소 6000원이던...

In [100]:
data.drop

In [96]:
data.to_csv('여행지 리뷰 1차.csv',encoding='utf-8-sig',index=False)

In [98]:
data2=pd.DataFrame(reviews['리뷰제목'].str.split('-->').tolist(),columns=['장소명','리뷰제목'])
data2

TypeError: list indices must be integers or slices, not str

In [101]:
data

,리뷰제목,내용,관광지
0,경복궁-->대한민국의 역사,경복궁-->대한민국의 역사가 잠들어 있는 곳. 서울을 방문했다면 꼭 방문해야 되는 ...,제주 감귤박물관-->신나는 감귤 축제
1,경복궁-->국민이 공감하는 장소,경복궁-->경복궁은 국민들이 자주 찾는곳으로 작성자는 주말에 자주 가족들과 방문하고...,제주 감귤박물관-->신나는 감귤 축제
2,경복궁-->산책하기 좋은 경복궁,경복궁-->날씨 좋은 날 종종 산책하러 경복궁에 가는데 마음이 편온해지는 기분이라고...,제주 감귤박물관-->신나는 감귤 축제
3,경복궁-->Good,경복궁-->Goooooood 다 좋습니다 다음에 또 오고 싶네요 근처 관광지도많고 ...,제주 감귤박물관-->신나는 감귤 축제
4,경복궁-->가족단위로 방문하기 좋은곳,경복궁-->요새 더더욱 코로나로 인해 사람 방문이 적음. 두자녀 동반시 성인 입장무...,제주 감귤박물관-->신나는 감귤 축제
...,...,...,...
6174,제주 감귤박물관-->생각보다 사람이 없네요.,제주 감귤박물관-->제주 감규의 역사에 대해 알수 있습니다.세게 감귤 전시과 및 열...,제주 감귤박물관-->신나는 감귤 축제
6175,"제주 감귤박물관-->한국 감귤의 역사, 세계 감귤 전시관,열대 식물 온실, 족욕체험...",제주 감귤박물관-->잘 만들어 놓았는데 관광객들이 오가기엔 조금 애매한가봅니다.서귀...,제주 감귤박물관-->신나는 감귤 축제
6176,제주 감귤박물관-->제주도의 역사에대해 나와있습니다.,제주 감귤박물관-->감귤의 제배 과정 효능 방법등에 대해 나와 있고 종류또한 다양...,제주 감귤박물관-->신나는 감귤 축제
6177,제주 감귤박물관-->감귤박물관,제주 감귤박물관-->생각보다 아주 크게 있음. 감귤을 수확하는 모든 과정을 볼 수 ...,제주 감귤박물관-->신나는 감귤 축제
6178,제주 감귤박물관-->신나는 감귤 축제,제주 감귤박물관-->감귤 축제 기간에 방문하니 감귤 수확 체험이 평소 6000원이던...,제주 감귤박물관-->신나는 감귤 축제

In [104]:
data['관광지']=data.리뷰제목.str.split('-->').str[0]

In [106]:
data=data[['관광지','리뷰제목','내용']]
data

,관광지,리뷰제목,내용
0,경복궁,경복궁-->대한민국의 역사,경복궁-->대한민국의 역사가 잠들어 있는 곳. 서울을 방문했다면 꼭 방문해야 되는 ...
1,경복궁,경복궁-->국민이 공감하는 장소,경복궁-->경복궁은 국민들이 자주 찾는곳으로 작성자는 주말에 자주 가족들과 방문하고...
2,경복궁,경복궁-->산책하기 좋은 경복궁,경복궁-->날씨 좋은 날 종종 산책하러 경복궁에 가는데 마음이 편온해지는 기분이라고...
3,경복궁,경복궁-->Good,경복궁-->Goooooood 다 좋습니다 다음에 또 오고 싶네요 근처 관광지도많고 ...
4,경복궁,경복궁-->가족단위로 방문하기 좋은곳,경복궁-->요새 더더욱 코로나로 인해 사람 방문이 적음. 두자녀 동반시 성인 입장무...
...,...,...,...
6174,제주 감귤박물관,제주 감귤박물관-->생각보다 사람이 없네요.,제주 감귤박물관-->제주 감규의 역사에 대해 알수 있습니다.세게 감귤 전시과 및 열...
6175,제주 감귤박물관,"제주 감귤박물관-->한국 감귤의 역사, 세계 감귤 전시관,열대 식물 온실, 족욕체험...",제주 감귤박물관-->잘 만들어 놓았는데 관광객들이 오가기엔 조금 애매한가봅니다.서귀...
6176,제주 감귤박물관,제주 감귤박물관-->제주도의 역사에대해 나와있습니다.,제주 감귤박물관-->감귤의 제배 과정 효능 방법등에 대해 나와 있고 종류또한 다양...
6177,제주 감귤박물관,제주 감귤박물관-->감귤박물관,제주 감귤박물관-->생각보다 아주 크게 있음. 감귤을 수확하는 모든 과정을 볼 수 ...
6178,제주 감귤박물관,제주 감귤박물관-->신나는 감귤 축제,제주 감귤박물관-->감귤 축제 기간에 방문하니 감귤 수확 체험이 평소 6000원이던...

In [107]:
data['리뷰제목']=data.리뷰제목.str.split('-->').str[1]
data

,관광지,리뷰제목,내용
0,경복궁,대한민국의 역사,경복궁-->대한민국의 역사가 잠들어 있는 곳. 서울을 방문했다면 꼭 방문해야 되는 ...
1,경복궁,국민이 공감하는 장소,경복궁-->경복궁은 국민들이 자주 찾는곳으로 작성자는 주말에 자주 가족들과 방문하고...
2,경복궁,산책하기 좋은 경복궁,경복궁-->날씨 좋은 날 종종 산책하러 경복궁에 가는데 마음이 편온해지는 기분이라고...
3,경복궁,Good,경복궁-->Goooooood 다 좋습니다 다음에 또 오고 싶네요 근처 관광지도많고 ...
4,경복궁,가족단위로 방문하기 좋은곳,경복궁-->요새 더더욱 코로나로 인해 사람 방문이 적음. 두자녀 동반시 성인 입장무...
...,...,...,...
6174,제주 감귤박물관,생각보다 사람이 없네요.,제주 감귤박물관-->제주 감규의 역사에 대해 알수 있습니다.세게 감귤 전시과 및 열...
6175,제주 감귤박물관,"한국 감귤의 역사, 세계 감귤 전시관,열대 식물 온실, 족욕체험도 무료",제주 감귤박물관-->잘 만들어 놓았는데 관광객들이 오가기엔 조금 애매한가봅니다.서귀...
6176,제주 감귤박물관,제주도의 역사에대해 나와있습니다.,제주 감귤박물관-->감귤의 제배 과정 효능 방법등에 대해 나와 있고 종류또한 다양...
6177,제주 감귤박물관,감귤박물관,제주 감귤박물관-->생각보다 아주 크게 있음. 감귤을 수확하는 모든 과정을 볼 수 ...
6178,제주 감귤박물관,신나는 감귤 축제,제주 감귤박물관-->감귤 축제 기간에 방문하니 감귤 수확 체험이 평소 6000원이던...

In [108]:
data['내용']=data.내용.str.split('-->').str[1]

In [109]:
data

,관광지,리뷰제목,내용
0,경복궁,대한민국의 역사,대한민국의 역사가 잠들어 있는 곳. 서울을 방문했다면 꼭 방문해야 되는 곳. 경복궁...
1,경복궁,국민이 공감하는 장소,경복궁은 국민들이 자주 찾는곳으로 작성자는 주말에 자주 가족들과 방문하고 있음.특히...
2,경복궁,산책하기 좋은 경복궁,날씨 좋은 날 종종 산책하러 경복궁에 가는데 마음이 편온해지는 기분이라고 할까요? ...
3,경복궁,Good,Goooooood 다 좋습니다 다음에 또 오고 싶네요 근처 관광지도많고 먹을거리도많...
4,경복궁,가족단위로 방문하기 좋은곳,요새 더더욱 코로나로 인해 사람 방문이 적음. 두자녀 동반시 성인 입장무료. 지금 ...
...,...,...,...
6174,제주 감귤박물관,생각보다 사람이 없네요.,"제주 감규의 역사에 대해 알수 있습니다.세게 감귤 전시과 및 열대 식물 온실, 족욕..."
6175,제주 감귤박물관,"한국 감귤의 역사, 세계 감귤 전시관,열대 식물 온실, 족욕체험도 무료",잘 만들어 놓았는데 관광객들이 오가기엔 조금 애매한가봅니다.서귀포시 직영관광지인 ...
6176,제주 감귤박물관,제주도의 역사에대해 나와있습니다.,감귤의 제배 과정 효능 방법등에 대해 나와 있고 종류또한 다양합니다. 아이들과 방...
6177,제주 감귤박물관,감귤박물관,생각보다 아주 크게 있음. 감귤을 수확하는 모든 과정을 볼 수 있으며 체험도 할 수...
6178,제주 감귤박물관,신나는 감귤 축제,감귤 축제 기간에 방문하니 감귤 수확 체험이 평소 6000원이던 것이 3000원으로...

In [110]:
data.to_csv('여행지 리뷰 1차.csv',encoding='utf-8-sig',index=False)

### 해야 할 것
- 여행지 리뷰 중 내용 없는 것 찾기
- 검색해서 제일 첫번째꺼로 들어가서 리뷰 가져오게 구조가 짜져 있는데, 잘못된 관광지명 찾아내기 (예상 한 350개 까야될듯)