In [1]:
import pandas as pd
import numpy as np
from selenium import webdriver
import time
from bs4 import BeautifulSoup
import requests
from selenium.webdriver.common.keys import Keys
import urllib
from selenium.webdriver import ActionChains
import warnings
warnings.filterwarnings(action='ignore')

In [6]:
df_new = pd.read_csv('./data/다른 칸 존재.csv')
df_new

                    여행지 일치여부  다른 칸에 존재여부
0                 월드컵공원    X           3
1     대한민국 국회의사당과 헌정기념관    X           3
2             암사동 선사주거지    X           2
3                    화성    X           2
4               안양 예술공원    X           1
5          부천 활박물관과 궁도장    X           1
6                   대부도    X           2
7          국립현대미술관(과천관)    X           2
8               파주 프로방스    X           1
9                  설봉공원    X           0
10               세계도자센터    X           0
11                  청룡사    X           0
12                 융ㆍ건릉    X           1
13                  용궁사    X           6
14                  산사원    X           3
15             운악산과 현등사    X           0
16         자라섬 국제재즈페스티벌    X           0
17                 자유공원    X           1
18                  정암사    X           0
19                통일전망대    X           1
20                  탄금대    X           3
21                독립기념관    X           2
22                  공산성    X           2
23                 무령왕릉    X           2
24                충청수영성    X           2
25       천주교 대전교구 공세리성당    X           2
26            그림이 있는 정원    X           5
27             십리포 해수욕장    X           1
28            팜카밀레 허브농원    X           2
29        천주교 전주교구 전동성당    X           2
30                  한벽당    X           6
31                  대둔산    X           4
32  무주 구천동계곡 방화동 가족휴양촌,    X           2
33             마이산 도립공원    X           5
34           순천 드라마세트장     X           1
35              순천만 갈대밭    X           2
36            지리산 산수유마을    X           3
37          벌교 홍교, 대한다원    X           8
38                 봇재다원    X           8
39                  용천사    X           2
40                   계림    X           2
41                  금오산    X           2
42                 빙계계곡    X           2
43              군위 삼존석굴    X           2
44                주남저수지    X           2
45                  청곡사    X           2
46                 달아공원    X           6
47              항공우주박물관    X           3
48               창녕 석빙고    X           3
49              고성 탈박물관    X           2
50                  임진성    X           2
51                다랑쉬오름    X           2
52                  약천사    X           2
53                제주 올레    X           2
54                천제연폭포    X           3

In [7]:
df_new = df_new.astype({'다른 칸에 존재여부': 'int'})

In [10]:
df_2 = df_new[df_new['다른 칸에 존재여부']==2].reset_index(drop = True)
df_3 = df_new[df_new['다른 칸에 존재여부']==3].reset_index(drop = True)
df_4 = df_new[df_new['다른 칸에 존재여부']==4].reset_index(drop = True)
df_5 = df_new[df_new['다른 칸에 존재여부']==5].reset_index(drop = True)
df_6 = df_new[df_new['다른 칸에 존재여부']==6].reset_index(drop = True)
df_8 = df_new[df_new['다른 칸에 존재여부'] == 8].reset_index(drop = True)
df_one = df_new[df_new['다른 칸에 존재여부'] == 1].reset_index(drop = True)

In [12]:
print(len(df_2))
print(len(df_3))
print(len(df_4))
print(len(df_5))
print(len(df_6))
print(len(df_8))
print(len(df_one))

25
8
1
2
3
2
8

In [70]:
options=webdriver.ChromeOptions()
options.add_argument('user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36')
options.add_experimental_option("excludeSwitches", ["enable-logging"])


driver=webdriver.Chrome()
url='https://www.tripadvisor.co.kr/'

category=[]
score = []
for i in range(len(df_2)):
    driver.get(url)
    search=df_2.여행지[i]
    driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(search)
    driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(Keys.ENTER)
    driver.switch_to.window(driver.window_handles[-1])
    time.sleep(2)
    try: 
        driver.find_element_by_css_selector('#BODY_BLOCK_JQUERY_REFLOW > div.page > div > div.ui_container.main_wrap > div > div > div > div > div.content_column.ui_column.is-9-desktop.is-12-tablet.is-12-mobile > div > div.ui_columns.sections_wrapper > div > div.prw_rup.prw_search_search_results.ajax-content > div > div.main_content.ui_column.is-12 > div > div:nth-child(2) > div > div > div:nth-child(2) > div > div > div > div.ui_column.is-9-desktop.is-8-mobile.is-9-tablet.content-block-column > div').click()

        driver.switch_to.window(driver.window_handles[-1])
        soup=BeautifulSoup(driver.page_source,'html.parser')
        mydata=soup.find('div','pIRBV _T KRIav')
        category.append(search + '-->' + mydata.get_text())
        mydata2=soup.find('div','WlYyy cPsXC fksET cMKSg')
        score.append(search + '-->' + mydata2.get_text())
        driver.switch_to.window(driver.window_handles[-1])
        driver.close()
        driver.switch_to.window(driver.window_handles[0])
        driver.back()
        time.sleep(1)
    except:
        category.append('결과 없음')
        score.append('결과 없음')

In [73]:
options=webdriver.ChromeOptions()
options.add_argument('user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36')
options.add_experimental_option("excludeSwitches", ["enable-logging"])


driver=webdriver.Chrome()
url='https://www.tripadvisor.co.kr/'

category3=[]
score3 = []
for i in range(len(df_3)):
    driver.get(url)
    search=df_3.여행지[i]
    driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(search)
    driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(Keys.ENTER)
    driver.switch_to.window(driver.window_handles[-1])
    time.sleep(2)
    try: 
        driver.find_element_by_css_selector('#BODY_BLOCK_JQUERY_REFLOW > div.page > div > div.ui_container.main_wrap > div > div > div > div > div.content_column.ui_column.is-9-desktop.is-12-tablet.is-12-mobile > div > div.ui_columns.sections_wrapper > div > div.prw_rup.prw_search_search_results.ajax-content > div > div.main_content.ui_column.is-12 > div > div:nth-child(2) > div > div > div:nth-child(3) > div > div > div > div.ui_column.is-9-desktop.is-8-mobile.is-9-tablet.content-block-column > div').click()

        driver.switch_to.window(driver.window_handles[-1])
        soup=BeautifulSoup(driver.page_source,'html.parser')
        mydata=soup.find('div','pIRBV _T KRIav')
        category3.append(search + '-->' + mydata.get_text())
        mydata2=soup.find('div','WlYyy cPsXC fksET cMKSg')
        score3.append(search + '-->' + mydata2.get_text())
        driver.switch_to.window(driver.window_handles[-1])
        driver.close()
        driver.switch_to.window(driver.window_handles[0])
        driver.back()
        time.sleep(1)
    except:
        category3.append('결과 없음')
        score3.append('결과 없음')

In [76]:
options=webdriver.ChromeOptions()
options.add_argument('user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36')
options.add_experimental_option("excludeSwitches", ["enable-logging"])


driver=webdriver.Chrome()
url='https://www.tripadvisor.co.kr/'

category4=[]
score4 = []
for i in range(len(df_4)):
    driver.get(url)
    search=df_4.여행지[i]
    driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(search)
    driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(Keys.ENTER)
    driver.switch_to.window(driver.window_handles[-1])
    time.sleep(2)
    try:
        some_tag = driver.find_element_by_css_selector('#BODY_BLOCK_JQUERY_REFLOW > div.page > div > div.ui_container.main_wrap > div > div > div > div > div.content_column.ui_column.is-9-desktop.is-12-tablet.is-12-mobile > div > div.ui_columns.sections_wrapper > div > div.prw_rup.prw_search_search_results.ajax-content > div > div.main_content.ui_column.is-12 > div > div:nth-child(2) > div > div > div:nth-child(4) > div > div > div > div.ui_column.is-9-desktop.is-8-mobile.is-9-tablet.content-block-column > div')
        action = ActionChains(driver)
        action.move_to_element(some_tag).perform()
        driver.find_element_by_css_selector('#BODY_BLOCK_JQUERY_REFLOW > div.page > div > div.ui_container.main_wrap > div > div > div > div > div.content_column.ui_column.is-9-desktop.is-12-tablet.is-12-mobile > div > div.ui_columns.sections_wrapper > div > div.prw_rup.prw_search_search_results.ajax-content > div > div.main_content.ui_column.is-12 > div > div:nth-child(2) > div > div > div:nth-child(4) > div > div > div > div.ui_column.is-9-desktop.is-8-mobile.is-9-tablet.content-block-column > div').click()

        driver.switch_to.window(driver.window_handles[-1])
        soup=BeautifulSoup(driver.page_source,'html.parser')
        mydata=soup.find('div','pIRBV _T KRIav')
        category4.append(search + '-->' + mydata.get_text())
        mydata2=soup.find('div','WlYyy cPsXC fksET cMKSg')
        score4.append(search + '-->' + mydata2.get_text())
        driver.switch_to.window(driver.window_handles[-1])
        driver.close()
        driver.switch_to.window(driver.window_handles[0])
        driver.back()
        time.sleep(1)
    except:
        category4.append('결과 없음')
        score4.append('결과 없음')

In [79]:
options=webdriver.ChromeOptions()
options.add_argument('user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36')
options.add_experimental_option("excludeSwitches", ["enable-logging"])


driver=webdriver.Chrome()
url='https://www.tripadvisor.co.kr/'

category5=[]
score5 = []
for i in range(len(df_5)):
    driver.get(url)
    search=df_5.여행지[i]
    driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(search)
    driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(Keys.ENTER)
    driver.switch_to.window(driver.window_handles[-1])
    time.sleep(2)
    try: 
        some_tag = driver.find_element_by_css_selector('#BODY_BLOCK_JQUERY_REFLOW > div.page > div > div.ui_container.main_wrap > div > div > div > div > div.content_column.ui_column.is-9-desktop.is-12-tablet.is-12-mobile > div > div.ui_columns.sections_wrapper > div > div.prw_rup.prw_search_search_results.ajax-content > div > div.main_content.ui_column.is-12 > div > div:nth-child(2) > div > div > div:nth-child(5) > div > div > div > div.ui_column.is-9-desktop.is-8-mobile.is-9-tablet.content-block-column > div')
        action = ActionChains(driver)
        action.move_to_element(some_tag).perform()
        driver.find_element_by_css_selector('#BODY_BLOCK_JQUERY_REFLOW > div.page > div > div.ui_container.main_wrap > div > div > div > div > div.content_column.ui_column.is-9-desktop.is-12-tablet.is-12-mobile > div > div.ui_columns.sections_wrapper > div > div.prw_rup.prw_search_search_results.ajax-content > div > div.main_content.ui_column.is-12 > div > div:nth-child(2) > div > div > div:nth-child(5) > div > div > div > div.ui_column.is-9-desktop.is-8-mobile.is-9-tablet.content-block-column > div').click()

        driver.switch_to.window(driver.window_handles[-1])
        soup=BeautifulSoup(driver.page_source,'html.parser')
        mydata=soup.find('div','pIRBV _T KRIav')
        category5.append(search + '-->' + mydata.get_text())
        mydata2=soup.find('div','WlYyy cPsXC fksET cMKSg')
        score5.append(search + '-->' + mydata2.get_text())
        driver.switch_to.window(driver.window_handles[-1])
        driver.close()
        driver.switch_to.window(driver.window_handles[0])
        driver.back()
        time.sleep(1)
    except:
        category5.append('결과 없음')
        score5.append('결과 없음')

In [82]:
options=webdriver.ChromeOptions()
options.add_argument('user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36')
options.add_experimental_option("excludeSwitches", ["enable-logging"])


driver=webdriver.Chrome()
url='https://www.tripadvisor.co.kr/'

category6=[]
score6 = []
for i in range(len(df_6)):
    driver.get(url)
    search=df_6.여행지[i]
    driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(search)
    driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(Keys.ENTER)
    driver.switch_to.window(driver.window_handles[-1])
    time.sleep(2)
    try:
        some_tag = driver.find_element_by_css_selector('#BODY_BLOCK_JQUERY_REFLOW > div.page > div > div.ui_container.main_wrap > div > div > div > div > div.content_column.ui_column.is-9-desktop.is-12-tablet.is-12-mobile > div > div.ui_columns.sections_wrapper > div > div.prw_rup.prw_search_search_results.ajax-content > div > div.main_content.ui_column.is-12 > div > div:nth-child(2) > div > div > div:nth-child(7) > div > div > div > div.ui_column.is-9-desktop.is-8-mobile.is-9-tablet.content-block-column > div')
        action = ActionChains(driver)
        action.move_to_element(some_tag).perform()
        driver.find_element_by_css_selector('#BODY_BLOCK_JQUERY_REFLOW > div.page > div > div.ui_container.main_wrap > div > div > div > div > div.content_column.ui_column.is-9-desktop.is-12-tablet.is-12-mobile > div > div.ui_columns.sections_wrapper > div > div.prw_rup.prw_search_search_results.ajax-content > div > div.main_content.ui_column.is-12 > div > div:nth-child(2) > div > div > div:nth-child(7) > div > div > div > div.ui_column.is-9-desktop.is-8-mobile.is-9-tablet.content-block-column > div').click()

        driver.switch_to.window(driver.window_handles[-1])
        soup=BeautifulSoup(driver.page_source,'html.parser')
        mydata=soup.find('div','pIRBV _T KRIav')
        category6.append(search + '-->' + mydata.get_text())
        mydata2=soup.find('div','WlYyy cPsXC fksET cMKSg')
        score6.append(search + '-->' + mydata2.get_text())
        driver.switch_to.window(driver.window_handles[-1])
        driver.close()
        driver.switch_to.window(driver.window_handles[0])
        driver.back()
        time.sleep(1)
    except:
        category6.append('결과 없음')
        score6.append('결과 없음')

In [87]:
options=webdriver.ChromeOptions()
options.add_argument('user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36')
options.add_experimental_option("excludeSwitches", ["enable-logging"])


driver=webdriver.Chrome()
url='https://www.tripadvisor.co.kr/'

category8=[]
score8 = []
for i in range(len(df_8)):
    driver.get(url)
    search=df_8.여행지[i]
    driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(search)
    driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(Keys.ENTER)
    driver.switch_to.window(driver.window_handles[-1])
    time.sleep(2)
    try:
        
        some_tag = driver.find_element_by_css_selector('#BODY_BLOCK_JQUERY_REFLOW > div.page > div > div.ui_container.main_wrap > div > div > div > div > div.content_column.ui_column.is-9-desktop.is-12-tablet.is-12-mobile > div > div.ui_columns.sections_wrapper > div > div.prw_rup.prw_search_search_results.ajax-content > div > div.main_content.ui_column.is-12 > div > div:nth-child(2) > div > div > div:nth-child(9) > div > div > div > div.ui_column.is-9-desktop.is-8-mobile.is-9-tablet.content-block-column > div')
        action = ActionChains(driver)
        action.move_to_element(some_tag).perform()
        driver.find_element_by_css_selector('#BODY_BLOCK_JQUERY_REFLOW > div.page > div > div.ui_container.main_wrap > div > div > div > div > div.content_column.ui_column.is-9-desktop.is-12-tablet.is-12-mobile > div > div.ui_columns.sections_wrapper > div > div.prw_rup.prw_search_search_results.ajax-content > div > div.main_content.ui_column.is-12 > div > div:nth-child(2) > div > div > div:nth-child(9) > div > div > div > div.ui_column.is-9-desktop.is-8-mobile.is-9-tablet.content-block-column > div').click()

        driver.switch_to.window(driver.window_handles[-1])
        soup=BeautifulSoup(driver.page_source,'html.parser')
        mydata=soup.find('div','pIRBV _T KRIav')
        category8.append(search + '-->' + mydata.get_text())
        mydata2=soup.find('div','WlYyy cPsXC fksET cMKSg')
        score8.append(search + '-->' + mydata2.get_text())
        driver.switch_to.window(driver.window_handles[-1])
        driver.close()
        driver.switch_to.window(driver.window_handles[0])
        driver.back()
        time.sleep(1)
    except:
        category8.append('결과 없음')
        score8.append('결과 없음')

In [20]:
category = []
score = []

In [89]:
len(category8)

2

In [90]:
len(score)

25

In [88]:
category8

['벌교 홍교, 대한다원-->산림 • 농장', '결과 없음']

In [55]:
score6

['용궁사-->4.0', '한벽당-->4.0', '달아공원-->4.0']

In [91]:
category = category+category3+category4+category5+category6+category8
score = score+score3+score4+score5+score6+score8

In [92]:
len(category)

41

In [93]:
len(score)

41

In [110]:
df_one = df_new[df_new['다른 칸에 존재여부'] == 1].reset_index(drop = True)

In [102]:
options=webdriver.ChromeOptions()
options.add_argument('user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36')
options.add_experimental_option("excludeSwitches", ["enable-logging"])


driver=webdriver.Chrome()
url='https://www.tripadvisor.co.kr/'

reviews=[]
for i in range(len(df_1)):
    driver.get(url)
    search=df_1.여행지[i]
    driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(search)
    driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(Keys.ENTER)
    driver.switch_to.window(driver.window_handles[-1])
    time.sleep(2)
    try: 
        driver.find_element_by_css_selector('#BODY_BLOCK_JQUERY_REFLOW > div.page > div > div.ui_container.main_wrap > div > div > div > div > div.content_column.ui_column.is-9-desktop.is-12-tablet.is-12-mobile > div > div.ui_columns.sections_wrapper > div > div.prw_rup.prw_search_search_results.ajax-content > div > div.main_content.ui_column.is-12 > div > div:nth-child(2) > div > div > div:nth-child(1) > div > div > div > div.ui_column.is-9-desktop.is-8-mobile.is-9-tablet.content-block-column > div').click()

        driver.switch_to.window(driver.window_handles[-1])
        soup=BeautifulSoup(driver.page_source,'html.parser')
        mydata=soup.find_all('span','NejBf')
        for item in mydata:
            reviews.append(search + '-->' + item.get_text().strip())
        driver.switch_to.window(driver.window_handles[-1])
        driver.close()
        driver.switch_to.window(driver.window_handles[0])
        driver.back()
        time.sleep(1)
    except:
        pass

In [103]:
reviews

['안양 예술공원-->안양예술공원',
 '안양 예술공원-->갈때마다 새로운 프로그램과,유명한 아티스트들의작품들이 많다.볼거리도많고,빽빽히있는 식당과 카페도굿~이다.산책하기 좋은 둘레길과 흐르는 맑은 물,쓰레기만조심하고 안버리면 발담그고 라면먹는것도 가능하다고한다',
 '안양 예술공원-->어르신도 살방살방 다니기 높지 않은 공원길',
 '안양 예술공원-->안양시내에 이런 쉼터가 잇다는게 행복한 일이다. 주변의 사찰과 산책로가 그리고 주차장도 잘된편이며ㅡ 최근에는 공연도 많이 하고, 전시공간도 충분하다. 당연히 먹걸리도 많아 골라먹는 재미도 쏠쏠하다. 어르신도 살방살방 다니기 높지 않은 공원길과 특히 단풍도 그만이다.',
 '부천 활박물관과 궁도장-->다른 박물관과 같이 보기 좋아요',
 '부천 활박물관과 궁도장-->부천종합운동장 옆에 있습니다. 종합운동장에 수석발물관, 자기박물관이 있기 때문에 같이 보면 좋습니다. 활 박물관들은 생각보다 크지 않습니다. 박물관 관람 후 종합운동장이나 원미공원에 들리면 좋습니다',
 '부천 활박물관과 궁도장-->우연히 들른 활 박물관',
 '부천 활박물관과 궁도장-->부천에 있는지도 몰랐다가 우연하게 들르게된 활 박물관아담한 전시공간에 각종 활에 대한 자료와 역사등을 기록해 놓고 있어 아일랑 잠시 들르기 좋습니다.',
 '부천 활박물관과 궁도장-->아이들의 체험학습',
 '부천 활박물관과 궁도장-->부천에는 다양한 박물관이 있는데 종합운동장 근처에 위치해 있고 종합운동장에 있는 다른 박물관과 함께 투어하게되면 좀더 저렴한 가격에 표를 구매할 수 있습니다.여러가지 활들과 이름이 생각이 안나는데 큰 화살통들을 볼 수 있습니다. 아이들 체험학습으로 좋습니다.옆에 국궁장도 있습니다.',
 '부천 활박물관과 궁도장-->조금 작다고 해야하나...',
 '부천 활박물관과 궁도장-->규모가 좀 작은 편이에요. 진달래 동산 바로 옆에 있어서 박물관 셋트 쿠폰 끊어서 돌아다니면서 간곳인데 활박물관은 좀 어두운 편이구요 그래도 아기자기하게 꾸며 놓기는 했어요. 아이들과 가기에는 금세 끝나버려서 좀 실망할것 같기는 해요.',
 '부천 활박물관과 궁도장-->조금은 생소한 부천 활 박물관',
 '부천 활박물관과 궁도장-->부천에 생각보다 많은 박물관들이 있더라구요~여기도 그중하나인데 생각보다 소장유물들도 많고!아이들 교육으로도 좋을 것 같아요~~~ 전 인터넷에서 보구 특별 전시기간 맞춰서.. 양궁! 보러 갔는데~~ 정말 많은 종류의 활들이 있더라구요!',
 '부천 활박물관과 궁도장-->좋지만 더 기대되는 것',
 '부천 활박물관과 궁도장-->부천 축구장과 진달래 정원 사이에 위치한 부천 스타디움 (Bucheon Stadium) 지하철 7 호선에서 가까운 도보 거리에 있습니다. 이 박물관은 한국의 양궁 장비 및 유물과 다른 무기를 전시 한 아주 작은 박물관입니다. 활 만들기 및 fletching의 재미있는 비디오를 보여주는 극장 방도 있습니다. 불행히도 저에게는 박물관의 모든 것이 한국어로만되어 있습니다. . . 한국어를 말하거나 읽지 않으려면 한국인 친구 또는 여행 가이드를 데려 오십시오! 나는 박물관 뒤의 궁도 범위를 멀리 바라보고있는 30 분 미만의 끝에 끝내었고, 이웃의 "커피와 국수"카페에서 점심을 먹었다. 나는 한국의 올림픽 궁수들이 세계 최고라고 생각하는 박물관이 더 많을 것이라고 생각했지만 전반적으로 한 시간 동안 궁술에 관심이있는 사람에게는 좋은 경험이었다.',
 '파주 프로방스-->프로방스 주차장에서 주차하고 나서',
 '파주 프로방스-->들어가는 길이 조금 좁고 길게 느껴져서 들어가면 구석구석 준비되어 있는 주차라인! 한바뀌 구경하면서 돌다보면 보는 재미, 먹는 재미, 듣는 재미가 있습니다.',
 '파주 프로방스-->이뻐지만 너무 상업적',
 '파주 프로방스-->사람이 사는 마을이 아니라 상가들이 집결된 곳이다. 음식점, 빵집, 카페, 식물원, 옷가게, 잡화점 등. 주차장에 주차해야 하는데 1시간에 기본 2000원.',
 '파주 프로방스-->아기자기하고귀여움',
 '파주 프로방스-->몇년전보다 뭐가 많이 생겼네요사진찍을 스팟도 더 많고 상가도 많이 생기고 밤엔 전구들이 켜져서 더 예쁘네요꽃고 많구요 가족단위 커플 친구들 다 와도 좋을것같아요 근처에 식당도 많아서 뭐먹을지 고민안해도됩니다',
 '파주 프로방스-->가족.커플 방문하기좋음',
 '파주 프로방스-->몇년전에 와보고 간만에 왔는데 많이 바꼈네요주차장도넓어지고 상가도 많이 생기고 밤에 전구로 꾸며서 볼거리도 생기구요 낮에도 밤에도 사진찍을게 많더라구요놀다가 근처에서 식사하시고 아울렛 가시는분들고 있고 반대로 아울렛 쇼핑후 놀러오시는 분들도 많으니 편하신 이동경로로 하시면될것같아요',
 '파주 프로방스-->프랑스마을',
 '파주 프로방스-->프로방스마을은 헤이리와비슷하며 프랑스마을처럼 아기자기하게 잘 꾸며져있습니다 사진찍기에도 좋고 맛집도많이있습니다대표절으로 류재은베이커리라는 빵집이있는데 이곳에 마늘빵 추천드립니다',
 '파주 프로방스-->좋아요',
 '파주 프로방스-->고즈넉하고 평화롭고 음식점이나 카페도 많구요.좀 외져서 미사리처럼 불륜커플 많이 볼 수 있어요.',
 '파주 프로방스-->갈때마다 실망하지만',
 '파주 프로방스-->갈때마다 실망하지만 그럼에도 한번씩 가게되는곳입니다. 가격 비싸구요, 사람도 많고, 예전에비해 심하게 상업적으로 바뀌는듯해서 아쉬워요. 그래도 사진은 예쁘게 나오는곳.',
 '파주 프로방스-->나쁘지 않았어요',
 '파주 프로방스-->운전 연습할 겸 자유로 타고 갔습니다. 상점이 많긴 한데  뭔가.. 부족한 느낌? 옷가게가 대부분이고 예쁜 소품이나 식기들은 별로 없었습니다. 실내 정원이 있어 잠깐 둘러보고 몇 가지 소품 구입, 커피 한잔 마시고 왔네요. 건물이 이뻐서 사진은 잘 나오더라구요^^',
 '파주 프로방스-->헤이리 예술마을 가세요',
 '파주 프로방스-->그냥 한번 가볼만한 정도입니다. 굳이 가겠다면, 데이트할겸 한바퀴도는거 정도는 나쁘지 않습니다. 규모가 그리 크지 않아 오래 걸리지도 않습니다. 근처 건너쪽에 헤이리 예술마을이 훨씬 좋습니다.',
 '파주 프로방스-->나름 인상적인 프로방스',
 '파주 프로방스-->파주에 있는 종합 쇼핑타운으로 프로방스풍으로 특색있게 조성하여 놓은 곳이다. 주차료가 부담스럽기도 하다',
 '융ㆍ건릉-->하루를 조용히 보내기에 좋은 장소 입니다.',
 '융ㆍ건릉-->유명한 관광지는 아니지만 근처에 사는 사람들에게 하루를 조용히 보낼 수 있는 곳입니다.단체 관광으로 방문하는 것은 의미가 없으며 개인적으로 연인과 조용한 하루를 보내기에 좋습니다.한국의 고풍을 느끼기 위해서는 한국 전통 소나무가 중요합니다. 이런 소나무는 현재 잘 남아 있지 않은데 여기는 그런 나무들이 많습니다.',
 '융ㆍ건릉-->가족 나들이',
 '융ㆍ건릉-->조용한 봄에 가족 나들이 장소로 딱인 곳으로 진달래와 새소리로 마음을 정화할 수 있습니다. 가까운 곳에 윤릉과 용주사를 함께 관람하여 가족의 소중함과 아버지와 아들의 그리움을 느낄 수 있는 장소 입니다.',
 '융ㆍ건릉-->융릉과 함께 있어요',
 '융ㆍ건릉-->융릉과 건릉 함께 있습니다.잘 관리된 왕릉을 돌아본다는 마음으로 다녀오시면 좋을것 같아요.주말에는 일반인들이 주로 방문하고 평일에는 초등학생 소풍으로 오는듯합니다.',
 '융ㆍ건릉-->융건릉',
 '융ㆍ건릉-->융릉과 맞닿아 있습니다. 융건릉 입장료 1회로 융릉과 건릉을 볼 수 있습니다. 지대가 굉장히 넓고 나무가 많아 역사적인 지식 쌓기는 물론 힐링하기 좋은 장소입니다.',
 '융ㆍ건릉-->산책하기 좋다',
 '융ㆍ건릉-->역사적 의미가 있는 장소이기도 하지만 오래된 나무들사이로 난 길이 좋아서 산책하기 좋은 곳.',
 '융ㆍ건릉-->시내와 떨어져있어 한적하고 가볍게 산책하기 좋아요!',
 '융ㆍ건릉-->입장료 성인 1000원, 점심시간(12:00-13:00) 이용권 5000원(10회권 기준)주변환경 정돈이 매우 잘 되있고, 잔디상태 너무 좋아서 사진 예쁘게 나와요하늘이 탁 트여서 바람도 잘 불고 마음도 시원해져요. 한여름엔 땡볕이겠지만 ^^;공공장소인데 화장실도 깨끗해요!산책길 따라 걷다보면 키큰 나무들 사이에서 풀내음 맡으며 작은 동물도 발견할수 있어남녀노소 기분좋게 다녀오실수있을것같아요. 특히 아이들이 많이 좋아하더라구요. 오르막이 있으니 이왕이면 편한 신발 신고 가시고 6시에 폐장하니 참고하세요.',
 '융ㆍ건릉-->융건릉',
 '융ㆍ건릉-->건릉과 융릉이 붙어 있어서 입구는 하나이다.위대한 정조대왕의 무덤이며접근 금지라 아래에서 위를 자세히 보긴 어렵다.날씨 좋은 날 산책하면 좋을 것 같다.',
 '융ㆍ건릉-->문화체험 장소로 적합',
 '융ㆍ건릉-->아이들이 커 가면서 물어보는 것도 많고, 가고 싶은곳도 많은것 같습니다. 저희집 아이들도 주말이면 좋은 구경거리를 찾아 다니는데요! 그중하나가 건릉 인것 같습니다. 옛 조상들의 모습을 잠깐 이나마 볼 수 있고, 잘 꾸면지 수목원들이 있어 가족들이 놀기에도 그만인 장소 인것 같습니다.간단한 먹거리와 돗자리만 있다면 꼭 놀러가세요! 건릉으로~',
 '융ㆍ건릉-->조선의 존경할 왕을 만나는 곳',
 '융ㆍ건릉-->왕이지만 자식의 도리를 다한 정조대왕의 모습을 상기하며 여행까지 하는 곳 조선의 역사를 다시금 돌아보며 닮지 못한 아쉬움을 느끼게 만들어 주는 곳',
 '융ㆍ건릉-->산책하기좋은 융 건릉',
 '융ㆍ건릉-->예전에는 돗자리나 음식물 반입금지가 아니라서 소풍겸 자주갔는데 작년부터인가 금지가 됐어요. 음식물반입은 그렇다치고 돗자리는 허용해줬으면 좋겠는데  반입금지 후에는 딱히 안찾게 됩니다.입장료가 있기때문에 특별하게 먼저 찾지는 않게되지만 수목조성이 잘 되어있는 편임으로 가까히 있는경우에는 한번쯤 들려볼만합니다.',
 '자유공원-->산책하기 좋은곳',
 '자유공원-->천천히 걷기 좋고 인천 앞바다를 한눈에 볼수 있는곳 시간이 남거나 근처에 왔다면 가볼만 합니다그리고 맥아더장군 동상을 볼수있어요',
 '자유공원-->동인천의 뷰 포인트',
 '자유공원-->동인천의 뷰 포인트신포시장과 차이나타운, 동화마을이랑 가깝다노을 보기에  최적의 장소로 인천 앞바다가 내려다 보이며 저 멀리 영종도까지 볼 수 있다',
 '자유공원-->4,5월에 방문하기 좋은곳',
 '자유공원-->4,5월에 데이트장소로 방문하기 좋은곳이에요 특히 벚꽃필때는 꼭 야간에 방문해보세요. 정말 좋습니다. 가족 또는 연인과 산책하기 좋은곳!!',
 '자유공원-->산책',
 '자유공원-->봄밤에 산책하기 좋은 공원이예요..저녁으로 차이나타운 들려서 맛난 음식 먹구   산책겸  벗꽃핀 공원을 산책하면  정말 분위기 있고  좋아요~~강추입니다',
 '자유공원-->벚꽃 만발시기에 강추합니다.',
 '자유공원-->가족들과 이 시기에 한 번쯤 가볼만한 가까운 명소......추천합니다!!!! 다만 주차가 조금 쉽지 않습니다. 유료 주차장을 이용하셔야 합니다.',
 '자유공원-->의외로 괜찮은 공원',
 '자유공원-->기대없이 우연히 들른 곳인데 산책하기 꽤 괜찮았어요. 공원도 돌고 주변 시장이나 차이나 타운까지 가면 하루 시간 보내기에 좋은 코스입니다.',
 '자유공원-->봄과 잘 어울리는 공원',
 '자유공원-->5월1일 근로자의날에 차이나타운에 방문하여 바로 위에 위치한 자유공원에 들렀다오래된 나무들이 울창하게 우거져있어 산책하는길이 너무 운치있었으며 공원 곳곳에 여러가지색들의 다양한 꽃들이 봄 햇살에 빛나고있었다 올라가면 인천 앞바다도 보이고 차이나타운에서 맛있는 중식을 즐기고 산책하기 알맞은 곳이다',
 '자유공원-->인천 자유공원',
 '자유공원-->차이나타운 위쪽으로 걷다 보면 제물포고등학교 근처에 있는 곳이에요. 서울 벚꽃은 다 졌는데 여기는 탐스럽고 너무 예쁘게 피어 있네요!',
 '자유공원-->인천의 명소 자유공원',
 '자유공원-->인천역이나 동인천역에서 도보로 이동 가능한 도심공원... 주변 차이나타운이나 신포시장 등과 함께 코스로 잡으면 좋을듯해요...저녁 무렵 서해 낙조도 볼수있는 곳이니 시간 잘 맞추시면 좋은 여행지가 될거예요...',
 '자유공원-->걷기운동하기 딱 좋은 자유공원',
 '자유공원-->처음에 갔을 때, 우와~ ! 조명때문인지 살짝 차이나 느낌이 나서 좀 이국적인 느낌도 들었구요. 장시간 걷기운동하러가기 딱 좋은 곳, 데이트 하기에도 좋은 곳. 봄에 꽃피고 나서 가면 정말 좋겠구나 생각했습니다 ^^',
 '통일전망대-->글쎄요.....',
 '통일전망대-->입장료 3천원이지만, 호불호가 갈릴 것 같읍니다. 친구랑 같이 갔는데, 친구는 엄청 아까워 하더군요. 맑은 날에는 시야가 트여서 멀리까지 잘 보일 것 같읍니다.',
 '통일전망대-->방문기',
 '통일전망대-->이곳은 자유로를 달리다 보면 임진강 변으로 보이는 전망대입니다. 전망이 좋아 건너편 북쪽 마을과 전경이 대한민국이 처한 분단의 현실을 느낄 수 있는 곳입니다.',
 '통일전망대-->역사의 현장',
 '통일전망대-->아이들과 역사투어하며 여러군데를 방문했는데 여기도 정말 좋았어요. 언덕이 조금 높아 차가 올라가는데 어려움을 겪었네요',
 '통일전망대-->가족 나들이겸 안보견학하기에 좋은곳',
 '통일전망대-->통일 평화등 뜬구름 잡는 얘기보다는 이런곳에 방문해서 아이들에게 직접 보여주는것이 최고의 안보교육이 아닐까 싶습니다. 망원경으로 잘 보면 북한의 모습도 보여요',
 '통일전망대-->가족나들이 도시락싸고 소풍 ^^',
 '통일전망대-->어제 가족들과 함께 파주 헤이리마을 가다 통일전망대를 보고 찾아 갔습니다. 강원도에만 있는줄 알았는데 파주에 있어서 아이 교육상 방문했습니다. 주말에는 아래 주차장에 차를 주차하고 셔틀버스 타야합니다. 저희가 방문한 날은 무료입장 기간이였습니다. 생각보다 너무 잘 꾸며져 있었습니다.  아이들체험공간도 있고 전망대에 카페도 있고 , 북측지역 설명도 잘 되어 있었습니다. 준비해간  도시락 먹으며 편한하게 가족나들이를 즐길수 있는 곳입니다.',
 '통일전망대-->아름다운 오두산 통일전망대',
 '통일전망대-->입장료 3000원으로 통일휴게소에서 주차하고 셔틀버스를 운행하고 있어 손쉽게 오두산 통일전망대에 도착할수 있었다. 벚꽃시즌이라 너무 좋았다. 사람도 많지 않고 한적하고 개나리도 피였다',
 '통일전망대-->좋아요',
 '통일전망대-->좋아요. 통일전망대에도 외국인이 많이 보입니다. 우리나라가 분단국가라는 현실을 확실하게 느낄 수 있어요.',
 '통일전망대-->할머니가 북한분이셔서',
 '통일전망대-->안에서 북한 특산물 이것저것 팔고명절엔.실향민들이 와서 제사도 지내요교통이 불편 일산에서도 한참 가야함교육적으로는 꽤 괜찮음',
 '통일전망대-->난 별로',
 '통일전망대-->친구네 할아버지가 이북분이셔서 아버지랑 가끔갔다고한번가보자고해서갔는데북한은 잘 보이지도 않구 너무 춥고ㅜㅜ저에겐 의미있는 장소는 아니었네요',
 '통일전망대-->북한 사람들이 보입니다.',
 '통일전망대-->오두산 통일 전망대 입니다. 집이 파주인 저는 이곳에 여러번 방문한 적이 있습니다.이곳에서 망원경을 통하면 실제의 북한 주민들을 볼수가 있습니다.또한 북한의 현재 생활을 엿볼수 있는 비디오 등 여러가지 전시물을 통해 북한에 대해 알수가 있습니다.한 번 쯤 가볼만 합니다.',
 '십리포 해수욕장-->물놀이와 조개잡이가 가능한 바닷가',
 '십리포 해수욕장-->토요일에 방문했는데 사람들이 제법 많았지만 인산인해라 할 정도는 아니었고,체온과 연락처를 확인한 뒤 이용권 팔찌를 나눠주고 있었습니다.화장실, 샤워실, 수도 시설이 잘 되어 있어 아이들과 함께 놀기 좋았습니다.텐트 치는 곳은 꽤 안쪽인데 캠핑 의자를 가져가니 아이들이 있는 바닷가 가까이에 있을 수 있어 좋았습니다.물이 빠지고 나니 다들 조개잡이에 나서더군요. 해안 왼쪽에 나무 울타리 있는 쪽에서 많이 잡을 수 있었습니다.',
 '십리포 해수욕장-->인천의 아름다운 섬, 영흥도의 십리포해수욕장',
 '십리포 해수욕장-->서울에서 가까운 해변을 찾아다닌지가 꽤 되는데요 무의도 하나개해수욕장은 알려지지 않았던 시절부터 다녔는데 이제는 배타고 나와서 교통체증이 싫어지고 비용도 그렇고..연륙교로 연결된 섬의 해변을 찾아다닙니다. 근년에 가끔 찾는 영흥도의 십리포 해변, 소박하지만 아이들 모래장난하고 갯벌체험하기 편안하고 좋은 장소로 추천합니다. 대부도 거쳐서 선재도 지나 영흥도로 들어가니 시화방조제까지의 교통체증은 어쩔수 없습니다만..',
 '순천 드라마세트장 -->재미있어요',
 '순천 드라마세트장 -->꼭 옷도 빌려입고 놀아보세요 순천역쪽에 개화기 의상도 렌탈 해주더군요 미리 빌려입고 와도 좋을거 같아요. 교복은 현장에서 가능이요',
 '순천 드라마세트장 -->옛 사람들의 정취가 남아있는 곳.',
 '순천 드라마세트장 -->한 겨울에 방문해서 사람들이 적었고, 스산하기 까지 했음. 그래도 한번쯤 나이 드신 분들과 오게 되면 옛 생각이 새록새록 날 그런 장소... 한번은 꼭 들러볼만 합니다.',
 '순천 드라마세트장 -->순천여행',
 '순천 드라마세트장 -->지금처럼 바쁜일상에서 시간이 정지된거 처럼 옛 추억을 생각할 수 것 같아서 좋아서요 오랜된 건물 같은데 보존도 잘 되고 있어서좋아서요.',
 '순천 드라마세트장 -->추억의 장소',
 '순천 드라마세트장 -->드라마와 영화 촬영장입니다 과거 장면들을 추억할수 있습니다 그렇게 크지 않아서 한시간이면 충분히 볼 수 있습니다 순천오시면 들려보세요',
 '순천 드라마세트장 -->교복입기 체험하고 사진찍으면 좋아요',
 '순천 드라마세트장 -->드라마 촬영장이 옛날 70-80년대를 배경으로 만들어져 있어서 고즈넉한 느낌에 색다른 느낌이 있어요. 옛날 교복 빌려 입고 사진 찍으면 타임머신 탄 느낌이 들 정도!',
 '순천 드라마세트장 -->6-70년대옛날 향수를 느끼시는 분은 한번쯤 방문해보시길...',
 '순천 드라마세트장 -->6-70년대옛날 향수를 느끼시는 분은 한번쯤 방문해보시길...어른들이 옛날 기억을 새록새록하게핫네요..ㅎㅎ달동네는 오르막길이 있어 어른들이 조금 힘들수도 있습니다.',
 '순천 드라마세트장 -->드라마세트장 데이트',
 '순천 드라마세트장 -->재미있는 구경을 많이 했다. 영화나 드라마에 나온 곳을 발견하는 재미가 쏠쏠. 신기한건 이렇게나 건물들이 작은데 어떻게 영상속에선 작게 안보였을까 하는 점',
 '순천 드라마세트장 -->기억이 새록 새록',
 '순천 드라마세트장 -->서울 달동네와 어린 시절에 보고 경험해 익숙한 셋트장에 잊혀진 기억들이 새록 새록특히 예날 타고 다니던 자전거하며, 농기구다만 아쉬운건 달동네 셋트장에서 집집마다 내부도 현장감있게 보수하였으면 좋겠다는 생각이 듭니다.',
 '순천 드라마세트장 -->사진찍기 좋은 날에~~^^',
 '순천 드라마세트장 -->기분  좋은  그  어떤  날~~~   그 곳에선  그  어떠한  모습도  예쁘고  사랑스럽다  컨셉사진 몇 컷 찍고  션하게  막걸리도  한잔하고~~~  드라마 주인공이된냥~~^^  나두  나름  즐기고 있었던 것 같았다  그 날~~~~',
 '순천 드라마세트장 -->재밌네요ㅎ',
 '순천 드라마세트장 -->드라마세트장 재밌어요다들 교복 입고 돌아다니시던데 보기좋았어요되게 드라마생각나고 예전의 부모님세대의 분위기를 느낄수있었어요']

In [98]:
df_1

            여행지 일치여부  다른 칸에 존재여부
0       안양 예술공원    X           1
1  부천 활박물관과 궁도장    X           1
2       파주 프로방스    X           1
3          융ㆍ건릉    X           1
4          자유공원    X           1
5         통일전망대    X           1
6      십리포 해수욕장    X           1
7    순천 드라마세트장     X           1

In [104]:
df_1 = pd.DataFrame(reviews, columns=['리뷰'])

In [105]:
df_1.to_csv('./data/추가 리뷰.csv', encoding='utf-8-sig')

In [109]:
df_1

                                                    리뷰
0                                     안양 예술공원-->안양예술공원
1    안양 예술공원-->갈때마다 새로운 프로그램과,유명한 아티스트들의작품들이 많다.볼거리...
2                    안양 예술공원-->어르신도 살방살방 다니기 높지 않은 공원길
3    안양 예술공원-->안양시내에 이런 쉼터가 잇다는게 행복한 일이다. 주변의 사찰과 산...
4                     부천 활박물관과 궁도장-->다른 박물관과 같이 보기 좋아요
..                                                 ...
115  순천 드라마세트장 -->서울 달동네와 어린 시절에 보고 경험해 익숙한 셋트장에 잊혀...
116                        순천 드라마세트장 -->사진찍기 좋은 날에~~^^
117  순천 드라마세트장 -->기분  좋은  그  어떤  날~~~   그 곳에선  그  어...
118                                 순천 드라마세트장 -->재밌네요ㅎ
119  순천 드라마세트장 -->드라마세트장 재밌어요다들 교복 입고 돌아다니시던데 보기좋았어...

[120 rows x 1 columns]

In [112]:
options=webdriver.ChromeOptions()
options.add_argument('user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36')
options.add_experimental_option("excludeSwitches", ["enable-logging"])


driver=webdriver.Chrome()
url='https://www.tripadvisor.co.kr/'

category1=[]
score1 = []
for i in range(len(df_one)):
    driver.get(url)
    search=df_one['여행지'][i]
    driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(search)
    driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(Keys.ENTER)
    driver.switch_to.window(driver.window_handles[-1])
    time.sleep(2)
    try:
        driver.find_element_by_css_selector('#BODY_BLOCK_JQUERY_REFLOW > div.page > div > div.ui_container.main_wrap > div > div > div > div > div.content_column.ui_column.is-9-desktop.is-12-tablet.is-12-mobile > div > div.ui_columns.sections_wrapper > div > div.prw_rup.prw_search_search_results.ajax-content > div > div.main_content.ui_column.is-12 > div > div:nth-child(2) > div > div > div:nth-child(1) > div > div > div > div.ui_column.is-9-desktop.is-8-mobile.is-9-tablet.content-block-column > div').click()

        driver.switch_to.window(driver.window_handles[-1])
        soup=BeautifulSoup(driver.page_source,'html.parser')
        mydata=soup.find('div','pIRBV _T KRIav')
        category1.append(search + '-->' + mydata.get_text())
        mydata2=soup.find('div','WlYyy cPsXC fksET cMKSg')
        score1.append(search + '-->' + mydata2.get_text())
        driver.switch_to.window(driver.window_handles[-1])
        driver.close()
        driver.switch_to.window(driver.window_handles[0])
        driver.back()
        time.sleep(1)
    except:
        category1.append('결과 없음')
        score1.append('결과 없음')

In [116]:
category = category+category1
len(category)

57

In [117]:
score = score+score1

In [131]:
len(score)

49

In [125]:
category = category[:49]

In [126]:
category

['암사동 선사주거지-->역사적인 장소',
 '화성-->역사적인 장소',
 '대부도-->섬',
 '국립현대미술관(과천관)-->아트뮤지엄',
 '독립기념관-->역사박물관',
 '공산성-->역사적인 장소 • 즐길거리 & 랜드마크',
 '무령왕릉-->역사적인 장소',
 '충청수영성-->역사적인 장소 • 성 • 경관이 좋은 산책로',
 '천주교 대전교구 공세리성당-->종교적인 장소',
 '팜카밀레 허브농원-->공원 • 가든',
 '천주교 전주교구 전동성당-->종교적인 장소',
 '무주 구천동계곡 방화동 가족휴양촌,-->국립공원 • 자연 & 야생동물 서식지 • 계곡',
 '순천만 갈대밭-->공원',
 '용천사-->역사적인 장소 • 종교적인 장소 • 경관이 좋은 산책로',
 '계림-->유서 깊은 산책로',
 '금오산-->공원',
 '빙계계곡-->물길 • 산림 • 계곡',
 '군위 삼존석굴-->역사적인 장소 • 종교적인 장소',
 '주남저수지-->자연 & 야생동물 서식지',
 '청곡사-->종교적인 장소',
 '고성 탈박물관-->전문 박물관',
 '임진성-->성',
 '다랑쉬오름-->화산',
 '약천사-->종교적인 장소',
 '제주 올레-->하이킹 트레일',
 '월드컵공원-->기타 야외 활동',
 '대한민국 국회의사당과 헌정기념관-->전문 박물관',
 '산사원-->전문 박물관 • 맥주 양조장',
 '탄금대-->물길',
 '지리산 산수유마을-->유서 깊은 산책로 • 절경 드라이브 코스 • 경관이 좋은 산책로',
 '항공우주박물관-->과학박물관',
 '창녕 석빙고-->역사적인 장소',
 '천제연폭포-->폭포',
 '대둔산-->산',
 '그림이 있는 정원-->가든',
 '마이산 도립공원-->산',
 '용궁사-->종교적인 장소',
 '한벽당-->역사적인 장소',
 '달아공원-->자연 & 야생동물 서식지',
 '벌교 홍교, 대한다원-->산림 • 농장',
 '결과 없음',
 '안양 예술공원-->공원',
 '부천 활박물관과 궁도장-->전문 박물관',
 '파주 프로방스-->특산물 & 기념품 가게 • 쇼핑몰',
 '융ㆍ건릉-->역사적인 장소',
 '자유공원-->공원',
 '통일전망대-->전망대 & 타워',
 '십리포 해수욕장-->해변',
 '순천 드라마세트장 -->즐길거리 & 랜드마크']

In [132]:
len(category)

49

In [133]:
df_category = pd.DataFrame(category, columns=['카테고리'])
df_category

                                               카테고리
0                               암사동 선사주거지-->역사적인 장소
1                                      화성-->역사적인 장소
2                                           대부도-->섬
3                              국립현대미술관(과천관)-->아트뮤지엄
4                                     독립기념관-->역사박물관
5                       공산성-->역사적인 장소 • 즐길거리 & 랜드마크
6                                    무령왕릉-->역사적인 장소
7                  충청수영성-->역사적인 장소 • 성 • 경관이 좋은 산책로
8                          천주교 대전교구 공세리성당-->종교적인 장소
9                               팜카밀레 허브농원-->공원 • 가든
10                          천주교 전주교구 전동성당-->종교적인 장소
11  무주 구천동계곡 방화동 가족휴양촌,-->국립공원 • 자연 & 야생동물 서식지 • 계곡
12                                     순천만 갈대밭-->공원
13             용천사-->역사적인 장소 • 종교적인 장소 • 경관이 좋은 산책로
14                                   계림-->유서 깊은 산책로
15                                         금오산-->공원
16                              빙계계곡-->물길 • 산림 • 계곡
17                      군위 삼존석굴-->역사적인 장소 • 종교적인 장소
18                            주남저수지-->자연 & 야생동물 서식지
19                                    청곡사-->종교적인 장소
20                                 고성 탈박물관-->전문 박물관
21                                          임진성-->성
22                                       다랑쉬오름-->화산
23                                    약천사-->종교적인 장소
24                                  제주 올레-->하이킹 트레일
25                                 월드컵공원-->기타 야외 활동
26                       대한민국 국회의사당과 헌정기념관-->전문 박물관
27                            산사원-->전문 박물관 • 맥주 양조장
28                                         탄금대-->물길
29  지리산 산수유마을-->유서 깊은 산책로 • 절경 드라이브 코스 • 경관이 좋은 산책로
30                                  항공우주박물관-->과학박물관
31                                 창녕 석빙고-->역사적인 장소
32                                       천제연폭포-->폭포
33                                          대둔산-->산
34                                   그림이 있는 정원-->가든
35                                     마이산 도립공원-->산
36                                    용궁사-->종교적인 장소
37                                    한벽당-->역사적인 장소
38                             달아공원-->자연 & 야생동물 서식지
39                            벌교 홍교, 대한다원-->산림 • 농장
40                                            결과 없음
41                                     안양 예술공원-->공원
42                            부천 활박물관과 궁도장-->전문 박물관
43                     파주 프로방스-->특산물 & 기념품 가게 • 쇼핑몰
44                                   융ㆍ건릉-->역사적인 장소
45                                        자유공원-->공원
46                                 통일전망대-->전망대 & 타워
47                                    십리포 해수욕장-->해변
48                         순천 드라마세트장 -->즐길거리 & 랜드마크

In [134]:
df_category['평점'] = score

In [135]:
df_category

                                               카테고리                         평점
0                               암사동 선사주거지-->역사적인 장소            암사동 선사주거지-->4.5
1                                      화성-->역사적인 장소                   화성-->4.0
2                                           대부도-->섬                  대부도-->4.0
3                              국립현대미술관(과천관)-->아트뮤지엄         국립현대미술관(과천관)-->4.5
4                                     독립기념관-->역사박물관                독립기념관-->4.5
5                       공산성-->역사적인 장소 • 즐길거리 & 랜드마크                  공산성-->4.5
6                                    무령왕릉-->역사적인 장소                 무령왕릉-->4.0
7                  충청수영성-->역사적인 장소 • 성 • 경관이 좋은 산책로                충청수영성-->5.0
8                          천주교 대전교구 공세리성당-->종교적인 장소       천주교 대전교구 공세리성당-->4.5
9                               팜카밀레 허브농원-->공원 • 가든            팜카밀레 허브농원-->5.0
10                          천주교 전주교구 전동성당-->종교적인 장소        천주교 전주교구 전동성당-->4.0
11  무주 구천동계곡 방화동 가족휴양촌,-->국립공원 • 자연 & 야생동물 서식지 • 계곡  무주 구천동계곡 방화동 가족휴양촌,-->5.0
12                                     순천만 갈대밭-->공원              순천만 갈대밭-->4.5
13             용천사-->역사적인 장소 • 종교적인 장소 • 경관이 좋은 산책로                  용천사-->4.0
14                                   계림-->유서 깊은 산책로                   계림-->4.0
15                                         금오산-->공원                  금오산-->4.5
16                              빙계계곡-->물길 • 산림 • 계곡                 빙계계곡-->5.0
17                      군위 삼존석굴-->역사적인 장소 • 종교적인 장소              군위 삼존석굴-->4.5
18                            주남저수지-->자연 & 야생동물 서식지                주남저수지-->4.0
19                                    청곡사-->종교적인 장소                  청곡사-->3.5
20                                 고성 탈박물관-->전문 박물관              고성 탈박물관-->4.0
21                                          임진성-->성                  임진성-->3.5
22                                       다랑쉬오름-->화산                다랑쉬오름-->5.0
23                                    약천사-->종교적인 장소                  약천사-->4.5
24                                  제주 올레-->하이킹 트레일                제주 올레-->4.5
25                                 월드컵공원-->기타 야외 활동                월드컵공원-->4.5
26                       대한민국 국회의사당과 헌정기념관-->전문 박물관    대한민국 국회의사당과 헌정기념관-->4.0
27                            산사원-->전문 박물관 • 맥주 양조장                  산사원-->4.5
28                                         탄금대-->물길                  탄금대-->4.5
29  지리산 산수유마을-->유서 깊은 산책로 • 절경 드라이브 코스 • 경관이 좋은 산책로            지리산 산수유마을-->4.0
30                                  항공우주박물관-->과학박물관              항공우주박물관-->4.0
31                                 창녕 석빙고-->역사적인 장소               창녕 석빙고-->3.5
32                                       천제연폭포-->폭포                천제연폭포-->4.0
33                                          대둔산-->산                  대둔산-->4.5
34                                   그림이 있는 정원-->가든            그림이 있는 정원-->2.5
35                                     마이산 도립공원-->산             마이산 도립공원-->4.5
36                                    용궁사-->종교적인 장소                  용궁사-->4.0
37                                    한벽당-->역사적인 장소                  한벽당-->4.0
38                             달아공원-->자연 & 야생동물 서식지                 달아공원-->4.0
39                            벌교 홍교, 대한다원-->산림 • 농장          벌교 홍교, 대한다원-->4.5
40                                            결과 없음                      결과 없음
41                                     안양 예술공원-->공원              안양 예술공원-->4.5
42                            부천 활박물관과 궁도장-->전문 박물관         부천 활박물관과 궁도장-->4.0
43                     파주 프로방스-->특산물 & 기념품 가게 • 쇼핑몰              파주 프로방스-->4.0
44                                   융ㆍ건릉-->역사적인 장소                 융ㆍ건릉-->4.0
45                                        자유공원-->공원                 자유공원-->4.0
46                                 통일전망대-->전망대 & 타워                통일전망대-->4.0
47                                    십리포 해수욕장-->해변             십리포 해수욕장-->3.5
48                         순천 드라마세트장 -->즐길거리 & 랜드마크           순천 드라마세트장 -->4.0

In [136]:
df_category = df_category.drop([40])

In [138]:
df_category = df_category.reset_index(drop = True)
df_category

                                               카테고리                         평점
0                               암사동 선사주거지-->역사적인 장소            암사동 선사주거지-->4.5
1                                      화성-->역사적인 장소                   화성-->4.0
2                                           대부도-->섬                  대부도-->4.0
3                              국립현대미술관(과천관)-->아트뮤지엄         국립현대미술관(과천관)-->4.5
4                                     독립기념관-->역사박물관                독립기념관-->4.5
5                       공산성-->역사적인 장소 • 즐길거리 & 랜드마크                  공산성-->4.5
6                                    무령왕릉-->역사적인 장소                 무령왕릉-->4.0
7                  충청수영성-->역사적인 장소 • 성 • 경관이 좋은 산책로                충청수영성-->5.0
8                          천주교 대전교구 공세리성당-->종교적인 장소       천주교 대전교구 공세리성당-->4.5
9                               팜카밀레 허브농원-->공원 • 가든            팜카밀레 허브농원-->5.0
10                          천주교 전주교구 전동성당-->종교적인 장소        천주교 전주교구 전동성당-->4.0
11  무주 구천동계곡 방화동 가족휴양촌,-->국립공원 • 자연 & 야생동물 서식지 • 계곡  무주 구천동계곡 방화동 가족휴양촌,-->5.0
12                                     순천만 갈대밭-->공원              순천만 갈대밭-->4.5
13             용천사-->역사적인 장소 • 종교적인 장소 • 경관이 좋은 산책로                  용천사-->4.0
14                                   계림-->유서 깊은 산책로                   계림-->4.0
15                                         금오산-->공원                  금오산-->4.5
16                              빙계계곡-->물길 • 산림 • 계곡                 빙계계곡-->5.0
17                      군위 삼존석굴-->역사적인 장소 • 종교적인 장소              군위 삼존석굴-->4.5
18                            주남저수지-->자연 & 야생동물 서식지                주남저수지-->4.0
19                                    청곡사-->종교적인 장소                  청곡사-->3.5
20                                 고성 탈박물관-->전문 박물관              고성 탈박물관-->4.0
21                                          임진성-->성                  임진성-->3.5
22                                       다랑쉬오름-->화산                다랑쉬오름-->5.0
23                                    약천사-->종교적인 장소                  약천사-->4.5
24                                  제주 올레-->하이킹 트레일                제주 올레-->4.5
25                                 월드컵공원-->기타 야외 활동                월드컵공원-->4.5
26                       대한민국 국회의사당과 헌정기념관-->전문 박물관    대한민국 국회의사당과 헌정기념관-->4.0
27                            산사원-->전문 박물관 • 맥주 양조장                  산사원-->4.5
28                                         탄금대-->물길                  탄금대-->4.5
29  지리산 산수유마을-->유서 깊은 산책로 • 절경 드라이브 코스 • 경관이 좋은 산책로            지리산 산수유마을-->4.0
30                                  항공우주박물관-->과학박물관              항공우주박물관-->4.0
31                                 창녕 석빙고-->역사적인 장소               창녕 석빙고-->3.5
32                                       천제연폭포-->폭포                천제연폭포-->4.0
33                                          대둔산-->산                  대둔산-->4.5
34                                   그림이 있는 정원-->가든            그림이 있는 정원-->2.5
35                                     마이산 도립공원-->산             마이산 도립공원-->4.5
36                                    용궁사-->종교적인 장소                  용궁사-->4.0
37                                    한벽당-->역사적인 장소                  한벽당-->4.0
38                             달아공원-->자연 & 야생동물 서식지                 달아공원-->4.0
39                            벌교 홍교, 대한다원-->산림 • 농장          벌교 홍교, 대한다원-->4.5
40                                     안양 예술공원-->공원              안양 예술공원-->4.5
41                            부천 활박물관과 궁도장-->전문 박물관         부천 활박물관과 궁도장-->4.0
42                     파주 프로방스-->특산물 & 기념품 가게 • 쇼핑몰              파주 프로방스-->4.0
43                                   융ㆍ건릉-->역사적인 장소                 융ㆍ건릉-->4.0
44                                        자유공원-->공원                 자유공원-->4.0
45                                 통일전망대-->전망대 & 타워                통일전망대-->4.0
46                                    십리포 해수욕장-->해변             십리포 해수욕장-->3.5
47                         순천 드라마세트장 -->즐길거리 & 랜드마크           순천 드라마세트장 -->4.0

In [140]:
df_category['관광지']=df_category.카테고리.str.split('-->').str[0]
df_category['분류']=df_category.카테고리.str.split('-->').str[1]
df_category

,카테고리,평점,관광지,분류
0,암사동 선사주거지-->역사적인 장소,암사동 선사주거지-->4.5,암사동 선사주거지,역사적인 장소
1,화성-->역사적인 장소,화성-->4.0,화성,역사적인 장소
2,대부도-->섬,대부도-->4.0,대부도,섬
3,국립현대미술관(과천관)-->아트뮤지엄,국립현대미술관(과천관)-->4.5,국립현대미술관(과천관),아트뮤지엄
4,독립기념관-->역사박물관,독립기념관-->4.5,독립기념관,역사박물관
5,공산성-->역사적인 장소 • 즐길거리 & 랜드마크,공산성-->4.5,공산성,역사적인 장소 • 즐길거리 & 랜드마크
6,무령왕릉-->역사적인 장소,무령왕릉-->4.0,무령왕릉,역사적인 장소
7,충청수영성-->역사적인 장소 • 성 • 경관이 좋은 산책로,충청수영성-->5.0,충청수영성,역사적인 장소 • 성 • 경관이 좋은 산책로
8,천주교 대전교구 공세리성당-->종교적인 장소,천주교 대전교구 공세리성당-->4.5,천주교 대전교구 공세리성당,종교적인 장소
9,팜카밀레 허브농원-->공원 • 가든,팜카밀레 허브농원-->5.0,팜카밀레 허브농원,공원 • 가든
10,천주교 전주교구 전동성당-->종교적인 장소,천주교 전주교구 전동성당-->4.0,천주교 전주교구 전동성당,종교적인 장소
11,"무주 구천동계곡 방화동 가족휴양촌,-->국립공원 • 자연 & 야생동물 서식지 • 계곡","무주 구천동계곡 방화동 가족휴양촌,-->5.0","무주 구천동계곡 방화동 가족휴양촌,",국립공원 • 자연 & 야생동물 서식지 • 계곡
12,순천만 갈대밭-->공원,순천만 갈대밭-->4.5,순천만 갈대밭,공원
13,용천사-->역사적인 장소 • 종교적인 장소 • 경관이 좋은 산책로,용천사-->4.0,용천사,역사적인 장소 • 종교적인 장소 • 경관이 좋은 산책로
14,계림-->유서 깊은 산책로,계림-->4.0,계림,유서 깊은 산책로
15,금오산-->공원,금오산-->4.5,금오산,공원
16,빙계계곡-->물길 • 산림 • 계곡,빙계계곡-->5.0,빙계계곡,물길 • 산림 • 계곡
17,군위 삼존석굴-->역사적인 장소 • 종교적인 장소,군위 삼존석굴-->4.5,군위 삼존석굴,역사적인 장소 • 종교적인 장소
18,주남저수지-->자연 & 야생동물 서식지,주남저수지-->4.0,주남저수지,자연 & 야생동물 서식지
19,청곡사-->종교적인 장소,청곡사-->3.5,청곡사,종교적인 장소
20,고성 탈박물관-->전문 박물관,고성 탈박물관-->4.0,고성 탈박물관,전문 박물관
21,임진성-->성,임진성-->3.5,임진성,성
22,다랑쉬오름-->화산,다랑쉬오름-->5.0,다랑쉬오름,화산
23,약천사-->종교적인 장소,약천사-->4.5,약천사,종교적인 장소
24,제주 올레-->하이킹 트레일,제주 올레-->4.5,제주 올레,하이킹 트레일
25,월드컵공원-->기타 야외 활동,월드컵공원-->4.5,월드컵공원,기타 야외 활동
26,대한민국 국회의사당과 헌정기념관-->전문 박물관,대한민국 국회의사당과 헌정기념관-->4.0,대한민국 국회의사당과 헌정기념관,전문 박물관
27,산사원-->전문 박물관 • 맥주 양조장,산사원-->4.5,산사원,전문 박물관 • 맥주 양조장
28,탄금대-->물길,탄금대-->4.5,탄금대,물길
29,지리산 산수유마을-->유서 깊은 산책로 • 절경 드라이브 코스 • 경관이 좋은 산책로,지리산 산수유마을-->4.0,지리산 산수유마을,유서 깊은 산책로 • 절경 드라이브 코스 • 경관이 좋은 산책로
30,항공우주박물관-->과학박물관,항공우주박물관-->4.0,항공우주박물관,과학박물관
31,창녕 석빙고-->역사적인 장소,창녕 석빙고-->3.5,창녕 석빙고,역사적인 장소
32,천제연폭포-->폭포,천제연폭포-->4.0,천제연폭포,폭포
33,대둔산-->산,대둔산-->4.5,대둔산,산
34,그림이 있는 정원-->가든,그림이 있는 정원-->2.5,그림이 있는 정원,가든
35,마이산 도립공원-->산,마이산 도립공원-->4.5,마이산 도립공원,산
36,용궁사-->종교적인 장소,용궁사-->4.0,용궁사,종교적인 장소
37,한벽당-->역사적인 장소,한벽당-->4.0,한벽당,역사적인 장소
38,달아공원-->자연 & 야생동물 서식지,달아공원-->4.0,달아공원,자연 & 야생동물 서식지
39,"벌교 홍교, 대한다원-->산림 • 농장","벌교 홍교, 대한다원-->4.5","벌교 홍교, 대한다원",산림 • 농장
40,안양 예술공원-->공원,안양 예술공원-->4.5,안양 예술공원,공원
41,부천 활박물관과 궁도장-->전문 박물관,부천 활박물관과 궁도장-->4.0,부천 활박물관과 궁도장,전문 박물관
42,파주 프로방스-->특산물 & 기념품 가게 • 쇼핑몰,파주 프로방스-->4.0,파주 프로방스,특산물 & 기념품 가게 • 쇼핑몰
43,융ㆍ건릉-->역사적인 장소,융ㆍ건릉-->4.0,융ㆍ건릉,역사적인 장소
44,자유공원-->공원,자유공원-->4.0,자유공원,공원
45,통일전망대-->전망대 & 타워,통일전망대-->4.0,통일전망대,전망대 & 타워
46,십리포 해수욕장-->해변,십리포 해수욕장-->3.5,십리포 해수욕장,해변
47,순천 드라마세트장 -->즐길거리 & 랜드마크,순천 드라마세트장 -->4.0,순천 드라마세트장,즐길거리 & 랜드마크

In [141]:
df_category['평점']=df_category.평점.str.split('-->').str[1]
df_category

,카테고리,평점,관광지,분류
0,암사동 선사주거지-->역사적인 장소,4.5,암사동 선사주거지,역사적인 장소
1,화성-->역사적인 장소,4.0,화성,역사적인 장소
2,대부도-->섬,4.0,대부도,섬
3,국립현대미술관(과천관)-->아트뮤지엄,4.5,국립현대미술관(과천관),아트뮤지엄
4,독립기념관-->역사박물관,4.5,독립기념관,역사박물관
5,공산성-->역사적인 장소 • 즐길거리 & 랜드마크,4.5,공산성,역사적인 장소 • 즐길거리 & 랜드마크
6,무령왕릉-->역사적인 장소,4.0,무령왕릉,역사적인 장소
7,충청수영성-->역사적인 장소 • 성 • 경관이 좋은 산책로,5.0,충청수영성,역사적인 장소 • 성 • 경관이 좋은 산책로
8,천주교 대전교구 공세리성당-->종교적인 장소,4.5,천주교 대전교구 공세리성당,종교적인 장소
9,팜카밀레 허브농원-->공원 • 가든,5.0,팜카밀레 허브농원,공원 • 가든
10,천주교 전주교구 전동성당-->종교적인 장소,4.0,천주교 전주교구 전동성당,종교적인 장소
11,"무주 구천동계곡 방화동 가족휴양촌,-->국립공원 • 자연 & 야생동물 서식지 • 계곡",5.0,"무주 구천동계곡 방화동 가족휴양촌,",국립공원 • 자연 & 야생동물 서식지 • 계곡
12,순천만 갈대밭-->공원,4.5,순천만 갈대밭,공원
13,용천사-->역사적인 장소 • 종교적인 장소 • 경관이 좋은 산책로,4.0,용천사,역사적인 장소 • 종교적인 장소 • 경관이 좋은 산책로
14,계림-->유서 깊은 산책로,4.0,계림,유서 깊은 산책로
15,금오산-->공원,4.5,금오산,공원
16,빙계계곡-->물길 • 산림 • 계곡,5.0,빙계계곡,물길 • 산림 • 계곡
17,군위 삼존석굴-->역사적인 장소 • 종교적인 장소,4.5,군위 삼존석굴,역사적인 장소 • 종교적인 장소
18,주남저수지-->자연 & 야생동물 서식지,4.0,주남저수지,자연 & 야생동물 서식지
19,청곡사-->종교적인 장소,3.5,청곡사,종교적인 장소
20,고성 탈박물관-->전문 박물관,4.0,고성 탈박물관,전문 박물관
21,임진성-->성,3.5,임진성,성
22,다랑쉬오름-->화산,5.0,다랑쉬오름,화산
23,약천사-->종교적인 장소,4.5,약천사,종교적인 장소
24,제주 올레-->하이킹 트레일,4.5,제주 올레,하이킹 트레일
25,월드컵공원-->기타 야외 활동,4.5,월드컵공원,기타 야외 활동
26,대한민국 국회의사당과 헌정기념관-->전문 박물관,4.0,대한민국 국회의사당과 헌정기념관,전문 박물관
27,산사원-->전문 박물관 • 맥주 양조장,4.5,산사원,전문 박물관 • 맥주 양조장
28,탄금대-->물길,4.5,탄금대,물길
29,지리산 산수유마을-->유서 깊은 산책로 • 절경 드라이브 코스 • 경관이 좋은 산책로,4.0,지리산 산수유마을,유서 깊은 산책로 • 절경 드라이브 코스 • 경관이 좋은 산책로
30,항공우주박물관-->과학박물관,4.0,항공우주박물관,과학박물관
31,창녕 석빙고-->역사적인 장소,3.5,창녕 석빙고,역사적인 장소
32,천제연폭포-->폭포,4.0,천제연폭포,폭포
33,대둔산-->산,4.5,대둔산,산
34,그림이 있는 정원-->가든,2.5,그림이 있는 정원,가든
35,마이산 도립공원-->산,4.5,마이산 도립공원,산
36,용궁사-->종교적인 장소,4.0,용궁사,종교적인 장소
37,한벽당-->역사적인 장소,4.0,한벽당,역사적인 장소
38,달아공원-->자연 & 야생동물 서식지,4.0,달아공원,자연 & 야생동물 서식지
39,"벌교 홍교, 대한다원-->산림 • 농장",4.5,"벌교 홍교, 대한다원",산림 • 농장
40,안양 예술공원-->공원,4.5,안양 예술공원,공원
41,부천 활박물관과 궁도장-->전문 박물관,4.0,부천 활박물관과 궁도장,전문 박물관
42,파주 프로방스-->특산물 & 기념품 가게 • 쇼핑몰,4.0,파주 프로방스,특산물 & 기념품 가게 • 쇼핑몰
43,융ㆍ건릉-->역사적인 장소,4.0,융ㆍ건릉,역사적인 장소
44,자유공원-->공원,4.0,자유공원,공원
45,통일전망대-->전망대 & 타워,4.0,통일전망대,전망대 & 타워
46,십리포 해수욕장-->해변,3.5,십리포 해수욕장,해변
47,순천 드라마세트장 -->즐길거리 & 랜드마크,4.0,순천 드라마세트장,즐길거리 & 랜드마크

In [142]:
df_category = df_category[['관광지','분류','평점']]
df_category

                    관광지                                   분류   평점
0             암사동 선사주거지                              역사적인 장소  4.5
1                    화성                              역사적인 장소  4.0
2                   대부도                                    섬  4.0
3          국립현대미술관(과천관)                                아트뮤지엄  4.5
4                 독립기념관                                역사박물관  4.5
5                   공산성                역사적인 장소 • 즐길거리 & 랜드마크  4.5
6                  무령왕릉                              역사적인 장소  4.0
7                 충청수영성             역사적인 장소 • 성 • 경관이 좋은 산책로  5.0
8        천주교 대전교구 공세리성당                              종교적인 장소  4.5
9             팜카밀레 허브농원                              공원 • 가든  5.0
10        천주교 전주교구 전동성당                              종교적인 장소  4.0
11  무주 구천동계곡 방화동 가족휴양촌,            국립공원 • 자연 & 야생동물 서식지 • 계곡  5.0
12              순천만 갈대밭                                   공원  4.5
13                  용천사       역사적인 장소 • 종교적인 장소 • 경관이 좋은 산책로  4.0
14                   계림                            유서 깊은 산책로  4.0
15                  금오산                                   공원  4.5
16                 빙계계곡                         물길 • 산림 • 계곡  5.0
17              군위 삼존석굴                    역사적인 장소 • 종교적인 장소  4.5
18                주남저수지                        자연 & 야생동물 서식지  4.0
19                  청곡사                              종교적인 장소  3.5
20              고성 탈박물관                               전문 박물관  4.0
21                  임진성                                    성  3.5
22                다랑쉬오름                                   화산  5.0
23                  약천사                              종교적인 장소  4.5
24                제주 올레                              하이킹 트레일  4.5
25                월드컵공원                             기타 야외 활동  4.5
26    대한민국 국회의사당과 헌정기념관                               전문 박물관  4.0
27                  산사원                      전문 박물관 • 맥주 양조장  4.5
28                  탄금대                                   물길  4.5
29            지리산 산수유마을  유서 깊은 산책로 • 절경 드라이브 코스 • 경관이 좋은 산책로  4.0
30              항공우주박물관                                과학박물관  4.0
31               창녕 석빙고                              역사적인 장소  3.5
32                천제연폭포                                   폭포  4.0
33                  대둔산                                    산  4.5
34            그림이 있는 정원                                   가든  2.5
35             마이산 도립공원                                    산  4.5
36                  용궁사                              종교적인 장소  4.0
37                  한벽당                              역사적인 장소  4.0
38                 달아공원                        자연 & 야생동물 서식지  4.0
39          벌교 홍교, 대한다원                              산림 • 농장  4.5
40              안양 예술공원                                   공원  4.5
41         부천 활박물관과 궁도장                               전문 박물관  4.0
42              파주 프로방스                   특산물 & 기념품 가게 • 쇼핑몰  4.0
43                 융ㆍ건릉                              역사적인 장소  4.0
44                 자유공원                                   공원  4.0
45                통일전망대                             전망대 & 타워  4.0
46             십리포 해수욕장                                   해변  3.5
47           순천 드라마세트장                           즐길거리 & 랜드마크  4.0

In [145]:
df_category.to_csv('./data/1차.csv')

In [2]:
df_all = pd.read_csv('./data/1차.csv')
df_all

    Unnamed: 0                  관광지                                   분류   평점
0            0            암사동 선사주거지                              역사적인 장소  4.5
1            1                   화성                              역사적인 장소  4.0
2            2                  대부도                                    섬  4.0
3            3         국립현대미술관(과천관)                                아트뮤지엄  4.5
4            4                독립기념관                                역사박물관  4.5
5            5                  공산성                역사적인 장소 • 즐길거리 & 랜드마크  4.5
6            6                 무령왕릉                              역사적인 장소  4.0
7            7                충청수영성             역사적인 장소 • 성 • 경관이 좋은 산책로  5.0
8            8       천주교 대전교구 공세리성당                              종교적인 장소  4.5
9            9            팜카밀레 허브농원                              공원 • 가든  5.0
10          10        천주교 전주교구 전동성당                              종교적인 장소  4.0
11          11  무주 구천동계곡 방화동 가족휴양촌,            국립공원 • 자연 & 야생동물 서식지 • 계곡  5.0
12          12              순천만 갈대밭                                   공원  4.5
13          13                  용천사       역사적인 장소 • 종교적인 장소 • 경관이 좋은 산책로  4.0
14          14                   계림                            유서 깊은 산책로  4.0
15          15                  금오산                                   공원  4.5
16          16                 빙계계곡                         물길 • 산림 • 계곡  5.0
17          17              군위 삼존석굴                    역사적인 장소 • 종교적인 장소  4.5
18          18                주남저수지                        자연 & 야생동물 서식지  4.0
19          19                  청곡사                              종교적인 장소  3.5
20          20              고성 탈박물관                               전문 박물관  4.0
21          21                  임진성                                    성  3.5
22          22                다랑쉬오름                                   화산  5.0
23          23                  약천사                              종교적인 장소  4.5
24          24                제주 올레                              하이킹 트레일  4.5
25          25                월드컵공원                             기타 야외 활동  4.5
26          26    대한민국 국회의사당과 헌정기념관                               전문 박물관  4.0
27          27                  산사원                      전문 박물관 • 맥주 양조장  4.5
28          28                  탄금대                                   물길  4.5
29          29            지리산 산수유마을  유서 깊은 산책로 • 절경 드라이브 코스 • 경관이 좋은 산책로  4.0
30          30              항공우주박물관                                과학박물관  4.0
31          31               창녕 석빙고                              역사적인 장소  3.5
32          32                천제연폭포                                   폭포  4.0
33          33                  대둔산                                    산  4.5
34          34            그림이 있는 정원                                   가든  2.5
35          35             마이산 도립공원                                    산  4.5
36          36                  용궁사                              종교적인 장소  4.0
37          37                  한벽당                              역사적인 장소  4.0
38          38                 달아공원                        자연 & 야생동물 서식지  4.0
39          39          벌교 홍교, 대한다원                              산림 • 농장  4.5
40          40              안양 예술공원                                   공원  4.5
41          41         부천 활박물관과 궁도장                               전문 박물관  4.0
42          42              파주 프로방스                   특산물 & 기념품 가게 • 쇼핑몰  4.0
43          43                 융ㆍ건릉                              역사적인 장소  4.0
44          44                 자유공원                                   공원  4.0
45          45                통일전망대                             전망대 & 타워  4.0
46          46             십리포 해수욕장                                   해변  3.5
47          47           순천 드라마세트장                           즐길거리 & 랜드마크  4.0

In [16]:
options=webdriver.ChromeOptions()
options.add_argument('user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36')
options.add_experimental_option("excludeSwitches", ["enable-logging"])


driver=webdriver.Chrome()
url='https://map.kakao.com/?nil_profile=title&nil_src=local'

address = []
for i in range(len(df_all)):
    driver.get(url)
    search=df_all.관광지[i]
    driver.find_element_by_css_selector('#search\.keyword\.query').send_keys(search)
    driver.find_element_by_css_selector('#search\.keyword\.query').send_keys(Keys.ENTER)
    time.sleep(2)
    try: 
        driver.switch_to.window(driver.window_handles[-1])
        soup=BeautifulSoup(driver.page_source,'html.parser')
        mydata=soup.find('div','address-text')
        address.append(search + '-->' + item.get_text().strip())
        driver.switch_to.window(driver.window_handles[-1])
        driver.close()
        driver.switch_to.window(driver.window_handles[0])
        driver.back()
        time.sleep(1)
    except:
        pass

WebDriverException: Message: chrome not reachable
  (Session info: chrome=102.0.5005.61)
Stacktrace:
Backtrace:
	Ordinal0 [0x007CB8F3+2406643]
	Ordinal0 [0x0075AF31+1945393]
	Ordinal0 [0x0064C610+837136]
	Ordinal0 [0x00640442+787522]
	Ordinal0 [0x00640C78+789624]
	Ordinal0 [0x006424B2+795826]
	Ordinal0 [0x0063BF09+769801]
	Ordinal0 [0x0064DAC0+842432]
	Ordinal0 [0x006A3E62+1195618]
	Ordinal0 [0x00694096+1130646]
	Ordinal0 [0x0066E636+976438]
	Ordinal0 [0x0066F546+980294]
	GetHandleVerifier [0x00A39612+2498066]
	GetHandleVerifier [0x00A2C920+2445600]
	GetHandleVerifier [0x00864F2A+579370]
	GetHandleVerifier [0x00863D36+574774]
	Ordinal0 [0x00761C0B+1973259]
	Ordinal0 [0x00766688+1992328]
	Ordinal0 [0x00766775+1992565]
	Ordinal0 [0x0076F8D1+2029777]
	BaseThreadInitThunk [0x75C6FA29+25]
	RtlGetAppContainerNamedObjectPath [0x779A7A7E+286]
	RtlGetAppContainerNamedObjectPath [0x779A7A4E+238]

In [59]:
options=webdriver.ChromeOptions()
options.add_argument('user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36')
options.add_experimental_option("excludeSwitches", ["enable-logging"])


driver=webdriver.Chrome()
url='https://www.tripadvisor.co.kr/'

address = []
for i in range(len(df_2)):
    driver.get(url)
    search=df_2.여행지[i]
    driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(search)
    driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(Keys.ENTER)
    driver.switch_to.window(driver.window_handles[-1])
    time.sleep(2)
    try: 
        driver.switch_to.window(driver.window_handles[-1])
        soup=BeautifulSoup(driver.page_source,'html.parser')
        mydata = soup.find_all('div','address-text')
        address.append(search + '-->' + mydata[1].get_text().strip())
        driver.back()
        time.sleep(1)
    except:
        address.append('결과 없음')

In [60]:
len(address)

25

In [35]:
options=webdriver.ChromeOptions()
options.add_argument('user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36')
options.add_experimental_option("excludeSwitches", ["enable-logging"])


driver=webdriver.Chrome()
url='https://www.tripadvisor.co.kr/'

address3 = []
for i in range(len(df_3)):
    driver.get(url)
    search=df_3.여행지[i]
    driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(search)
    driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(Keys.ENTER)
    time.sleep(2)
    try: 
        soup=BeautifulSoup(driver.page_source,'html.parser')
        mydata = soup.find_all('div','address-text')
        address3.append(search + '-->' + mydata[2].get_text().strip())
        driver.back()
        time.sleep(1)
    except:
        address3.append('결과 없음')

In [37]:
address3

['결과 없음',
 '대한민국 국회의사당과 헌정기념관-->영등포구 국회대로68길 18, 서울, 대한민국',
 '산사원-->화현면 화현리 512, 포천, 경기도, 대한민국',
 '탄금대-->중앙탑면 탑정안길, 충주, 충청북도, 대한민국',
 '지리산 산수유마을-->6-12, Wianwolgye-gil, 구례, 전라남도, 대한민국',
 '항공우주박물관-->사남면 공단1로 78, 사천, 경상남도, 대한민국',
 '결과 없음',
 '천제연폭포-->천제연로 132, 서귀포, 제주도, 대한민국']

In [38]:
options=webdriver.ChromeOptions()
options.add_argument('user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36')
options.add_experimental_option("excludeSwitches", ["enable-logging"])


driver=webdriver.Chrome()
url='https://www.tripadvisor.co.kr/'

address4 = []
for i in range(len(df_4)):
    driver.get(url)
    search=df_4.여행지[i]
    driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(search)
    driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(Keys.ENTER)
    time.sleep(2)
    try:
        some_tag = driver.find_element_by_css_selector('#BODY_BLOCK_JQUERY_REFLOW > div.page > div > div.ui_container.main_wrap > div > div > div > div > div.content_column.ui_column.is-9-desktop.is-12-tablet.is-12-mobile > div > div.ui_columns.sections_wrapper > div > div.prw_rup.prw_search_search_results.ajax-content > div > div.main_content.ui_column.is-12 > div > div:nth-child(2) > div > div > div:nth-child(4) > div > div > div > div.ui_column.is-9-desktop.is-8-mobile.is-9-tablet.content-block-column > div')
        action = ActionChains(driver)
        action.move_to_element(some_tag).perform()
        soup=BeautifulSoup(driver.page_source,'html.parser')
        mydata = soup.find_all('div','address-text')
        address4.append(search + '-->' + mydata[3].get_text().strip())
        driver.back()
        time.sleep(1)
    except:
        address3.append('결과 없음')

In [39]:
address4

['대둔산-->운주면 대둔산공원길 23, 완주, 전라북도, 대한민국']

In [40]:
options=webdriver.ChromeOptions()
options.add_argument('user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36')
options.add_experimental_option("excludeSwitches", ["enable-logging"])


driver=webdriver.Chrome()
url='https://www.tripadvisor.co.kr/'

address5 = []
for i in range(len(df_5)):
    driver.get(url)
    search=df_5.여행지[i]
    driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(search)
    driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(Keys.ENTER)
    time.sleep(2)
    try:
        some_tag = driver.find_element_by_css_selector('#BODY_BLOCK_JQUERY_REFLOW > div.page > div > div.ui_container.main_wrap > div > div > div > div > div.content_column.ui_column.is-9-desktop.is-12-tablet.is-12-mobile > div > div.ui_columns.sections_wrapper > div > div.prw_rup.prw_search_search_results.ajax-content > div > div.main_content.ui_column.is-12 > div > div:nth-child(2) > div > div > div:nth-child(5) > div > div > div > div.ui_column.is-9-desktop.is-8-mobile.is-9-tablet.content-block-column > div')
        action = ActionChains(driver)
        action.move_to_element(some_tag).perform()
        soup=BeautifulSoup(driver.page_source,'html.parser')
        mydata = soup.find_all('div','address-text')
        address5.append(search + '-->' + mydata[4].get_text().strip())
        driver.back()
        time.sleep(1)
    except:
        address5.append('결과 없음')

In [41]:
address5

['그림이 있는 정원-->광천읍 충서로400번길 102-36, 홍성, 충청남도, 대한민국',
 '마이산 도립공원-->진안, 전라북도, 대한민국']

In [42]:
options=webdriver.ChromeOptions()
options.add_argument('user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36')
options.add_experimental_option("excludeSwitches", ["enable-logging"])


driver=webdriver.Chrome()
url='https://www.tripadvisor.co.kr/'

address6 = []
for i in range(len(df_6)):
    driver.get(url)
    search=df_6.여행지[i]
    driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(search)
    driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(Keys.ENTER)
    time.sleep(2)
    try:
        some_tag = driver.find_element_by_css_selector('#BODY_BLOCK_JQUERY_REFLOW > div.page > div > div.ui_container.main_wrap > div > div > div > div > div.content_column.ui_column.is-9-desktop.is-12-tablet.is-12-mobile > div > div.ui_columns.sections_wrapper > div > div.prw_rup.prw_search_search_results.ajax-content > div > div.main_content.ui_column.is-12 > div > div:nth-child(2) > div > div > div:nth-child(7) > div > div > div > div.ui_column.is-9-desktop.is-8-mobile.is-9-tablet.content-block-column > div')
        action = ActionChains(driver)
        action.move_to_element(some_tag).perform()
        soup=BeautifulSoup(driver.page_source,'html.parser')
        mydata = soup.find_all('div','address-text')
        address6.append(search + '-->' + mydata[5].get_text().strip())
        driver.back()
        time.sleep(1)
    except:
        address6.append('결과 없음')

In [43]:
address6

['용궁사-->중구 운남로 199-1, 인천, 대한민국',
 '한벽당-->완산구 기린대로 2, 전주, 전라북도, 대한민국',
 '달아공원-->산양읍 산양일주로 1115, 통영, 경상남도, 대한민국']

In [44]:
options=webdriver.ChromeOptions()
options.add_argument('user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36')
options.add_experimental_option("excludeSwitches", ["enable-logging"])


driver=webdriver.Chrome()
url='https://www.tripadvisor.co.kr/'

address8 = []
for i in range(len(df_8)):
    driver.get(url)
    search=df_8.여행지[i]
    driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(search)
    driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(Keys.ENTER)
    time.sleep(2)
    try:
        some_tag = driver.find_element_by_css_selector('#BODY_BLOCK_JQUERY_REFLOW > div.page > div > div.ui_container.main_wrap > div > div > div > div > div.content_column.ui_column.is-9-desktop.is-12-tablet.is-12-mobile > div > div.ui_columns.sections_wrapper > div > div.prw_rup.prw_search_search_results.ajax-content > div > div.main_content.ui_column.is-12 > div > div:nth-child(2) > div > div > div:nth-child(9) > div > div > div > div.ui_column.is-9-desktop.is-8-mobile.is-9-tablet.content-block-column > div')
        action = ActionChains(driver)
        action.move_to_element(some_tag).perform()
        soup=BeautifulSoup(driver.page_source,'html.parser')
        mydata = soup.find_all('div','address-text')
        address8.append(search + '-->' + mydata[7].get_text().strip())
        driver.back()
        time.sleep(1)
    except:
        address8.append('결과 없음')

In [48]:
address8 = address8[:1]

In [49]:
address8

['벌교 홍교, 대한다원-->해맞이해안로 1752, 제주, 제주도, 대한민국']

In [46]:
options=webdriver.ChromeOptions()
options.add_argument('user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36')
options.add_experimental_option("excludeSwitches", ["enable-logging"])


driver=webdriver.Chrome()
url='https://www.tripadvisor.co.kr/'

address1 = []
for i in range(len(df_one)):
    driver.get(url)
    search=df_one.여행지[i]
    driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(search)
    driver.find_element_by_css_selector('#lithium-root > main > div.dqRmR.dcDXR.dJjeH > div > div > div.weiIG.Z0.Wh.fRhqZ > form > input.fhEMT._G.B-.z._J.Cj.R0').send_keys(Keys.ENTER)
    driver.switch_to.window(driver.window_handles[-1])
    time.sleep(2)
    try: 
        driver.switch_to.window(driver.window_handles[-1])
        soup=BeautifulSoup(driver.page_source,'html.parser')
        mydata = soup.find_all('div','address-text')
        address1.append(search + '-->' + mydata[0].get_text().strip())
        driver.back()
        time.sleep(1)
    except:
        address1.append('결과 없음')

In [47]:
address1

['안양 예술공원-->만안구 예술공원로 131, 안양, 경기도, 대한민국',
 '부천 활박물관과 궁도장-->8, Chunui-dong, Wonmi-gu, 부천, 경기도, 대한민국',
 '파주 프로방스-->탄현면 성동리 82-1, 파주, 경기도, 대한민국',
 '융ㆍ건릉-->화성, 경기도, 대한민국',
 '자유공원-->중구 신포로27번길 80, 인천, 대한민국',
 '통일전망대-->탄현면 필승로 369, 파주, 경기도, 대한민국',
 '십리포 해수욕장-->영흥면 영흥북로 420-26, 인천, 대한민국',
 '순천 드라마세트장 -->비례골길 24, 순천, 전라남도, 대한민국']

In [61]:
address_all = address+address3+address4+address5+address6+address8+address1
address_all

['암사동 선사주거지-->강동구 올림픽로 875, 서울, 대한민국',
 '화성-->팔달구 정조로 825, 수원, 경기도, 대한민국',
 '대부도-->2-3 Kitanomarukoen, 치요다, 도쿄, 도쿄도, 관동, 일본',
 '국립현대미술관(과천관)-->광명로 313, 과천, 경기도, 대한민국',
 '결과 없음',
 '공산성-->280 Ungjin-ro, Gongju-si, Chungcheongnam-do, 공주, 충청남도, 대한민국',
 '무령왕릉-->왕릉로 37, 공주, 충청남도, 대한민국',
 '충청수영성-->오천면 소성리 931, 보령, 충청남도, 대한민국',
 '천주교 대전교구 공세리성당-->인주면 공세리성당길 10, 아산, 충청남도, 대한민국',
 '팜카밀레 허브농원-->남면 우운길 56-19, 태안, 충청남도, 대한민국',
 '천주교 전주교구 전동성당-->200-1, Jeon-dong, Wansan-gu, 전주, 전라북도, 대한민국',
 '무주 구천동계곡 방화동 가족휴양촌,-->설천면 구천동1로 159, 무주, 전라북도, 대한민국',
 '순천만 갈대밭-->대대동 162-2, 순천, 전라남도, 대한민국',
 '용천사-->해보면 용천사길 209, 함평, 전라남도, 대한민국',
 '계림-->1, Gyo-dong, 경주, 경상북도, 대한민국',
 '결과 없음',
 '빙계계곡-->춘산면 빙계리 896, 의성, 경상북도, 대한민국',
 '군위 삼존석굴-->302, Namsan-ri, Bugye-myeon, 군위, 경상북도, 대한민국',
 '주남저수지-->의창구 동읍 주남로101번길 26, 창원, 경상남도, 대한민국',
 '청곡사-->금산면 월아산로1440번길 138, 진주, 경상남도, 대한민국',
 '고성 탈박물관-->고성읍 율대리 666-18, 경상남도, 대한민국',
 '임진성-->남면 상가리 291, 남해, 경상남도, 대한민국',
 '다랑쉬오름-->구좌읍 세화리 산 6, 제주, 제주도, 대한민국',
 '약천사-->대포동 1165, 서귀포, 제주도, 대한민국',
 '제주 올레-->제주도, 대한민국',
 '결과 없음',
 '대한민국 국회의사당과 헌정기념관-->영등포구 국회대로68길 18, 서울, 대한민국',
 '산사원-->화현면 화현리 512, 포천, 경기도, 대한민국',
 '탄금대-->중앙탑면 탑정안길, 충주, 충청북도, 대한민국',
 '지리산 산수유마을-->6-12, Wianwolgye-gil, 구례, 전라남도, 대한민국',
 '항공우주박물관-->사남면 공단1로 78, 사천, 경상남도, 대한민국',
 '결과 없음',
 '천제연폭포-->천제연로 132, 서귀포, 제주도, 대한민국',
 '대둔산-->운주면 대둔산공원길 23, 완주, 전라북도, 대한민국',
 '그림이 있는 정원-->광천읍 충서로400번길 102-36, 홍성, 충청남도, 대한민국',
 '마이산 도립공원-->진안, 전라북도, 대한민국',
 '용궁사-->중구 운남로 199-1, 인천, 대한민국',
 '한벽당-->완산구 기린대로 2, 전주, 전라북도, 대한민국',
 '달아공원-->산양읍 산양일주로 1115, 통영, 경상남도, 대한민국',
 '벌교 홍교, 대한다원-->해맞이해안로 1752, 제주, 제주도, 대한민국',
 '안양 예술공원-->만안구 예술공원로 131, 안양, 경기도, 대한민국',
 '부천 활박물관과 궁도장-->8, Chunui-dong, Wonmi-gu, 부천, 경기도, 대한민국',
 '파주 프로방스-->탄현면 성동리 82-1, 파주, 경기도, 대한민국',
 '융ㆍ건릉-->화성, 경기도, 대한민국',
 '자유공원-->중구 신포로27번길 80, 인천, 대한민국',
 '통일전망대-->탄현면 필승로 369, 파주, 경기도, 대한민국',
 '십리포 해수욕장-->영흥면 영흥북로 420-26, 인천, 대한민국',
 '순천 드라마세트장 -->비례골길 24, 순천, 전라남도, 대한민국']

In [51]:
len(address)

48

In [84]:
address_df = pd.DataFrame(address_all)

In [85]:
address_df

                                                    0
0                  암사동 선사주거지-->강동구 올림픽로 875, 서울, 대한민국
1                     화성-->팔달구 정조로 825, 수원, 경기도, 대한민국
2      대부도-->2-3 Kitanomarukoen, 치요다, 도쿄, 도쿄도, 관동, 일본
3               국립현대미술관(과천관)-->광명로 313, 과천, 경기도, 대한민국
4                                               결과 없음
5   공산성-->280 Ungjin-ro, Gongju-si, Chungcheongnam...
6                       무령왕릉-->왕릉로 37, 공주, 충청남도, 대한민국
7                 충청수영성-->오천면 소성리 931, 보령, 충청남도, 대한민국
8      천주교 대전교구 공세리성당-->인주면 공세리성당길 10, 아산, 충청남도, 대한민국
9            팜카밀레 허브농원-->남면 우운길 56-19, 태안, 충청남도, 대한민국
10  천주교 전주교구 전동성당-->200-1, Jeon-dong, Wansan-gu, 전...
11  무주 구천동계곡 방화동 가족휴양촌,-->설천면 구천동1로 159, 무주, 전라북도,...
12                순천만 갈대밭-->대대동 162-2, 순천, 전라남도, 대한민국
13                 용천사-->해보면 용천사길 209, 함평, 전라남도, 대한민국
14                   계림-->1, Gyo-dong, 경주, 경상북도, 대한민국
15                                              결과 없음
16                 빙계계곡-->춘산면 빙계리 896, 의성, 경상북도, 대한민국
17  군위 삼존석굴-->302, Namsan-ri, Bugye-myeon, 군위, 경상북...
18         주남저수지-->의창구 동읍 주남로101번길 26, 창원, 경상남도, 대한민국
19           청곡사-->금산면 월아산로1440번길 138, 진주, 경상남도, 대한민국
20               고성 탈박물관-->고성읍 율대리 666-18, 경상남도, 대한민국
21                   임진성-->남면 상가리 291, 남해, 경상남도, 대한민국
22                 다랑쉬오름-->구좌읍 세화리 산 6, 제주, 제주도, 대한민국
23                     약천사-->대포동 1165, 서귀포, 제주도, 대한민국
24                                  제주 올레-->제주도, 대한민국
25                                              결과 없음
26      대한민국 국회의사당과 헌정기념관-->영등포구 국회대로68길 18, 서울, 대한민국
27                   산사원-->화현면 화현리 512, 포천, 경기도, 대한민국
28                    탄금대-->중앙탑면 탑정안길, 충주, 충청북도, 대한민국
29   지리산 산수유마을-->6-12, Wianwolgye-gil, 구례, 전라남도, 대한민국
30              항공우주박물관-->사남면 공단1로 78, 사천, 경상남도, 대한민국
31                                              결과 없음
32                   천제연폭포-->천제연로 132, 서귀포, 제주도, 대한민국
33                대둔산-->운주면 대둔산공원길 23, 완주, 전라북도, 대한민국
34    그림이 있는 정원-->광천읍 충서로400번길 102-36, 홍성, 충청남도, 대한민국
35                          마이산 도립공원-->진안, 전라북도, 대한민국
36                       용궁사-->중구 운남로 199-1, 인천, 대한민국
37                   한벽당-->완산구 기린대로 2, 전주, 전라북도, 대한민국
38              달아공원-->산양읍 산양일주로 1115, 통영, 경상남도, 대한민국
39           벌교 홍교, 대한다원-->해맞이해안로 1752, 제주, 제주도, 대한민국
40             안양 예술공원-->만안구 예술공원로 131, 안양, 경기도, 대한민국
41  부천 활박물관과 궁도장-->8, Chunui-dong, Wonmi-gu, 부천, 경...
42              파주 프로방스-->탄현면 성동리 82-1, 파주, 경기도, 대한민국
43                               융ㆍ건릉-->화성, 경기도, 대한민국
44                     자유공원-->중구 신포로27번길 80, 인천, 대한민국
45                 통일전망대-->탄현면 필승로 369, 파주, 경기도, 대한민국
46               십리포 해수욕장-->영흥면 영흥북로 420-26, 인천, 대한민국
47               순천 드라마세트장 -->비례골길 24, 순천, 전라남도, 대한민국

In [86]:
address_df.to_csv('./data/주소.csv')

In [87]:
address_df['행정구역'] = address_df[0].str.split(',').str[-2]

In [88]:
address_df['관광지'] = address_df[0].str.split('-->').str[0]
address_df

,0,행정구역,관광지
0,"암사동 선사주거지-->강동구 올림픽로 875, 서울, 대한민국",서울,암사동 선사주거지
1,"화성-->팔달구 정조로 825, 수원, 경기도, 대한민국",경기도,화성
2,"대부도-->2-3 Kitanomarukoen, 치요다, 도쿄, 도쿄도, 관동, 일본",관동,대부도
3,"국립현대미술관(과천관)-->광명로 313, 과천, 경기도, 대한민국",경기도,국립현대미술관(과천관)
4,결과 없음,NaN,결과 없음
5,"공산성-->280 Ungjin-ro, Gongju-si, Chungcheongnam...",충청남도,공산성
6,"무령왕릉-->왕릉로 37, 공주, 충청남도, 대한민국",충청남도,무령왕릉
7,"충청수영성-->오천면 소성리 931, 보령, 충청남도, 대한민국",충청남도,충청수영성
8,"천주교 대전교구 공세리성당-->인주면 공세리성당길 10, 아산, 충청남도, 대한민국",충청남도,천주교 대전교구 공세리성당
9,"팜카밀레 허브농원-->남면 우운길 56-19, 태안, 충청남도, 대한민국",충청남도,팜카밀레 허브농원
10,"천주교 전주교구 전동성당-->200-1, Jeon-dong, Wansan-gu, 전...",전라북도,천주교 전주교구 전동성당
11,"무주 구천동계곡 방화동 가족휴양촌,-->설천면 구천동1로 159, 무주, 전라북도,...",전라북도,"무주 구천동계곡 방화동 가족휴양촌,"
12,"순천만 갈대밭-->대대동 162-2, 순천, 전라남도, 대한민국",전라남도,순천만 갈대밭
13,"용천사-->해보면 용천사길 209, 함평, 전라남도, 대한민국",전라남도,용천사
14,"계림-->1, Gyo-dong, 경주, 경상북도, 대한민국",경상북도,계림
15,결과 없음,NaN,결과 없음
16,"빙계계곡-->춘산면 빙계리 896, 의성, 경상북도, 대한민국",경상북도,빙계계곡
17,"군위 삼존석굴-->302, Namsan-ri, Bugye-myeon, 군위, 경상북...",경상북도,군위 삼존석굴
18,"주남저수지-->의창구 동읍 주남로101번길 26, 창원, 경상남도, 대한민국",경상남도,주남저수지
19,"청곡사-->금산면 월아산로1440번길 138, 진주, 경상남도, 대한민국",경상남도,청곡사
20,"고성 탈박물관-->고성읍 율대리 666-18, 경상남도, 대한민국",경상남도,고성 탈박물관
21,"임진성-->남면 상가리 291, 남해, 경상남도, 대한민국",경상남도,임진성
22,"다랑쉬오름-->구좌읍 세화리 산 6, 제주, 제주도, 대한민국",제주도,다랑쉬오름
23,"약천사-->대포동 1165, 서귀포, 제주도, 대한민국",제주도,약천사
24,"제주 올레-->제주도, 대한민국",제주 올레-->제주도,제주 올레
25,결과 없음,NaN,결과 없음
26,"대한민국 국회의사당과 헌정기념관-->영등포구 국회대로68길 18, 서울, 대한민국",서울,대한민국 국회의사당과 헌정기념관
27,"산사원-->화현면 화현리 512, 포천, 경기도, 대한민국",경기도,산사원
28,"탄금대-->중앙탑면 탑정안길, 충주, 충청북도, 대한민국",충청북도,탄금대
29,"지리산 산수유마을-->6-12, Wianwolgye-gil, 구례, 전라남도, 대한민국",전라남도,지리산 산수유마을
30,"항공우주박물관-->사남면 공단1로 78, 사천, 경상남도, 대한민국",경상남도,항공우주박물관
31,결과 없음,NaN,결과 없음
32,"천제연폭포-->천제연로 132, 서귀포, 제주도, 대한민국",제주도,천제연폭포
33,"대둔산-->운주면 대둔산공원길 23, 완주, 전라북도, 대한민국",전라북도,대둔산
34,"그림이 있는 정원-->광천읍 충서로400번길 102-36, 홍성, 충청남도, 대한민국",충청남도,그림이 있는 정원
35,"마이산 도립공원-->진안, 전라북도, 대한민국",전라북도,마이산 도립공원
36,"용궁사-->중구 운남로 199-1, 인천, 대한민국",인천,용궁사
37,"한벽당-->완산구 기린대로 2, 전주, 전라북도, 대한민국",전라북도,한벽당
38,"달아공원-->산양읍 산양일주로 1115, 통영, 경상남도, 대한민국",경상남도,달아공원
39,"벌교 홍교, 대한다원-->해맞이해안로 1752, 제주, 제주도, 대한민국",제주도,"벌교 홍교, 대한다원"
40,"안양 예술공원-->만안구 예술공원로 131, 안양, 경기도, 대한민국",경기도,안양 예술공원
41,"부천 활박물관과 궁도장-->8, Chunui-dong, Wonmi-gu, 부천, 경...",경기도,부천 활박물관과 궁도장
42,"파주 프로방스-->탄현면 성동리 82-1, 파주, 경기도, 대한민국",경기도,파주 프로방스
43,"융ㆍ건릉-->화성, 경기도, 대한민국",경기도,융ㆍ건릉
44,"자유공원-->중구 신포로27번길 80, 인천, 대한민국",인천,자유공원
45,"통일전망대-->탄현면 필승로 369, 파주, 경기도, 대한민국",경기도,통일전망대
46,"십리포 해수욕장-->영흥면 영흥북로 420-26, 인천, 대한민국",인천,십리포 해수욕장
47,"순천 드라마세트장 -->비례골길 24, 순천, 전라남도, 대한민국",전라남도,순천 드라마세트장

In [94]:
address_df.loc[31][0] = '창녕 석빙고-->경상남도 창녕군 창녕읍 송현리 288'
address_df.loc[25][0] = '월드컵공원-->서울특별시 마포구 월드컵로 243-60'
address_df.loc[4][0] = '독립기념관-->충남 천안시 동남구 목천읍 독립기념관로 1'
address_df.loc[15][0] = '금오산-->경북 구미시 남통동 288-2'

In [95]:
address_df

,0,행정구역,관광지
0,"암사동 선사주거지-->강동구 올림픽로 875, 서울, 대한민국",서울,암사동 선사주거지
1,"화성-->팔달구 정조로 825, 수원, 경기도, 대한민국",경기도,화성
2,"대부도-->2-3 Kitanomarukoen, 치요다, 도쿄, 도쿄도, 관동, 일본",관동,대부도
3,"국립현대미술관(과천관)-->광명로 313, 과천, 경기도, 대한민국",경기도,국립현대미술관(과천관)
4,독립기념관-->충남 천안시 동남구 목천읍 독립기념관로 1,NaN,결과 없음
5,"공산성-->280 Ungjin-ro, Gongju-si, Chungcheongnam...",충청남도,공산성
6,"무령왕릉-->왕릉로 37, 공주, 충청남도, 대한민국",충청남도,무령왕릉
7,"충청수영성-->오천면 소성리 931, 보령, 충청남도, 대한민국",충청남도,충청수영성
8,"천주교 대전교구 공세리성당-->인주면 공세리성당길 10, 아산, 충청남도, 대한민국",충청남도,천주교 대전교구 공세리성당
9,"팜카밀레 허브농원-->남면 우운길 56-19, 태안, 충청남도, 대한민국",충청남도,팜카밀레 허브농원
10,"천주교 전주교구 전동성당-->200-1, Jeon-dong, Wansan-gu, 전...",전라북도,천주교 전주교구 전동성당
11,"무주 구천동계곡 방화동 가족휴양촌,-->설천면 구천동1로 159, 무주, 전라북도,...",전라북도,"무주 구천동계곡 방화동 가족휴양촌,"
12,"순천만 갈대밭-->대대동 162-2, 순천, 전라남도, 대한민국",전라남도,순천만 갈대밭
13,"용천사-->해보면 용천사길 209, 함평, 전라남도, 대한민국",전라남도,용천사
14,"계림-->1, Gyo-dong, 경주, 경상북도, 대한민국",경상북도,계림
15,금오산-->경북 구미시 남통동 288-2,NaN,결과 없음
16,"빙계계곡-->춘산면 빙계리 896, 의성, 경상북도, 대한민국",경상북도,빙계계곡
17,"군위 삼존석굴-->302, Namsan-ri, Bugye-myeon, 군위, 경상북...",경상북도,군위 삼존석굴
18,"주남저수지-->의창구 동읍 주남로101번길 26, 창원, 경상남도, 대한민국",경상남도,주남저수지
19,"청곡사-->금산면 월아산로1440번길 138, 진주, 경상남도, 대한민국",경상남도,청곡사
20,"고성 탈박물관-->고성읍 율대리 666-18, 경상남도, 대한민국",경상남도,고성 탈박물관
21,"임진성-->남면 상가리 291, 남해, 경상남도, 대한민국",경상남도,임진성
22,"다랑쉬오름-->구좌읍 세화리 산 6, 제주, 제주도, 대한민국",제주도,다랑쉬오름
23,"약천사-->대포동 1165, 서귀포, 제주도, 대한민국",제주도,약천사
24,"제주 올레-->제주도, 대한민국",제주 올레-->제주도,제주 올레
25,월드컵공원-->서울특별시 마포구 월드컵로 243-60,NaN,결과 없음
26,"대한민국 국회의사당과 헌정기념관-->영등포구 국회대로68길 18, 서울, 대한민국",서울,대한민국 국회의사당과 헌정기념관
27,"산사원-->화현면 화현리 512, 포천, 경기도, 대한민국",경기도,산사원
28,"탄금대-->중앙탑면 탑정안길, 충주, 충청북도, 대한민국",충청북도,탄금대
29,"지리산 산수유마을-->6-12, Wianwolgye-gil, 구례, 전라남도, 대한민국",전라남도,지리산 산수유마을
30,"항공우주박물관-->사남면 공단1로 78, 사천, 경상남도, 대한민국",경상남도,항공우주박물관
31,창녕 석빙고-->경상남도 창녕군 창녕읍 송현리 288,NaN,결과 없음
32,"천제연폭포-->천제연로 132, 서귀포, 제주도, 대한민국",제주도,천제연폭포
33,"대둔산-->운주면 대둔산공원길 23, 완주, 전라북도, 대한민국",전라북도,대둔산
34,"그림이 있는 정원-->광천읍 충서로400번길 102-36, 홍성, 충청남도, 대한민국",충청남도,그림이 있는 정원
35,"마이산 도립공원-->진안, 전라북도, 대한민국",전라북도,마이산 도립공원
36,"용궁사-->중구 운남로 199-1, 인천, 대한민국",인천,용궁사
37,"한벽당-->완산구 기린대로 2, 전주, 전라북도, 대한민국",전라북도,한벽당
38,"달아공원-->산양읍 산양일주로 1115, 통영, 경상남도, 대한민국",경상남도,달아공원
39,"벌교 홍교, 대한다원-->해맞이해안로 1752, 제주, 제주도, 대한민국",제주도,"벌교 홍교, 대한다원"
40,"안양 예술공원-->만안구 예술공원로 131, 안양, 경기도, 대한민국",경기도,안양 예술공원
41,"부천 활박물관과 궁도장-->8, Chunui-dong, Wonmi-gu, 부천, 경...",경기도,부천 활박물관과 궁도장
42,"파주 프로방스-->탄현면 성동리 82-1, 파주, 경기도, 대한민국",경기도,파주 프로방스
43,"융ㆍ건릉-->화성, 경기도, 대한민국",경기도,융ㆍ건릉
44,"자유공원-->중구 신포로27번길 80, 인천, 대한민국",인천,자유공원
45,"통일전망대-->탄현면 필승로 369, 파주, 경기도, 대한민국",경기도,통일전망대
46,"십리포 해수욕장-->영흥면 영흥북로 420-26, 인천, 대한민국",인천,십리포 해수욕장
47,"순천 드라마세트장 -->비례골길 24, 순천, 전라남도, 대한민국",전라남도,순천 드라마세트장

In [96]:
address_df.to_csv('./data/주소().csv')

In [97]:
address_df

,0,행정구역,관광지
0,"암사동 선사주거지-->강동구 올림픽로 875, 서울, 대한민국",서울,암사동 선사주거지
1,"화성-->팔달구 정조로 825, 수원, 경기도, 대한민국",경기도,화성
2,"대부도-->2-3 Kitanomarukoen, 치요다, 도쿄, 도쿄도, 관동, 일본",관동,대부도
3,"국립현대미술관(과천관)-->광명로 313, 과천, 경기도, 대한민국",경기도,국립현대미술관(과천관)
4,독립기념관-->충남 천안시 동남구 목천읍 독립기념관로 1,NaN,결과 없음
5,"공산성-->280 Ungjin-ro, Gongju-si, Chungcheongnam...",충청남도,공산성
6,"무령왕릉-->왕릉로 37, 공주, 충청남도, 대한민국",충청남도,무령왕릉
7,"충청수영성-->오천면 소성리 931, 보령, 충청남도, 대한민국",충청남도,충청수영성
8,"천주교 대전교구 공세리성당-->인주면 공세리성당길 10, 아산, 충청남도, 대한민국",충청남도,천주교 대전교구 공세리성당
9,"팜카밀레 허브농원-->남면 우운길 56-19, 태안, 충청남도, 대한민국",충청남도,팜카밀레 허브농원
10,"천주교 전주교구 전동성당-->200-1, Jeon-dong, Wansan-gu, 전...",전라북도,천주교 전주교구 전동성당
11,"무주 구천동계곡 방화동 가족휴양촌,-->설천면 구천동1로 159, 무주, 전라북도,...",전라북도,"무주 구천동계곡 방화동 가족휴양촌,"
12,"순천만 갈대밭-->대대동 162-2, 순천, 전라남도, 대한민국",전라남도,순천만 갈대밭
13,"용천사-->해보면 용천사길 209, 함평, 전라남도, 대한민국",전라남도,용천사
14,"계림-->1, Gyo-dong, 경주, 경상북도, 대한민국",경상북도,계림
15,금오산-->경북 구미시 남통동 288-2,NaN,결과 없음
16,"빙계계곡-->춘산면 빙계리 896, 의성, 경상북도, 대한민국",경상북도,빙계계곡
17,"군위 삼존석굴-->302, Namsan-ri, Bugye-myeon, 군위, 경상북...",경상북도,군위 삼존석굴
18,"주남저수지-->의창구 동읍 주남로101번길 26, 창원, 경상남도, 대한민국",경상남도,주남저수지
19,"청곡사-->금산면 월아산로1440번길 138, 진주, 경상남도, 대한민국",경상남도,청곡사
20,"고성 탈박물관-->고성읍 율대리 666-18, 경상남도, 대한민국",경상남도,고성 탈박물관
21,"임진성-->남면 상가리 291, 남해, 경상남도, 대한민국",경상남도,임진성
22,"다랑쉬오름-->구좌읍 세화리 산 6, 제주, 제주도, 대한민국",제주도,다랑쉬오름
23,"약천사-->대포동 1165, 서귀포, 제주도, 대한민국",제주도,약천사
24,"제주 올레-->제주도, 대한민국",제주 올레-->제주도,제주 올레
25,월드컵공원-->서울특별시 마포구 월드컵로 243-60,NaN,결과 없음
26,"대한민국 국회의사당과 헌정기념관-->영등포구 국회대로68길 18, 서울, 대한민국",서울,대한민국 국회의사당과 헌정기념관
27,"산사원-->화현면 화현리 512, 포천, 경기도, 대한민국",경기도,산사원
28,"탄금대-->중앙탑면 탑정안길, 충주, 충청북도, 대한민국",충청북도,탄금대
29,"지리산 산수유마을-->6-12, Wianwolgye-gil, 구례, 전라남도, 대한민국",전라남도,지리산 산수유마을
30,"항공우주박물관-->사남면 공단1로 78, 사천, 경상남도, 대한민국",경상남도,항공우주박물관
31,창녕 석빙고-->경상남도 창녕군 창녕읍 송현리 288,NaN,결과 없음
32,"천제연폭포-->천제연로 132, 서귀포, 제주도, 대한민국",제주도,천제연폭포
33,"대둔산-->운주면 대둔산공원길 23, 완주, 전라북도, 대한민국",전라북도,대둔산
34,"그림이 있는 정원-->광천읍 충서로400번길 102-36, 홍성, 충청남도, 대한민국",충청남도,그림이 있는 정원
35,"마이산 도립공원-->진안, 전라북도, 대한민국",전라북도,마이산 도립공원
36,"용궁사-->중구 운남로 199-1, 인천, 대한민국",인천,용궁사
37,"한벽당-->완산구 기린대로 2, 전주, 전라북도, 대한민국",전라북도,한벽당
38,"달아공원-->산양읍 산양일주로 1115, 통영, 경상남도, 대한민국",경상남도,달아공원
39,"벌교 홍교, 대한다원-->해맞이해안로 1752, 제주, 제주도, 대한민국",제주도,"벌교 홍교, 대한다원"
40,"안양 예술공원-->만안구 예술공원로 131, 안양, 경기도, 대한민국",경기도,안양 예술공원
41,"부천 활박물관과 궁도장-->8, Chunui-dong, Wonmi-gu, 부천, 경...",경기도,부천 활박물관과 궁도장
42,"파주 프로방스-->탄현면 성동리 82-1, 파주, 경기도, 대한민국",경기도,파주 프로방스
43,"융ㆍ건릉-->화성, 경기도, 대한민국",경기도,융ㆍ건릉
44,"자유공원-->중구 신포로27번길 80, 인천, 대한민국",인천,자유공원
45,"통일전망대-->탄현면 필승로 369, 파주, 경기도, 대한민국",경기도,통일전망대
46,"십리포 해수욕장-->영흥면 영흥북로 420-26, 인천, 대한민국",인천,십리포 해수욕장
47,"순천 드라마세트장 -->비례골길 24, 순천, 전라남도, 대한민국",전라남도,순천 드라마세트장

In [99]:
df_all = df_all[['관광지','분류','평점']]
df_all

                    관광지                                   분류   평점
0             암사동 선사주거지                              역사적인 장소  4.5
1                    화성                              역사적인 장소  4.0
2                   대부도                                    섬  4.0
3          국립현대미술관(과천관)                                아트뮤지엄  4.5
4                 독립기념관                                역사박물관  4.5
5                   공산성                역사적인 장소 • 즐길거리 & 랜드마크  4.5
6                  무령왕릉                              역사적인 장소  4.0
7                 충청수영성             역사적인 장소 • 성 • 경관이 좋은 산책로  5.0
8        천주교 대전교구 공세리성당                              종교적인 장소  4.5
9             팜카밀레 허브농원                              공원 • 가든  5.0
10        천주교 전주교구 전동성당                              종교적인 장소  4.0
11  무주 구천동계곡 방화동 가족휴양촌,            국립공원 • 자연 & 야생동물 서식지 • 계곡  5.0
12              순천만 갈대밭                                   공원  4.5
13                  용천사       역사적인 장소 • 종교적인 장소 • 경관이 좋은 산책로  4.0
14                   계림                            유서 깊은 산책로  4.0
15                  금오산                                   공원  4.5
16                 빙계계곡                         물길 • 산림 • 계곡  5.0
17              군위 삼존석굴                    역사적인 장소 • 종교적인 장소  4.5
18                주남저수지                        자연 & 야생동물 서식지  4.0
19                  청곡사                              종교적인 장소  3.5
20              고성 탈박물관                               전문 박물관  4.0
21                  임진성                                    성  3.5
22                다랑쉬오름                                   화산  5.0
23                  약천사                              종교적인 장소  4.5
24                제주 올레                              하이킹 트레일  4.5
25                월드컵공원                             기타 야외 활동  4.5
26    대한민국 국회의사당과 헌정기념관                               전문 박물관  4.0
27                  산사원                      전문 박물관 • 맥주 양조장  4.5
28                  탄금대                                   물길  4.5
29            지리산 산수유마을  유서 깊은 산책로 • 절경 드라이브 코스 • 경관이 좋은 산책로  4.0
30              항공우주박물관                                과학박물관  4.0
31               창녕 석빙고                              역사적인 장소  3.5
32                천제연폭포                                   폭포  4.0
33                  대둔산                                    산  4.5
34            그림이 있는 정원                                   가든  2.5
35             마이산 도립공원                                    산  4.5
36                  용궁사                              종교적인 장소  4.0
37                  한벽당                              역사적인 장소  4.0
38                 달아공원                        자연 & 야생동물 서식지  4.0
39          벌교 홍교, 대한다원                              산림 • 농장  4.5
40              안양 예술공원                                   공원  4.5
41         부천 활박물관과 궁도장                               전문 박물관  4.0
42              파주 프로방스                   특산물 & 기념품 가게 • 쇼핑몰  4.0
43                 융ㆍ건릉                              역사적인 장소  4.0
44                 자유공원                                   공원  4.0
45                통일전망대                             전망대 & 타워  4.0
46             십리포 해수욕장                                   해변  3.5
47           순천 드라마세트장                           즐길거리 & 랜드마크  4.0

In [100]:
df_all.to_csv('./data/카테고리 및 평점 추가.csv', encoding='utf-8-sig', header=False, index=False)

In [101]:
address_df.to_csv('./data/주소 추가.csv', encoding='utf-8-sig', header=False, index=False)